# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/triangulax',
                'doc_host': 'https://nikolas-claussen.github.io',
                'git_url': 'https://github.com/nikolas-claussen/triangulax',
                'lib_path': 'triangulax'},
  'syms': {'triangulax.core': {'triangulax.core.foo': ('core.html#foo', 'triangulax/core.py')}}}
