# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/04_adjacency_operators.ipynb.

# %% auto #0
__all__ = ['get_exterior_gradient', 'get_exterior_circulation', 'sum_he_to_vertex_incoming', 'sum_he_to_vertex_outgoing',
           'sum_he_to_vertex_opposite', 'sum_he_to_face', 'sum_face_to_he', 'sum_vertex_to_face',
           'average_vertex_to_face', 'sum_face_to_vertex', 'average_face_to_vertex', 'get_coordination_number',
           'compute_uniform_laplacian', 'get_uniform_laplacian']

# %% ../nbs/src/04_adjacency_operators.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp
import jax.experimental.sparse as jsparse

# %% ../nbs/src/04_adjacency_operators.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Float 

# %% ../nbs/src/04_adjacency_operators.ipynb #cef3ff0a
from . import mesh as msh

# %% ../nbs/src/04_adjacency_operators.ipynb #4a7c1a65
def get_exterior_gradient(hemesh: msh.HeMesh, v_field: Float[jax.Array, "n_vertices ..."]
                          ) -> Float[jax.Array, "n_hes ..."]:
    """Discrete exterior derivative: difference of a vertex field across each half-edge."""
    return v_field[hemesh.dest] - v_field[hemesh.orig]

def get_exterior_circulation(hemesh: msh.HeMesh, he_field: Float[jax.Array, "n_hes ..."]
                            ) -> Float[jax.Array, "n_faces ..."]:
    """Discrete exterior derivative: circulation of a half-edge field around each face."""
    return (he_field[hemesh.prv[hemesh.face_incident]]
            + he_field[hemesh.face_incident]
            + he_field[hemesh.nxt[hemesh.face_incident]])

# %% ../nbs/src/04_adjacency_operators.ipynb #8749ff1e
def sum_he_to_vertex_incoming(hemesh: msh.HeMesh, he_field: Float[jax.Array, "n_hes ..."]
                              ) -> Float[jax.Array, "n_vertices ..."]:
    """Sum a half-edge field onto destination vertices (scatter-add over incoming half-edges).

    Includes boundary half-edges. To exclude them, zero out the field at boundary
    half-edges before calling.
    """
    out_shape = (hemesh.n_vertices,) + he_field.shape[1:]
    v_field = jnp.zeros(out_shape, dtype=he_field.dtype)
    return v_field.at[hemesh.dest].add(he_field)

def sum_he_to_vertex_outgoing(hemesh: msh.HeMesh, he_field: Float[jax.Array, "n_hes ..."]
                              ) -> Float[jax.Array, "n_vertices ..."]:
    """Sum a half-edge field onto origin vertices (scatter-add over outgoing half-edges).

    Includes boundary half-edges. To exclude them, zero out the field at boundary
    half-edges before calling.
    """
    out_shape = (hemesh.n_vertices,) + he_field.shape[1:]
    v_field = jnp.zeros(out_shape, dtype=he_field.dtype)
    return v_field.at[hemesh.orig].add(he_field)

def sum_he_to_vertex_opposite(hemesh: msh.HeMesh, he_field: Float[jax.Array, "n_hes ..."]
                              ) -> Float[jax.Array, "n_vertices ..."]:
    """Sum a half-edge field onto opposite vertices (the vertex across the face from the half-edge).

    Warning: includes boundary half-edges, whose "opposite vertex" may not be meaningful.
    """
    out_shape = (hemesh.n_vertices,) + he_field.shape[1:]
    v_field = jnp.zeros(out_shape, dtype=he_field.dtype)
    return v_field.at[hemesh.dest[hemesh.nxt]].add(he_field)

# %% ../nbs/src/04_adjacency_operators.ipynb #c4634b84
def sum_he_to_face(hemesh: msh.HeMesh, he_field: Float[jax.Array, "n_hes ..."]
                  ) -> Float[jax.Array, "n_faces ..."]:
    """Sum over the three half-edges of each face. Same as `get_exterior_circulation`."""
    return get_exterior_circulation(hemesh, he_field)

def sum_face_to_he(hemesh: msh.HeMesh, f_field: Float[jax.Array, "n_faces ..."]
                  ) -> Float[jax.Array, "n_hes ..."]:
    """Sum face-field to half-edges. Each half-edge receives the sum of its face and its twin's face.

    Boundary half-edges (heface == -1) contribute zero from the boundary side.
    """
    # Pad with a zero sentinel so that heface == -1 maps to index n_faces (the sentinel)
    sentinel = jnp.zeros_like(f_field[:1])
    f_padded = jnp.concatenate([f_field, sentinel])
    heface_safe = jnp.where(hemesh.heface >= 0, hemesh.heface, hemesh.n_faces)
    heface_twin_safe = jnp.where(hemesh.heface[hemesh.twin] >= 0,
                                 hemesh.heface[hemesh.twin], hemesh.n_faces)
    return f_padded[heface_safe] + f_padded[heface_twin_safe]

# %% ../nbs/src/04_adjacency_operators.ipynb #566e2cf7
def sum_vertex_to_face(hemesh: msh.HeMesh, v_field: Float[jax.Array, "n_vertices ..."]
                  ) -> Float[jax.Array, "n_faces ..."]:
    """Sum vertex-field to faces. Sums over the three vertices of each face."""
    return (v_field[hemesh.orig[hemesh.face_incident]]
            + v_field[hemesh.dest[hemesh.face_incident]]
            + v_field[hemesh.dest[hemesh.nxt[hemesh.face_incident]]])

def average_vertex_to_face(hemesh: msh.HeMesh, v_field: Float[jax.Array, "n_vertices ..."]
                           ) -> Float[jax.Array, "n_faces ..."]:
    """Average vertex-field to faces (uniform 1/3 weights)."""
    return sum_vertex_to_face(hemesh, v_field) / 3

def sum_face_to_vertex(hemesh: msh.HeMesh, f_field: Float[jax.Array, "n_faces ..."]
                      ) -> Float[jax.Array, "n_vertices ..."]:
    """Sum face-field to vertices. Each vertex receives the sum over its incident faces."""
    out_shape = (hemesh.n_vertices,) + f_field.shape[1:]
    v_field = jnp.zeros(out_shape, dtype=f_field.dtype)
    v_field = v_field.at[hemesh.orig[hemesh.face_incident]].add(f_field)
    v_field = v_field.at[hemesh.dest[hemesh.face_incident]].add(f_field)
    v_field = v_field.at[hemesh.dest[hemesh.nxt[hemesh.face_incident]]].add(f_field)
    return v_field

def average_face_to_vertex(hemesh: msh.HeMesh, f_field: Float[jax.Array, "n_faces ..."]
                           ) -> Float[jax.Array, "n_vertices ..."]:
    """Average face-field to vertices (uniform weights, i.e., divided by number of incident faces)."""
    summed_field = sum_face_to_vertex(hemesh, f_field)
    weights = sum_face_to_vertex(hemesh, jnp.ones(hemesh.n_faces))
    return (summed_field.T / weights.T).T  # transpose to broadcast scalar weights over trailing dims

# %% ../nbs/src/04_adjacency_operators.ipynb #52d7cd28
def get_coordination_number(hemesh: msh.HeMesh) -> Float[jax.Array, " n_vertices"]:
    """Coordination number (vertex degree): number of neighboring vertices.

    Includes boundary half-edges, so boundary vertices count all their neighbors.
    """
    return sum_he_to_vertex_incoming(hemesh, jnp.ones(hemesh.n_hes))

# %% ../nbs/src/04_adjacency_operators.ipynb #f74e78fb
def compute_uniform_laplacian(hemesh: msh.HeMesh, v_field: Float[jax.Array, "n_vertices ..."]
                              ) -> Float[jax.Array, "n_vertices ..."]:
    """Apply the uniform Laplacian to a vertex field. Non-normalized, positive semi-definite."""
    he_gradient = get_exterior_gradient(hemesh, v_field)
    return sum_he_to_vertex_incoming(hemesh, he_gradient)

def get_uniform_laplacian(hemesh: msh.HeMesh) -> jsparse.BCOO:
    """Assemble the uniform Laplacian as a sparse BCOO matrix. Non-normalized, positive semi-definite."""
    row = hemesh.dest
    col = hemesh.orig
    data = -jnp.ones(hemesh.n_hes)
    data_diagonal = get_coordination_number(hemesh)
    row_diagonal, col_diagonal = jnp.arange(hemesh.n_vertices), jnp.arange(hemesh.n_vertices)
    data = jnp.concatenate([data, data_diagonal])
    row, col = jnp.concatenate([row, row_diagonal]), jnp.concatenate([col, col_diagonal])
    L = jsparse.BCOO((data, jnp.stack([row, col], axis=1)), shape=(hemesh.n_vertices, hemesh.n_vertices))
    return L
