# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/07_algorithms.ipynb.

# %% auto #0
__all__ = ['get_face_angles', 'get_mesh_quality_stats', 'is_locally_delaunay', 'fix_delaunay', 'smooth_vertices_laplacian']

# %% ../nbs/src/07_algorithms.ipynb #eb9cca6d
import numpy as np
import matplotlib.pyplot as plt
import meshplot

# %% ../nbs/src/07_algorithms.ipynb #d16e3883
import jax
import jax.numpy as jnp
import jax.experimental.sparse as jsparse

import functools

# %% ../nbs/src/07_algorithms.ipynb #adff06cb
from jaxtyping import Float, Bool, Int

# %% ../nbs/src/07_algorithms.ipynb #598702c5
from . import trigonometry as trig
from . import mesh as msh
from . import adjacency as adj
from . import geometry as geom
from . import topology as topo

# %% ../nbs/src/07_algorithms.ipynb #27c5404b
def get_face_angles(vertices: Float[jax.Array, "n_vertices dim"],
                        hemesh: msh.HeMesh) -> Float[jax.Array, "n_faces 3"]:
    """Get corner angle per face (radians).

    Uses the half-edge corner angles and takes the max over the three
    corners of every face.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.

    Returns
    -------
    Float[Array, "n_faces"]
        Maximum interior angle per triangle.
    """
    angles = geom.get_corner_angles(vertices, hemesh)
    fi = hemesh.face_incident
    face_angles = jnp.stack([angles[fi], angles[hemesh.nxt[fi]], angles[hemesh.prv[fi]]], axis=-1)
    return face_angles

# %% ../nbs/src/07_algorithms.ipynb #a8043eb3
def get_mesh_quality_stats(vertices: Float[jax.Array, "n_vertices dim"],
                           hemesh: msh.HeMesh, degenerate_angle: float = 5.0, 
                           digits: int = 5) -> dict:
    """Compute mesh quality statistics.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.
    degenerate_angle : float
        Threshold (degrees) for a triangle to be considered degenerate.
        (I.e. if max angle > pi-threshold or min angle < threshold.)
    digits : int
        Number of decimal digits to round the statistics to.
    Returns
    -------
    dict
        Dictionary with keys: 'areas_min', 'areas_max', 'areas_cv',
        'max_angle', 'min_angle', 'angles_std',
        'n_degenerate', 'n_total_faces'.
    """
    areas = geom.get_triangle_areas(vertices, hemesh)
    angles = get_face_angles(vertices, hemesh)
    is_degenerate = ( (jnp.rad2deg(jnp.max(angles, axis=-1)) > (180.0 - degenerate_angle))
                     | (jnp.rad2deg(jnp.min(angles, axis=-1)) < degenerate_angle) )

    return {
        'areas_min': round(float(areas.min()), digits),
        'areas_max': round(float(areas.max()), digits),
        'areas_cv': round(float(areas.std() / jnp.clip(areas.mean(), 1e-30)), digits),
        'max_angle': round(float(jnp.rad2deg(angles.max())), digits),
        'min_angle': round(float(jnp.rad2deg(angles.min())), digits),
        'angles_std': round(float(jnp.rad2deg(angles.std())), digits),
        'n_degenerate': int(is_degenerate.sum()),
        'n_total_faces': int(hemesh.n_faces),
    }

# %% ../nbs/src/07_algorithms.ipynb #a54dfea1
def is_locally_delaunay(vertices: Float[jax.Array, "n_vertices dim"],
                        hemesh: msh.HeMesh) -> Bool[jax.Array, " n_hes"]:
    """Check the local Delaunay condition for each edge.

    An interior edge is locally Delaunay when the sum of the two
    opposite angles does not exceed π.  Boundary edges are always
    considered Delaunay.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.

    Returns
    -------
    Bool[Array, "n_hes"]
        True where the edge satisfies the Delaunay condition.
    """
    angles = geom.get_corner_angles(vertices, hemesh)
    angle_sum = angles + angles[hemesh.twin]
    return hemesh.is_bdry_edge | (angle_sum <= jnp.pi + 1e-10)

# %% ../nbs/src/07_algorithms.ipynb #7f69059d
@functools.partial(jax.jit, static_argnames=['max_iters'])
def fix_delaunay(vertices: Float[jax.Array, "n_vertices dim"],
                 hemesh: msh.HeMesh,
                 max_iters: int = 2) -> tuple[msh.HeMesh, Int[jax.Array, ""]]:
    """Flip non-Delaunay edges iteratively until convergence.

    Each iteration identifies non-Delaunay interior edges and flips them
    using ``topology.flip_all``.  Stops when no more flips are needed
    or ``max_iters`` is reached.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (unchanged by flips).
    hemesh : HeMesh
        Half-edge mesh connectivity.
    max_iters : int
        Maximum number of sweep iterations.

    Returns
    -------
    hemesh_new : HeMesh
        Updated half-edge mesh with improved Delaunay quality.
    n_flips : int
        Total number of edges flipped.
    """
    def cond_fun(state):
        hemesh_s, n_flips, i, did_flip = state
        return (i < max_iters) & did_flip

    def body_fun(state):
        hemesh_s, n_flips, i, _ = state
        delaunay = is_locally_delaunay(vertices, hemesh_s)
        to_flip = ~delaunay & hemesh_s.is_unique & ~hemesh_s.is_bdry_edge
        n_new = to_flip.sum()
        hemesh_s = topo.flip_all(hemesh_s, to_flip)
        return (hemesh_s, n_flips + n_new, i + 1, n_new > 0)

    init_state = (hemesh, jnp.array(0), jnp.array(0), jnp.array(True))
    hemesh_out, n_flips, _, _ = jax.lax.while_loop(cond_fun, body_fun, init_state)
    return hemesh_out, n_flips

# %% ../nbs/src/07_algorithms.ipynb #18f83a5d
def smooth_vertices_laplacian(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                              step_size: float = 1.0, bc: str = 'fixed') -> Float[jax.Array, "n_vertices dim"]:
    """One step of tangential Laplacian vertex smoothing.

    Moves each vertex towards the mean position of its neighbours.
    For 3D meshes, the displacement is projected onto the tangent plane.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.
    step_size : float
        Fraction of displacement to apply (1 = full step).
    bc : str
        Boundary condition: ``'fixed'`` freezes boundary vertices,
        ``'free'`` allows them to move.

    Returns
    -------
    Float[Array, "n_vertices dim"]
        Updated vertex positions.
    """
    triangle_areas = geom.get_triangle_areas(vertices, hemesh)
    weights = triangle_areas[hemesh.heface] + triangle_areas[hemesh.heface[hemesh.twin]]
    normalization = adj.sum_he_to_vertex_incoming(hemesh, weights)
    average_neighbor = adj.sum_he_to_vertex_incoming(hemesh, weights[:, None] * vertices[hemesh.orig])
    average_neighbor = average_neighbor/ normalization[:, None]

    step = step_size * (average_neighbor - vertices)

    if vertices.shape[1] == 3:
        normals = geom.get_vertex_normals(vertices, hemesh)
        step = jax.vmap(trig.project_out_vector)(step, normals)

    if bc == 'fixed':
        step = jnp.where(hemesh.is_bdry[:, None], 0.0, step)

    return vertices + step
