# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/09_algorithms.ipynb.

# %% auto #0
__all__ = ['kabsch_align', 'get_face_angles', 'get_mesh_quality_stats', 'is_locally_delaunay', 'fix_delaunay',
           'smooth_vertices_laplacian']

# %% ../nbs/src/09_algorithms.ipynb #eb9cca6d
#| export


# %% ../nbs/src/09_algorithms.ipynb #d16e3883
import jax
import jax.numpy as jnp

# %% ../nbs/src/09_algorithms.ipynb #adff06cb
from jaxtyping import Float, Bool, Int

# %% ../nbs/src/09_algorithms.ipynb #598702c5
from . import trigonometry as trig
from . import mesh as msh
from . import adjacency as adj
from . import geometry as geom
from . import topology as topo

# %% ../nbs/src/09_algorithms.ipynb #3e45e7b3
def kabsch_align(v: Float[jax.Array, "n_vertices dim"], v_ref: Float[jax.Array, "n_vertices dim"]
                 ) -> tuple[Float[jax.Array, "n_vertices dim"],
                            Float[jax.Array, "dim dim"],
                            Float[jax.Array, " dim"]]:
    """Optimally rotate/translate v onto v_ref (differentiable Kabsch algorithm).

    The resulting rotation R is proper (det(R) = 1), so no reflections are allowed.
    Works in any dimension, and is compatible with jax.jit and jax.grad.
    The convention is ``aligned == v @ R + d``.

    Parameters
    ----------
    v : Float[jax.Array, "n_vertices dim"]
        vertices to be aligned
    v_ref : Float[jax.Array, "n_vertices dim"]
        reference vertices

    Returns
    -------
    aligned : Float[jax.Array, "n_vertices dim"]
        v optimally aligned to v_ref
    R : Float[jax.Array, "dim dim"]
        Optimal rotation matrix
    d : Float[jax.Array, "dim"]
        Optimal translation vector
    """
    d1 = v.mean(axis=0)
    d2 = v_ref.mean(axis=0)
    vc = v - d1
    rc = v_ref - d2
    U, _, Vt = jnp.linalg.svd(vc.T @ rc, full_matrices=False)  # full_matrices=False: full SVD has no JVP rule
    sign = jnp.sign(jnp.linalg.det(U @ Vt))
    # flip the last singular direction if needed, so that det(R) = +1 in any dimension
    R = (U * jnp.ones(U.shape[-1]).at[-1].set(sign)) @ Vt
    aligned = vc @ R + d2
    d = -d1 @ R + d2  # note: shadows the reflection sign above
    return aligned, R, d

# %% ../nbs/src/09_algorithms.ipynb #27c5404b
def get_face_angles(vertices: Float[jax.Array, "n_vertices dim"],
                        hemesh: msh.HeMesh) -> Float[jax.Array, "n_faces 3"]:
    """Get the three corner angles of every face (radians).

    Uses the half-edge corner angles. Angles within a face sum to pi.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.

    Returns
    -------
    Float[Array, "n_faces 3"]
        The three interior angles of each triangle.
    """
    angles = geom.get_corner_angles(vertices, hemesh)
    fi = hemesh.face_incident
    face_angles = jnp.stack([angles[fi], angles[hemesh.nxt[fi]], angles[hemesh.prv[fi]]], axis=-1)
    return face_angles

# %% ../nbs/src/09_algorithms.ipynb #a8043eb3
def get_mesh_quality_stats(vertices: Float[jax.Array, "n_vertices dim"],
                           hemesh: msh.HeMesh, degenerate_angle: float = 5.0, 
                           digits: int = 5) -> dict:
    """Compute mesh quality statistics.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.
    degenerate_angle : float
        Threshold (degrees) for a triangle to be considered degenerate.
        (I.e. if max angle > pi-threshold or min angle < threshold.)
    digits : int
        Number of decimal digits to round the statistics to.
    Returns
    -------
    dict
        Dictionary with keys: 'areas_min', 'areas_max', 'areas_cv',
        'max_angle', 'min_angle', 'angles_std',
        'n_degenerate', 'n_total_faces'.
    """
    areas = geom.get_triangle_areas(vertices, hemesh)
    angles = get_face_angles(vertices, hemesh)
    is_degenerate = ( (jnp.rad2deg(jnp.max(angles, axis=-1)) > (180.0 - degenerate_angle))
                     | (jnp.rad2deg(jnp.min(angles, axis=-1)) < degenerate_angle) )

    return {
        'areas_min': round(float(areas.min()), digits),
        'areas_max': round(float(areas.max()), digits),
        'areas_cv': round(float(areas.std() / jnp.clip(areas.mean(), 1e-30)), digits),
        'max_angle': round(float(jnp.rad2deg(angles.max())), digits),
        'min_angle': round(float(jnp.rad2deg(angles.min())), digits),
        'angles_std': round(float(jnp.rad2deg(angles.std())), digits),
        'n_degenerate': int(is_degenerate.sum()),
        'n_total_faces': int(hemesh.n_faces),
    }

# %% ../nbs/src/09_algorithms.ipynb #a54dfea1
def is_locally_delaunay(vertices: Float[jax.Array, "n_vertices dim"],
                        hemesh: msh.HeMesh) -> Bool[jax.Array, " n_hes"]:
    """Check the local Delaunay condition for each edge.

    An interior edge is locally Delaunay when the sum of the two
    opposite angles does not exceed π.  Boundary edges are always
    considered Delaunay.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.

    Returns
    -------
    Bool[Array, "n_hes"]
        True where the edge satisfies the Delaunay condition.
    """
    angles = geom.get_corner_angles(vertices, hemesh)
    angle_sum = angles + angles[hemesh.twin]
    return hemesh.is_bdry_edge | (angle_sum <= jnp.pi + 1e-10)

# %% ../nbs/src/09_algorithms.ipynb #7f69059d
def fix_delaunay(vertices: Float[jax.Array, "n_vertices dim"],
                 hemesh: msh.HeMesh,
                 max_iters: int = 2, max_flips: int = 10) -> tuple[msh.HeMesh, Int[jax.Array, ""]]:
    """Flip non-Delaunay edges iteratively until convergence.

    Each iteration identifies non-Delaunay interior edges and flips them
    using ``topology.flip_by_score``.  Stops when no more flips are needed
    or ``max_iters`` is reached.

    Important: when JIT-compiling, use jax.jit with static_argnames=['max_iters', 'max_flips'].

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (unchanged by flips).
    hemesh : HeMesh
        Half-edge mesh connectivity.
    max_iters : int
        Maximum number of sweep iterations.
    max_flips : int
        Maximum number of flips at each iteration.
    Returns
    -------
    hemesh_new : HeMesh
        Updated half-edge mesh with improved Delaunay quality.
    n_flips : int
        Total number of edges flipped.
    """
    def cond_fun(state):
        hemesh_s, n_flips, i, did_flip = state
        return (i < max_iters) & did_flip

    def body_fun(state):
        hemesh_s, n_flips, i, _ = state
        delaunay_score = geom.get_cotan_weights_per_edge(vertices, hemesh_s)
        hemesh_s, did_flip = topo.flip_by_score(hemesh_s, edge_score=delaunay_score,
                                                threshold=0.0, max_flips=max_flips)
        n_new = did_flip.sum() // 2
        return (hemesh_s, n_flips + n_new, i + 1, n_new > 0)

    init_state = (hemesh, jnp.array(0), jnp.array(0), jnp.array(True))
    hemesh_out, n_flips, _, _ = jax.lax.while_loop(cond_fun, body_fun, init_state)
    return hemesh_out, n_flips

# %% ../nbs/src/09_algorithms.ipynb #18f83a5d
def smooth_vertices_laplacian(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                              step_size: float = 1.0, bc: str = 'fixed') -> Float[jax.Array, "n_vertices dim"]:
    """One step of tangential Laplacian vertex smoothing.

    Moves each vertex towards the mean position of its neighbours.
    For 3D meshes, the displacement is projected onto the tangent plane.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh connectivity.
    step_size : float
        Fraction of displacement to apply (1 = full step).
    bc : str
        Boundary condition: 'fixed' freezes boundary vertices,
        'free' allows them to move, and 'slide' allows them to
        move only tangentially along the boundary.

    Returns
    -------
    Float[Array, "n_vertices dim"]
        Updated vertex positions.
    """
    triangle_areas = geom.get_triangle_areas(vertices, hemesh)
    # heface == -1 on boundary half-edges, which would silently pick up the last face's area
    def area_of(he):
        return jnp.where(hemesh.heface[he] == -1, 0.0, triangle_areas[hemesh.heface[he]])
    weights = area_of(jnp.arange(hemesh.n_hes)) + area_of(hemesh.twin)
    normalization = adj.sum_he_to_vertex_incoming(hemesh, weights)
    average_neighbor = adj.sum_he_to_vertex_incoming(hemesh, weights[:, None] * vertices[hemesh.orig])
    average_neighbor = average_neighbor/ normalization[:, None]

    step = step_size * (average_neighbor - vertices)

    if vertices.shape[1] == 3:
        normals = geom.get_vertex_normals(vertices, hemesh)
        step = jax.vmap(trig.project_out_vector)(step, normals)

    if bc not in ('fixed', 'free', 'slide'):
        raise ValueError(f"unknown bc {bc!r}; expected 'fixed', 'free' or 'slide'")

    if bc == 'fixed':
        step = jnp.where(hemesh.is_bdry[:, None], 0.0, step)

    if bc == 'slide':
        edges = vertices[hemesh.orig]-vertices[hemesh.dest]
        boundary_tangents = adj.sum_he_to_vertex_incoming(hemesh, edges * hemesh.is_bdry_he[:, None])
        # the tangent is exactly zero at interior vertices. jnp.linalg.norm has a NaN
        # gradient at 0, so guard the argument of the sqrt as well as the division.
        sq = jnp.sum(boundary_tangents**2, axis=-1, keepdims=True)
        safe_sq = jnp.where(sq > 0, sq, 1.0)
        boundary_tangents = jnp.where(sq > 0, boundary_tangents / jnp.sqrt(safe_sq), 0.0)
        step = jnp.where(hemesh.is_bdry[:, None], jax.vmap(trig.project_on_vector)(step, boundary_tangents), step)
    
    return vertices + step
