# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/08_elasticity.ipynb.

# %% auto #0
__all__ = ['FaceParam', 'EdgeParam', 'VertexParam', 'get_metric', 'get_reference_areas', 'get_neo_hookean_energy_density',
           'get_neo_hookean_energy', 'get_st_venant_kirchhoff_energy', 'get_dihedral_bending_energy',
           'get_edge_normals', 'get_second_fundamental_form', 'get_svk_bending_energy', 'get_helfrich_energy']

# %% ../nbs/src/08_elasticity.ipynb #042a9f36
import jax
import jax.numpy as jnp

# %% ../nbs/src/08_elasticity.ipynb #afdd02cb
from jaxtyping import Float

# %% ../nbs/src/08_elasticity.ipynb #4ab4e7a7
from . import geometry as geom
from .mesh import HeMesh

# %% ../nbs/src/08_elasticity.ipynb #12a19d1e
# Material parameters can be homogeneous (scalar) or inhomogeneous (per-face,
# per-half-edge, or per-vertex arrays); all energies broadcast them.
FaceParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_faces"]
EdgeParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_hes"]
VertexParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_vertices"]

# %% ../nbs/src/08_elasticity.ipynb #134aee7e
def get_metric(vertices: Float[jax.Array, "n_vertices dim"],
               hemesh: HeMesh) -> Float[jax.Array, "n_faces 2 2"]:
    """Metric tensor (first fundamental form) per triangle, in the face basis.

    For a triangle with vertices a, b, c, the basis is the pair of side vectors
    u = b - a, v = c - a, so g = [[u.u, u.v], [u.v, v.v]].

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face metric. Symmetric positive definite for non-degenerate triangles.
    """
    a, b, c = vertices[hemesh.faces.T]
    J = jnp.stack([b - a, c - a], axis=1)
    return jnp.einsum("fik,fjk->fij", J, J)


def get_reference_areas(metric_ref: Float[jax.Array, "n_faces 2 2"]
                        ) -> Float[jax.Array, " n_faces"]:
    """Triangle areas of the reference configuration, A0 = sqrt(det(g0)) / 2.

    Parameters
    ----------
    metric_ref : Float[Array, "n_faces 2 2"]
        Reference metric per triangle (see `get_metric`).

    Returns
    -------
    Float[Array, " n_faces"]
        Reference triangle areas.
    """
    return jnp.sqrt(jnp.linalg.det(metric_ref)) / 2

# %% ../nbs/src/08_elasticity.ipynb #27c9270b
def get_neo_hookean_energy_density(C: Float[jax.Array, "*batch 2 2"],
                                   mod_bulk: FaceParam, mod_shear: FaceParam
                                   ) -> Float[jax.Array, " *batch"]:
    """Neo-Hookean energy density from the Cauchy-Green deformation tensor C:
        W = mod_shear/2 * (tr(C)/J - 2) + mod_bulk/2 * (J - 1)^2
    where J = sqrt(det(C)) is the local area change.
    See https://en.wikipedia.org/wiki/Neo-Hookean_solid

    Parameters
    ----------
    C : Float[Array, "*batch 2 2"]
        Cauchy-Green tensor(s) C = g0^-1 g, positive definite.
    mod_bulk, mod_shear : float | Float[Array, ""] | Float[Array, " n_faces"]
        Bulk and shear moduli >= 0 (units: energy/area), scalar or batched.

    Returns
    -------
    Float[Array, "*batch"]
        Energy density (units: energy/area).
    """
    J = jnp.sqrt(jnp.linalg.det(C))
    return mod_shear/2 * (jnp.trace(C, axis1=-2, axis2=-1)/J - 2) + mod_bulk/2 * (J-1)**2


def get_neo_hookean_energy(vertices: Float[jax.Array, "n_vertices dim"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """Total neo-Hookean in-plane energy, integrated over the reference configuration:
        E = sum_f A0_f * W(C_f)
    with A0_f the reference areas and W the neo-Hookean density (see
    `get_neo_hookean_energy_density`).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, mod_bulk, mod_shear). metric_ref is the reference
        metric in the face basis (see `get_metric`). The moduli can be scalars
        or per-face arrays (inhomogeneous material).

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, mod_bulk, mod_shear = args
    C = jnp.linalg.solve(metric_ref, get_metric(vertices, hemesh))
    densities = get_neo_hookean_energy_density(C, mod_bulk, mod_shear)
    return (get_reference_areas(metric_ref) * densities).sum()

# %% ../nbs/src/08_elasticity.ipynb #628d811f
def get_st_venant_kirchhoff_energy(vertices: Float[jax.Array, "n_vertices dim"],
                                   args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                               FaceParam, FaceParam]
                                   ) -> Float[jax.Array, ""]:
    """Total St.-Venant-Kirchhoff in-plane energy:
        E = sum_f A0_f * (alpha * tr(C - I)^2 + 2 * beta * tr((C - I)^2))
    with C = g0^-1 g the Cauchy-Green tensor, integrated over the reference
    configuration. Quadratic in the (Green-Lagrange) strain.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, alpha, beta). metric_ref is the reference metric
        in the face basis (see `get_metric`). The Lame-type coefficients
        alpha, beta >= 0 (units: energy/area) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, alpha, beta = args
    strain = jnp.linalg.solve(metric_ref, get_metric(vertices, hemesh)) - jnp.eye(2)
    trace = jnp.trace(strain, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", strain, strain)
    return (get_reference_areas(metric_ref) * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #1a014f09
def get_dihedral_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                                args: tuple[HeMesh, EdgeParam, EdgeParam]
                                ) -> Float[jax.Array, ""]:
    """Discrete-shells bending energy from dihedral angles:
        E = sum_e mod_bending * l_e^2 / A_e * (theta_e - theta0_e)^2
    where the sum runs over interior edges, l_e is the edge length and
    A_e = (A_f + A_f')/3 the edge area (one third of the adjacent triangle areas).
    Scale invariant. Boundary edges do not contribute.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, theta0, mod_bending). The target angles theta0 (radians,
        sign convention of `geom.get_dihedral_angles`: positive = convex) and the
        bending modulus mod_bending >= 0 (units: energy) can be scalars or
        per-half-edge arrays; per-half-edge values must be twin-symmetric.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, theta0, mod_bending = args
    theta = geom.get_dihedral_angles(vertices, hemesh)
    lengths = geom.get_he_length(vertices, hemesh)
    face_areas = geom.get_triangle_areas(vertices, hemesh)
    edge_areas = (face_areas[hemesh.heface] + face_areas[hemesh.heface[hemesh.twin]]) / 3
    energies = mod_bending * lengths**2 / edge_areas * (theta - theta0)**2
    return jnp.where(hemesh.is_unique & ~hemesh.is_bdry_edge, energies, 0.0).sum()

# %% ../nbs/src/08_elasticity.ipynb #b03a547d
def get_edge_normals(vertices: Float[jax.Array, "n_vertices 3"], hemesh: HeMesh
                     ) -> Float[jax.Array, "n_hes 3"]:
    """Unit mid-edge normals: normalized average of the two adjacent face normals.

    For boundary edges, the normal of the single adjacent face is used.
    Indexed per half-edge; twin half-edges carry identical normals.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_hes 3"]
        Unit normal per half-edge.
    """
    normals = geom.get_triangle_normals(vertices, hemesh)
    n_self = jnp.where(hemesh.is_bdry_he[:, None],
                       normals[hemesh.heface[hemesh.twin]], normals[hemesh.heface])
    n_twin = jnp.where(hemesh.is_bdry_he[hemesh.twin][:, None],
                       n_self, normals[hemesh.heface[hemesh.twin]])
    n_sum = n_self + n_twin
    return n_sum / jnp.clip(jnp.linalg.norm(n_sum, axis=-1, keepdims=True), 1e-12)


def get_second_fundamental_form(vertices: Float[jax.Array, "n_vertices 3"], hemesh: HeMesh
                                ) -> Float[jax.Array, "n_faces 2 2"]:
    """Second fundamental form (extrinsic curvature tensor) per triangle, in the face basis.

    Finite-difference approximation from mid-edge normals (Grinspun et al. 2006),
    expressed in the same basis u, v as `get_metric`. The shape operator is
    S = g^-1 b, with mean curvature H = tr(S)/2 and Gaussian curvature K = det(S).

    Sign convention: a sphere with outward-pointing normals has b = g (H = +1 for
    the unit sphere), consistent with `geom.get_mean_curvature_dihedral`.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face second fundamental form (units: length).
    """
    edge_normals = get_edge_normals(vertices, hemesh)
    h0 = hemesh.face_incident
    a, b, c = vertices[hemesh.faces.T]
    u, v = b - a, c - a
    n_a = edge_normals[hemesh.nxt[h0]]  # normal of edge b-c, opposite vertex a
    n_b = edge_normals[hemesh.prv[h0]]  # normal of edge c-a, opposite vertex b
    n_c = edge_normals[h0]              # normal of edge a-b, opposite vertex c
    b11 = 2 * jnp.sum(u * (n_a - n_b), axis=-1)
    b22 = 2 * jnp.sum(v * (n_a - n_c), axis=-1)
    b12 = jnp.sum(u * (n_a - n_c), axis=-1) + jnp.sum(v * (n_a - n_b), axis=-1)
    return jnp.stack([jnp.stack([b11, b12], axis=-1),
                      jnp.stack([b12, b22], axis=-1)], axis=-2)

# %% ../nbs/src/08_elasticity.ipynb #c74baa1d
def get_svk_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """St.-Venant-Kirchhoff-type bending energy from the second fundamental form:
        E = sum_f A0_f * (alpha * tr(S)^2 + 2 * beta * tr(S^2)),  S = g0^-1 (b - b0)
    integrated over the reference configuration. For b0 = 0, the sheet prefers
    to be flat.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, metric_ref, b_ref, alpha, beta). metric_ref and the reference
        curvature b_ref are expressed in the face basis (see `get_metric` and
        `get_second_fundamental_form`). The bending moduli alpha, beta >= 0
        (units: energy) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, metric_ref, b_ref, alpha, beta = args
    S = jnp.linalg.solve(metric_ref, get_second_fundamental_form(vertices, hemesh) - b_ref)
    trace = jnp.trace(S, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", S, S)
    return (get_reference_areas(metric_ref) * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #4fa25cd4
def get_helfrich_energy(vertices: Float[jax.Array, "n_vertices 3"],
                        args: tuple[HeMesh, VertexParam, VertexParam, VertexParam]
                        ) -> Float[jax.Array, ""]:
    """Discrete Helfrich bending energy of a triangulated surface:
        E = kappa_H/2 * sum_i (H_i - H0)^2 * A_i + kappa_K * sum_i K_i * A_i^bar

    The mean-curvature term uses the dihedral-angle mean curvature and mixed
    Voronoi cell areas A_i. The Gaussian term uses the barycentric areas A_i^bar
    that normalize `geom.get_gaussian_curvature`, so it equals the total angle
    defect: on a closed mesh it is exactly 2*pi*chi*kappa_K (Gauss-Bonnet) and
    exerts no forces.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, H0, kappa_H, kappa_K): the spontaneous curvature H0
        (units: 1/length), the bending modulus kappa_H >= 0 and the Gaussian
        (saddle-splay) modulus kappa_K (units: energy). All three can be
        scalars or per-vertex arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, H0, kappa_H, kappa_K = args
    cell_areas = geom.get_voronoi_areas_robust(vertices, hemesh)
    H = geom.get_mean_curvature_dihedral(vertices, hemesh, normalize=True)
    K = geom.get_gaussian_curvature(vertices, hemesh)
    barycentric_areas = geom.get_barycentric_cell_areas(vertices, hemesh)
    return (kappa_H/2 * (H - H0)**2 * cell_areas).sum() + (kappa_K * K * barycentric_areas).sum()
