# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/08_elasticity.ipynb.

# %% auto #0
__all__ = ['FaceParam', 'EdgeParam', 'VertexParam', 'get_metric', 'get_area_from_metric', 'get_two_x_two_inverse',
           'get_neo_hookean_energy_density', 'get_neo_hookean_energy', 'get_st_venant_kirchhoff_energy',
           'get_dihedral_bending_energy', 'get_second_fundamental_form', 'get_svk_bending_energy',
           'get_helfrich_energy', 'make_normal_energy', 'make_tangential_energy', 'vertices_from_normal',
           'vertices_from_tangential']

# %% ../nbs/src/08_elasticity.ipynb #042a9f36
import jax
import jax.numpy as jnp

# %% ../nbs/src/08_elasticity.ipynb #afdd02cb
from jaxtyping import Float

# %% ../nbs/src/08_elasticity.ipynb #4ab4e7a7
from . import geometry as geom
from .mesh import HeMesh

# %% ../nbs/src/08_elasticity.ipynb #12a19d1e
# Material parameters can be homogeneous (scalar) or inhomogeneous (per-face,
# per-half-edge, or per-vertex arrays); all energies broadcast them.
FaceParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_faces"]
EdgeParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_hes"]
VertexParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_vertices"]

# %% ../nbs/src/08_elasticity.ipynb #134aee7e
def get_metric(vertices: Float[jax.Array, "n_vertices dim"],
               hemesh: HeMesh) -> Float[jax.Array, "n_faces 2 2"]:
    """Metric tensor (first fundamental form) per triangle, in the face basis.

    For a triangle with vertices a, b, c, the basis is the pair of side vectors
    u = b - a, v = c - a, so g = [[u.u, u.v], [u.v, v.v]].

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face metric. Symmetric positive definite for non-degenerate triangles.
    """
    a, b, c = vertices[hemesh.faces.T]
    J = jnp.stack([b - a, c - a], axis=1)
    return jnp.einsum("fik,fjk->fij", J, J)

def get_area_from_metric(metric: Float[jax.Array, "n_faces 2 2"]) -> Float[jax.Array, " n_faces"]:
    """Compute triangle areas from metric tensor.

    Parameters
    ----------
    metric : Float[Array, "n_faces 2 2"]
        Per-face metric. Symmetric positive definite for non-degenerate triangles.

    Returns
    -------
    Float[Array, "n_faces"]
        Per-face area.
    """
    return 0.5 * jnp.sqrt(jnp.linalg.det(metric))

def get_two_x_two_inverse(metric: Float[jax.Array, "*batch 2 2"]) -> Float[jax.Array, "*batch 2 2"]:
    """Closed-form inverse of 2x2 metric tensor(s), inv(g) = adj(g)/det(g).

    Much faster than jnp.linalg.inv/solve for 2x2 matrices.

    Parameters
    ----------
    metric : Float[Array, "*batch 2 2"]
        2x2 matrix/matrices; must be non-singular (e.g. metrics of
        non-degenerate triangles).

    Returns
    -------
    Float[Array, "*batch 2 2"]
        Inverse matrices.
    """
    a, b = metric[..., 0, 0], metric[..., 0, 1]
    c, d = metric[..., 1, 0], metric[..., 1, 1]
    adjugate = jnp.stack([jnp.stack([d, -b], axis=-1),
                          jnp.stack([-c, a], axis=-1)], axis=-2)
    return adjugate / (a*d - b*c)[..., None, None]

# %% ../nbs/src/08_elasticity.ipynb #27c9270b
def get_neo_hookean_energy_density(C: Float[jax.Array, "*batch 2 2"],
                                   mod_bulk: FaceParam, mod_shear: FaceParam
                                   ) -> Float[jax.Array, " *batch"]:
    """Neo-Hookean energy density from the Cauchy-Green deformation tensor C:
        W = mod_shear/2 * (tr(C)/J - 2) + mod_bulk/2 * (J - 1)^2
    where J = sqrt(det(C)) is the local area change.
    See https://en.wikipedia.org/wiki/Neo-Hookean_solid

    Parameters
    ----------
    C : Float[Array, "*batch 2 2"]
        Cauchy-Green tensor(s) C = g0^-1 g, positive definite.
    mod_bulk, mod_shear : float | Float[Array, ""] | Float[Array, " n_faces"]
        Bulk and shear moduli >= 0 (units: energy/area), scalar or batched.

    Returns
    -------
    Float[Array, "*batch"]
        Energy density (units: energy/area).
    """
    J = jnp.sqrt(jnp.linalg.det(C))
    return mod_shear/2 * (jnp.trace(C, axis1=-2, axis2=-1)/J - 2) + mod_bulk/2 * (J-1)**2


def get_neo_hookean_energy(vertices: Float[jax.Array, "n_vertices dim"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """Total neo-Hookean in-plane energy, integrated over the reference configuration:
        E = sum_f A0_f * W(C_f)
    with A0_f the reference areas and W the neo-Hookean density (see
    `get_neo_hookean_energy_density`).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, mod_bulk, mod_shear). metric_ref is the reference
        metric in the face basis (see `get_metric`). The moduli can be scalars
        or per-face arrays (inhomogeneous material).

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, mod_bulk, mod_shear = args
    C = get_two_x_two_inverse(metric_ref) @ get_metric(vertices, hemesh)
    densities = get_neo_hookean_energy_density(C, mod_bulk, mod_shear)
    areas = get_area_from_metric(metric_ref)
    return (areas * densities).sum()

# %% ../nbs/src/08_elasticity.ipynb #628d811f
def get_st_venant_kirchhoff_energy(vertices: Float[jax.Array, "n_vertices dim"],
                                   args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                               FaceParam, FaceParam]
                                   ) -> Float[jax.Array, ""]:
    """Total St.-Venant-Kirchhoff in-plane energy:
        E = sum_f A0_f * (alpha * tr(C - I)^2 + 2 * beta * tr((C - I)^2))
    with C = g0^-1 g the Cauchy-Green tensor, integrated over the reference
    configuration. Quadratic in the (Green-Lagrange) strain.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, alpha, beta). metric_ref is the reference metric
        in the face basis (see `get_metric`). The Lame-type coefficients
        alpha, beta >= 0 (units: energy/area) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, alpha, beta = args
    strain = get_two_x_two_inverse(metric_ref) @ get_metric(vertices, hemesh) - jnp.eye(2)
    trace = jnp.trace(strain, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", strain, strain)
    areas = get_area_from_metric(metric_ref)
    return (areas * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #1a014f09
def get_dihedral_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                                args: tuple[HeMesh, EdgeParam, EdgeParam]
                                ) -> Float[jax.Array, ""]:
    """Discrete-shells bending energy from dihedral angles:
        E = sum_e mod_bending * l_e^2 / A_e * (theta_e - theta0_e)^2
    where the sum runs over interior edges, l_e is the edge length and
    A_e = (A_f + A_f')/3 the edge area (one third of the adjacent triangle areas).
    Scale invariant. Boundary edges do not contribute.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, theta0, mod_bending). The target angles theta0 (radians,
        sign convention of `geom.get_dihedral_angles`: positive = convex) and the
        bending modulus mod_bending >= 0 (units: energy) can be scalars or
        per-half-edge arrays; per-half-edge values must be twin-symmetric.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, theta0, mod_bending = args
    theta = geom.get_dihedral_angles(vertices, hemesh)
    lengths = geom.get_he_length(vertices, hemesh)
    face_areas = geom.get_triangle_areas(vertices, hemesh)
    edge_areas = (face_areas[hemesh.heface] + face_areas[hemesh.heface[hemesh.twin]]) / 3
    energies = mod_bending * lengths**2 / edge_areas * (theta - theta0)**2
    return jnp.where(hemesh.is_unique & ~hemesh.is_bdry_edge, energies, 0.0).sum()

# %% ../nbs/src/08_elasticity.ipynb #b03a547d
def get_second_fundamental_form(vertices: Float[jax.Array, "n_vertices 3"], hemesh: HeMesh
                                ) -> Float[jax.Array, "n_faces 2 2"]:
    """Second fundamental form (extrinsic curvature tensor) per triangle, in the face basis.

    Finite-difference approximation from mid-edge normals (Grinspun et al. 2006),
    expressed in the same basis u, v as `get_metric`. The shape operator is
    S = g^-1 b, with mean curvature H = tr(S)/2 and Gaussian curvature K = det(S).

    Sign convention: a sphere with outward-pointing normals has b = g (H = +1 for
    the unit sphere), consistent with `geom.get_mean_curvature_dihedral`.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face second fundamental form (units: length).
    """
    edge_normals = geom.get_edge_normals(vertices, hemesh)
    h0 = hemesh.face_incident
    a, b, c = vertices[hemesh.faces.T]
    u, v = b - a, c - a
    n_a = edge_normals[hemesh.nxt[h0]]  # normal of edge b-c, opposite vertex a
    n_b = edge_normals[hemesh.prv[h0]]  # normal of edge c-a, opposite vertex b
    n_c = edge_normals[h0]              # normal of edge a-b, opposite vertex c
    b11 = jnp.sum(u * (n_a - n_b), axis=-1)
    b22 = jnp.sum(v * (n_a - n_c), axis=-1)
    b12 = jnp.sum(u * (n_a - n_c), axis=-1)
    b21 = jnp.sum(v * (n_a - n_b), axis=-1)
    return 2*jnp.stack([jnp.stack([b11, b12], axis=-1),
                        jnp.stack([b21, b22], axis=-1)], axis=-2)

# %% ../nbs/src/08_elasticity.ipynb #c74baa1d
def get_svk_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """St.-Venant-Kirchhoff-type bending energy from the second fundamental form:
        E = sum_f A0_f * (alpha * tr(S)^2 + 2 * beta * tr(S^2)),  S = g0^-1 (b - b0)
    integrated over the reference configuration. For b0 = 0, the sheet prefers
    to be flat.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, metric_ref, b_ref, alpha, beta). metric_ref and the reference
        curvature b_ref are expressed in the face basis (see `get_metric` and
        `get_second_fundamental_form`). The bending moduli alpha, beta >= 0
        (units: energy) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, metric_ref, b_ref, alpha, beta = args
    S = get_two_x_two_inverse(metric_ref) @ (get_second_fundamental_form(vertices, hemesh) - b_ref)
    trace = jnp.trace(S, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", S, S)
    areas = get_area_from_metric(metric_ref)
    return (areas * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #4fa25cd4
def get_helfrich_energy(vertices: Float[jax.Array, "n_vertices 3"],
                        args: tuple[HeMesh, VertexParam, VertexParam, VertexParam]
                        ) -> Float[jax.Array, ""]:
    """Discrete Helfrich bending energy of a triangulated surface:
        E = kappa_H/2 * sum_i (H_i - H0)^2 * A_i + kappa_K * sum_i K_i * A_i^bar

    The mean-curvature term uses the dihedral-angle mean curvature and mixed
    Voronoi cell areas A_i. On a closed mesh the Gaussian curvature term is
    exactly 2*pi*chi*kappa_K (Gauss-Bonnet) and exerts no forces.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, H0, kappa_H, kappa_K): the spontaneous curvature H0
        (units: 1/length), the bending modulus kappa_H >= 0 and the Gaussian
        (saddle-splay) modulus kappa_K (units: energy). All three can be
        scalars or per-vertex arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, H0, kappa_H, kappa_K = args
    cell_areas = geom.get_voronoi_areas_robust(vertices, hemesh)
    H = geom.get_mean_curvature_dihedral(vertices, hemesh, normalize=True)
    K = geom.get_gaussian_curvature(vertices, hemesh)
    return ((kappa_H/2 * (H - H0)**2 + kappa_K * K) * cell_areas).sum()

# %% ../nbs/src/08_elasticity.ipynb #13576da4
def make_normal_energy(energy_fn, v0: Float[jax.Array, "n 3"],
                       normals: Float[jax.Array, "n 3"]):
    """Wrap energy_fn(vertices, args) to optimize over normal heights h ∈ ℝⁿ.

    vertices(h) = v0 + h[:, None] * normals.
    """
    def energy(h, args):
        return energy_fn(v0 + h[:, None] * normals, args)
    return energy


def make_tangential_energy(energy_fn, v0: Float[jax.Array, "n 3"],
                           basis: Float[jax.Array, "n 2 3"]):
    """Wrap energy_fn(vertices, args) to optimize over tangent coords t ∈ ℝⁿˣ².

    vertices(t) = v0 + einsum('vi,vid->vd', t, basis).
    """
    def energy(t, args):
        return energy_fn(v0 + jnp.einsum("vi,vid->vd", t, basis), args)
    return energy


def vertices_from_normal(v0, h, normals):
    """Reconstruct vertices from base + normal displacement."""
    return v0 + h[:, None] * normals


def vertices_from_tangential(v0, t, basis):
    """Reconstruct vertices from base + tangential displacement.
    The tangential basis can be computed using the geometry module, geom.get_vertex_tangent_basis(vertices, hemesh).
    """
    return v0 + jnp.einsum("vi,vid->vd", t, basis)
