# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/08_elasticity.ipynb.

# %% auto #0
__all__ = ['FaceParam', 'EdgeParam', 'VertexParam', 'ScalarParam', 'get_metric', 'get_area_from_metric', 'get_two_x_two_inverse',
           'get_neo_hookean_energy_density', 'get_neo_hookean_energy', 'get_st_venant_kirchhoff_energy',
           'get_dihedral_bending_energy', 'get_second_fundamental_form', 'get_svk_bending_energy',
           'get_helfrich_energy', 'get_area_constraint_energy', 'get_volume_constraint_energy', 'make_normal_energy',
           'make_tangential_energy', 'vertices_from_normal', 'vertices_from_tangential']

# %% ../nbs/src/08_elasticity.ipynb #042a9f36
import jax
import jax.numpy as jnp

# %% ../nbs/src/08_elasticity.ipynb #afdd02cb
from jaxtyping import Float
from collections.abc import Callable


# %% ../nbs/src/08_elasticity.ipynb #4ab4e7a7
from . import geometry as geom
from .mesh import HeMesh

# %% ../nbs/src/08_elasticity.ipynb #12a19d1e
# Material parameters can be homogeneous (scalar) or inhomogeneous (per-face,
# per-half-edge, or per-vertex arrays); all energies broadcast them.
FaceParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_faces"]
EdgeParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_hes"]
VertexParam = float | Float[jax.Array, ""] | Float[jax.Array, " n_vertices"]

# %% ../nbs/src/08_elasticity.ipynb #134aee7e
def get_metric(vertices: Float[jax.Array, "n_vertices dim"],
               hemesh: HeMesh) -> Float[jax.Array, "n_faces 2 2"]:
    """Metric tensor (first fundamental form) per triangle, in the face basis.

    For a triangle with vertices a, b, c, the basis is the pair of side vectors
    u = b - a, v = c - a, so g = [[u.u, u.v], [u.v, v.v]].

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face metric. Symmetric positive definite for non-degenerate triangles.
    """
    a, b, c = vertices[hemesh.faces.T]
    J = jnp.stack([b - a, c - a], axis=1)
    return jnp.einsum("fik,fjk->fij", J, J)

def get_area_from_metric(metric: Float[jax.Array, "n_faces 2 2"]) -> Float[jax.Array, " n_faces"]:
    """Compute triangle areas from metric tensor.

    Parameters
    ----------
    metric : Float[Array, "n_faces 2 2"]
        Per-face metric. Symmetric positive definite for non-degenerate triangles.

    Returns
    -------
    Float[Array, "n_faces"]
        Per-face area.
    """
    # det is >= 0 mathematically but rounds negative near degeneracy, where sqrt -> NaN
    return 0.5 * jnp.sqrt(jnp.clip(jnp.linalg.det(metric), 0.0))

def get_two_x_two_inverse(metric: Float[jax.Array, "*batch 2 2"]) -> Float[jax.Array, "*batch 2 2"]:
    """Closed-form inverse of 2x2 metric tensor(s), inv(g) = adj(g)/det(g).

    Much faster than jnp.linalg.inv/solve for 2x2 matrices.

    Parameters
    ----------
    metric : Float[Array, "*batch 2 2"]
        2x2 matrix/matrices; must be non-singular (e.g. metrics of
        non-degenerate triangles).

    Returns
    -------
    Float[Array, "*batch 2 2"]
        Inverse matrices.
    """
    a, b = metric[..., 0, 0], metric[..., 0, 1]
    c, d = metric[..., 1, 0], metric[..., 1, 1]
    adjugate = jnp.stack([jnp.stack([d, -b], axis=-1),
                          jnp.stack([-c, a], axis=-1)], axis=-2)
    return adjugate / (a*d - b*c)[..., None, None]

# %% ../nbs/src/08_elasticity.ipynb #27c9270b
def get_neo_hookean_energy_density(C: Float[jax.Array, "*batch 2 2"],
                                   mod_bulk: FaceParam, mod_shear: FaceParam
                                   ) -> Float[jax.Array, " *batch"]:
    """Neo-Hookean energy density from the Cauchy-Green deformation tensor C:
        W = mod_shear/2 * (tr(C)/J - 2) + mod_bulk/2 * (J - 1)^2
    where J = sqrt(det(C)) is the local area change.
    See https://en.wikipedia.org/wiki/Neo-Hookean_solid

    Parameters
    ----------
    C : Float[Array, "*batch 2 2"]
        Cauchy-Green tensor(s) C = g0^-1 g, positive definite.
    mod_bulk, mod_shear : float | Float[Array, ""] | Float[Array, " n_faces"]
        Bulk and shear moduli >= 0 (units: energy/area), scalar or batched.

    Returns
    -------
    Float[Array, "*batch"]
        Energy density (units: energy/area).
    """
    # clip at 0: det rounds negative at/past degeneracy, and sqrt of a negative gives
    # NaN, which destroys the +inf barrier that makes neo-Hookean inversion-safe.
    J = jnp.sqrt(jnp.clip(jnp.linalg.det(C), 0.0))
    return mod_shear/2 * (jnp.trace(C, axis1=-2, axis2=-1)/J - 2) + mod_bulk/2 * (J-1)**2


def get_neo_hookean_energy(vertices: Float[jax.Array, "n_vertices dim"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """Total neo-Hookean in-plane energy, integrated over the reference configuration:
        E = sum_f A0_f * W(C_f)
    with A0_f the reference areas and W the neo-Hookean density (see
    `get_neo_hookean_energy_density`).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, mod_bulk, mod_shear). metric_ref is the reference
        metric in the face basis (see `get_metric`). The moduli can be scalars
        or per-face arrays (inhomogeneous material).

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, mod_bulk, mod_shear = args
    C = get_two_x_two_inverse(metric_ref) @ get_metric(vertices, hemesh)
    densities = get_neo_hookean_energy_density(C, mod_bulk, mod_shear)
    areas = get_area_from_metric(metric_ref)
    return (areas * densities).sum()

# %% ../nbs/src/08_elasticity.ipynb #628d811f
def get_st_venant_kirchhoff_energy(vertices: Float[jax.Array, "n_vertices dim"],
                                   args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                               FaceParam, FaceParam]
                                   ) -> Float[jax.Array, ""]:
    """Total St.-Venant-Kirchhoff in-plane energy:
        E = sum_f A0_f * (alpha * tr(C - I)^2 + 2 * beta * tr((C - I)^2))
    with C = g0^-1 g the Cauchy-Green tensor, integrated over the reference
    configuration. Quadratic in the (Green-Lagrange) strain.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions (dim = 2 or 3).
    args : tuple
        (hemesh, metric_ref, alpha, beta). metric_ref is the reference metric
        in the face basis (see `get_metric`). The Lame-type coefficients
        alpha, beta >= 0 (units: energy/area) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total elastic energy.
    """
    hemesh, metric_ref, alpha, beta = args
    strain = get_two_x_two_inverse(metric_ref) @ get_metric(vertices, hemesh) - jnp.eye(2)
    trace = jnp.trace(strain, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", strain, strain)
    areas = get_area_from_metric(metric_ref)
    return (areas * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #1a014f09
def get_dihedral_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                                args: tuple[HeMesh, EdgeParam, EdgeParam]
                                ) -> Float[jax.Array, ""]:
    """Discrete-shells bending energy from dihedral angles:
        E = sum_e mod_bending * l_e^2 / A_e * (theta_e - theta0_e)^2
    where the sum runs over interior edges, l_e is the edge length and
    A_e = (A_f + A_f')/3 the edge area (one third of the adjacent triangle areas).
    Scale invariant. Boundary edges do not contribute.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, theta0, mod_bending). The target angles theta0 (radians,
        sign convention of `geom.get_dihedral_angles`: positive = convex) and the
        bending modulus mod_bending >= 0 (units: energy) can be scalars or
        per-half-edge arrays; per-half-edge values must be twin-symmetric.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, theta0, mod_bending = args
    theta = geom.get_dihedral_angles(vertices, hemesh)
    lengths = geom.get_he_length(vertices, hemesh)
    face_areas = geom.get_triangle_areas(vertices, hemesh)
    edge_areas = (face_areas[hemesh.heface] + face_areas[hemesh.heface[hemesh.twin]]) / 3
    # both adjacent triangles can be degenerate, giving 0/0 = NaN which the mask below
    # cannot repair; make the denominator safe first.
    safe_edge_areas = jnp.where(edge_areas > 0, edge_areas, 1.0)
    energies = mod_bending * lengths**2 / safe_edge_areas * (theta - theta0)**2
    keep = hemesh.is_unique & ~hemesh.is_bdry_edge & (edge_areas > 0)
    return jnp.where(keep, energies, 0.0).sum()

# %% ../nbs/src/08_elasticity.ipynb #b03a547d
def get_second_fundamental_form(vertices: Float[jax.Array, "n_vertices 3"], hemesh: HeMesh
                                ) -> Float[jax.Array, "n_faces 2 2"]:
    """Second fundamental form (extrinsic curvature tensor) per triangle, in the face basis.

    Finite-difference approximation from mid-edge normals (Grinspun et al. 2006),
    expressed in the same basis u, v as `get_metric`. The shape operator is
    S = g^-1 b, with mean curvature H = tr(S)/2 and Gaussian curvature K = det(S).

    Sign convention: a sphere with outward-pointing normals has b = g (H = +1 for
    the unit sphere), consistent with `geom.get_mean_curvature_dihedral`.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 2"]
        Per-face second fundamental form (units: length).
    """
    edge_normals = geom.get_edge_normals(vertices, hemesh)
    h0 = hemesh.face_incident
    a, b, c = vertices[hemesh.faces.T]
    u, v = b - a, c - a
    n_a = edge_normals[hemesh.nxt[h0]]  # normal of edge b-c, opposite vertex a
    n_b = edge_normals[hemesh.prv[h0]]  # normal of edge c-a, opposite vertex b
    n_c = edge_normals[h0]              # normal of edge a-b, opposite vertex c
    b11 = jnp.sum(u * (n_a - n_b), axis=-1)
    b22 = jnp.sum(v * (n_a - n_c), axis=-1)
    b12 = jnp.sum(u * (n_a - n_c), axis=-1)
    b21 = jnp.sum(v * (n_a - n_b), axis=-1)
    return 2*jnp.stack([jnp.stack([b11, b12], axis=-1),
                        jnp.stack([b21, b22], axis=-1)], axis=-2)

# %% ../nbs/src/08_elasticity.ipynb #c74baa1d
def get_svk_bending_energy(vertices: Float[jax.Array, "n_vertices 3"],
                           args: tuple[HeMesh, Float[jax.Array, "n_faces 2 2"],
                                       Float[jax.Array, "n_faces 2 2"],
                                       FaceParam, FaceParam]
                           ) -> Float[jax.Array, ""]:
    """St.-Venant-Kirchhoff-type bending energy from the second fundamental form:
        E = sum_f A0_f * (alpha * tr(S)^2 + 2 * beta * tr(S^2)),  S = g0^-1 (b - b0)
    integrated over the reference configuration. For b0 = 0, the sheet prefers
    to be flat.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, metric_ref, b_ref, alpha, beta). metric_ref and the reference
        curvature b_ref are expressed in the face basis (see `get_metric` and
        `get_second_fundamental_form`). The bending moduli alpha, beta >= 0
        (units: energy) can be scalars or per-face arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, metric_ref, b_ref, alpha, beta = args
    S = get_two_x_two_inverse(metric_ref) @ (get_second_fundamental_form(vertices, hemesh) - b_ref)
    trace = jnp.trace(S, axis1=-2, axis2=-1)
    trace_sq = jnp.einsum("fij,fji->f", S, S)
    areas = get_area_from_metric(metric_ref)
    return (areas * (alpha*trace**2 + 2*beta*trace_sq)).sum()

# %% ../nbs/src/08_elasticity.ipynb #4fa25cd4
def get_helfrich_energy(vertices: Float[jax.Array, "n_vertices 3"],
                        args: tuple[HeMesh, VertexParam, VertexParam, VertexParam]
                        ) -> Float[jax.Array, ""]:
    """Discrete Helfrich bending energy of a triangulated surface:
        E = kappa_H/2 * sum_i (H_i - H0)^2 * A_i + kappa_K * sum_i K_i * A_i^bar

    The mean-curvature term uses the dihedral-angle mean curvature and mixed
    Voronoi cell areas A_i. On a closed mesh the Gaussian curvature term is
    exactly 2*pi*chi*kappa_K (Gauss-Bonnet) and exerts no forces.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        (hemesh, H0, kappa_H, kappa_K):
        the mesh connectivity, the spontaneous curvature H0 (units: 1/length),
        the bending modulus kappa_H >= 0 and the Gaussian modulus kappa_K (units: energy).
        H0, kappa_H, kappa_K can be scalars or per-vertex arrays.

    Returns
    -------
    Float[Array, ""]
        Total bending energy.
    """
    hemesh, H0, kappa_H, kappa_K = args
    cell_areas = geom.get_voronoi_areas_robust(vertices, hemesh)
    H = geom.get_mean_curvature_dihedral(vertices, hemesh, normalize=True)
    K = geom.get_gaussian_curvature(vertices, hemesh)
    return ((kappa_H/2 * (H - H0)**2 + kappa_K * K) * cell_areas).sum()

# %% ../nbs/src/08_elasticity.ipynb #constraints
ScalarParam = float | Float[jax.Array, ""]


def get_area_constraint_energy(vertices: Float[jax.Array, "n_vertices dim"],
                               args: tuple[HeMesh, ScalarParam, ScalarParam]
                               ) -> Float[jax.Array, ""]:
    """Quadratic penalty on the total surface area:
        E = modulus/2 * (A - A0)^2

    Note this is a *global* constraint on the total area, not a per-face one. Combine it
    with a bending energy yourself; the energies in this module are deliberately separate
    so they can be mixed and weighted freely.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    args : tuple
        ``(hemesh, area_0, modulus)``: the target total area A0 (units: length^2) and the
        penalty modulus (units: energy/length^4).

    Returns
    -------
    Float[Array, ""]
        Constraint energy. Zero exactly when the total area equals A0.
    """
    hemesh, area_0, modulus = args
    return modulus / 2 * (geom.get_area(vertices, hemesh) - area_0) ** 2


def get_volume_constraint_energy(vertices: Float[jax.Array, "n_vertices 3"],
                                 args: tuple[HeMesh, ScalarParam, ScalarParam]
                                 ) -> Float[jax.Array, ""]:
    """Quadratic penalty on the enclosed volume:
        E = modulus/2 * (V - V0)^2

    Requires a closed, consistently oriented mesh (`geometry.get_volume` checks this).
    The volume is signed, so V0 should have the same sign as the initial configuration's
    volume -- positive for outward-oriented faces.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions.
    args : tuple
        ``(hemesh, volume_0, modulus)``: the target enclosed volume V0 (units: length^3)
        and the penalty modulus (units: energy/length^6).

    Returns
    -------
    Float[Array, ""]
        Constraint energy. Zero exactly when the enclosed volume equals V0.
    """
    hemesh, volume_0, modulus = args
    return modulus / 2 * (geom.get_volume(vertices, hemesh) - volume_0) ** 2


# %% ../nbs/src/08_elasticity.ipynb #13576da4
def make_normal_energy(energy_fn: Callable, v0: Float[jax.Array, "n 3"],
                       normals: Float[jax.Array, "n 3"]) -> Callable:
    """Wrap energy_fn(vertices, args) to optimize over normal heights h ∈ ℝⁿ.

    vertices(h) = v0 + h[:, None] * normals, see `vertices_from_normal`.

    Parameters
    ----------
    energy_fn : Callable
        Energy with signature ``energy_fn(vertices, args) -> scalar``.
    v0 : Float[Array, "n 3"]
        Base vertex positions.
    normals : Float[Array, "n 3"]
        Per-vertex displacement directions, e.g. `geom.get_vertex_normals`.

    Returns
    -------
    Callable
        Energy with signature ``energy(h, args) -> scalar``.
    """
    def energy(h, args):
        return energy_fn(v0 + h[:, None] * normals, args)
    return energy


def make_tangential_energy(energy_fn: Callable, v0: Float[jax.Array, "n 3"],
                           basis: Float[jax.Array, "2 n 3"]) -> Callable:
    """Wrap energy_fn(vertices, args) to optimize over tangent coords t ∈ ℝⁿˣ².

    vertices(t) = v0 + einsum('vi,ivd->vd', t, basis), see `vertices_from_tangential`.

    Any basis (orthonormal or not) which spans the tangent plane is valid,
    but the same basis must be used in make_tangential_energy and
    in vertices_from_tangential to recover the 3D vertex positions.

    Parameters
    ----------
    energy_fn : Callable
        Energy with signature ``energy_fn(vertices, args) -> scalar``.
    v0 : Float[Array, "n 3"]
        Base vertex positions.
    basis : Float[Array, "2 n 3"]
        Tangent basis, in the ``(2, n_vertices, 3)`` layout returned by
        `geom.get_vertex_tangent_basis`.

    Returns
    -------
    Callable
        Energy with signature ``energy(t, args) -> scalar``.
    """
    def energy(t, args):
        return energy_fn(vertices_from_tangential(v0, t, basis), args)
    return energy


def vertices_from_normal(v0: Float[jax.Array, "n 3"], h: Float[jax.Array, " n"],
                         normals: Float[jax.Array, "n 3"]) -> Float[jax.Array, "n 3"]:
    """Reconstruct vertices from base positions + normal displacement."""
    return v0 + h[:, None] * normals


def vertices_from_tangential(v0: Float[jax.Array, "n 3"], t: Float[jax.Array, "n 2"],
                             basis: Float[jax.Array, "2 n 3"]) -> Float[jax.Array, "n 3"]:
    """Reconstruct vertices from base positions + tangential displacement.

    `basis` is expected in the ``(2, n_vertices, 3)`` layout returned by
    `geom.get_vertex_tangent_basis(vertices, hemesh)`.
    """
    return v0 + jnp.einsum("vi,ivd->vd", t, basis)
