# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/05_geometric_quantities.ipynb.

# %% auto #0
__all__ = ['get_he_length', 'get_triangle_areas', 'get_barycentric_cell_areas', 'get_oriented_triangle_areas',
           'get_triangle_normals', 'get_vertex_normals', 'get_dihedral_angles', 'get_volume', 'get_area',
           'get_voronoi_face_positions', 'set_voronoi_face_positions', 'get_dual_he_length',
           'get_oriented_dual_he_length', 'get_corner_angles', 'get_angle_sum', 'get_cotan_weights_per_he',
           'get_cotan_weights_per_egde', 'get_voronoi_edge_lengths', 'get_voronoi_edge_areas',
           'get_cell_areas_traversal', 'get_voronoi_areas', 'get_mean_curvature_dihedral', 'get_corner_scaled_angles',
           'get_face_tangent_basis', 'get_vertex_tangent_basis', 'get_transport_across_halfedge',
           'get_transport_along_halfedge']

# %% ../nbs/src/05_geometric_quantities.ipynb #d159edd4-4456-41f8-b520-8b1b69219c67
import numpy as np

# %% ../nbs/src/05_geometric_quantities.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp

import dataclasses

# %% ../nbs/src/05_geometric_quantities.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Float 

# %% ../nbs/src/05_geometric_quantities.ipynb #cef3ff0a
from . import trigonometry as trig
from . import mesh as msh
from . import adjacency as adj

# %% ../nbs/src/05_geometric_quantities.ipynb #cf6fcd73
def get_he_length(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                  ) -> Float[jax.Array, " n_hes"]:
    """Get lengths of half-edges (triangulation/primal edges)."""
    return jnp.linalg.norm(vertices[hemesh.orig]-vertices[hemesh.dest], axis=-1)


# %% ../nbs/src/05_geometric_quantities.ipynb #5c5b1e2a
## triangle areas and normals

def get_triangle_areas(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                       ) ->Float[jax.Array, "n_faces ..."]:
    """Compute triangle areas in a mesh."""
    return jax.vmap(trig.get_triangle_area)(*vertices[hemesh.faces.T])

def get_barycentric_cell_areas(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                              ) -> Float[jax.Array, " n_vertices"]:
    """Get area of barycentric dual cell around each vertex. Defined as 1/3 * sum of adjacent triangle areas."""
    return adj.sum_face_to_vertex(hemesh, get_triangle_areas(vertices, hemesh)) / 3.0

def get_oriented_triangle_areas(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                                ) ->Float[jax.Array, "n_faces ..."]:
    """Compute oriented triangle areas in a mesh. In 3d, this is a vector."""
    return jax.vmap(trig.get_oriented_triangle_area)(*vertices[hemesh.faces.T])

def get_triangle_normals(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                         ) ->Float[jax.Array, "n_faces ..."]:
    """Compute normals. In 2d, this just returns +/-1."""
    oriented_areas = get_oriented_triangle_areas(vertices, hemesh)
    norm = jnp.clip(jnp.linalg.norm(oriented_areas, axis=-1), 1e-12)
    return (oriented_areas.T / norm).T

def get_vertex_normals(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                       ) ->Float[jax.Array, "n_faces ..."]:
    """Compute per-vertex normals by averaging over faces"""
    oriented_areas = get_oriented_triangle_areas(vertices, hemesh)
    oriented_areas_vertex = adj.sum_face_to_vertex(hemesh, oriented_areas)
    norm = jnp.clip(jnp.linalg.norm(oriented_areas_vertex, axis=-1), 1e-12)
    return (oriented_areas_vertex.T / norm).T

def get_dihedral_angles(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                       ) ->Float[jax.Array, "n_hes ..."]:
    """Get dihedral angles (angle between adjacent face normals)."""
    oriented_areas = get_oriented_triangle_areas(vertices, hemesh)
    dihedral = jax.vmap(trig.get_angle_between_vectors)(oriented_areas[hemesh.heface],
                                                        oriented_areas[hemesh.heface[hemesh.twin]])
    return dihedral

# %% ../nbs/src/05_geometric_quantities.ipynb #cbaf37c7
def get_volume(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
              ) -> Float[jax.Array, ""]:
    """Signed volume of a closed triangulated surface (sums tetrahedra volumes relative to the origin)."""
    v0, v1, v2 = vertices[hemesh.faces.T]
    return trig.get_tetrahedron_volume(v0, v1, v2).sum()

def get_area(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
            ) -> Float[jax.Array, ""]:
    """Total surface area."""
    return get_triangle_areas(vertices, hemesh).sum()

# %% ../nbs/src/05_geometric_quantities.ipynb #b30791e6
def get_voronoi_face_positions(vertices: Float[jax.Array, "n_vertices 2"], hemesh: msh.HeMesh
                               ) -> Float[jax.Array, "n_faces 2"]:
    """Get face positions of geommesh to the circumcenters of the faces defined by hemesh."""
    face_positions = jax.vmap(trig.get_circumcenter)(*vertices[hemesh.faces].transpose((1,0,2)))
    return face_positions

def set_voronoi_face_positions(geommesh: msh.GeomMesh, hemesh: msh.HeMesh
                               ) -> msh.GeomMesh:
    """Set face positions of geommesh to the circumcenters of the faces defined by hemesh."""
    face_positions = get_voronoi_face_positions(geommesh.vertices, hemesh)
    return dataclasses.replace(geommesh, face_positions=face_positions)

# %% ../nbs/src/05_geometric_quantities.ipynb #d0391799
## Note: these quantities are currently accurate in 2D only (i.e. for planar dual cells)
## On the other hand, the dual vertex positions can be arbitrary - they don't have to be circumcenters (Voronoi).

def get_dual_he_length(face_positions: Float[jax.Array, "n_faces dim"], hemesh: msh.HeMesh
                       ) -> Float[jax.Array, " n_hes"]:
    """Get lengths of dual/cell half-edges."""
    dual_edges = face_positions[hemesh.heface]-face_positions[hemesh.heface[hemesh.twin]]
    return jnp.linalg.norm(dual_edges, axis=-1)

def get_oriented_dual_he_length(vertices: Float[jax.Array, "n_vertices 2"],
                                face_positions: Float[jax.Array, "n_faces 2"],
                                hemesh: msh.HeMesh) -> Float[jax.Array, " n_hes"]:
    """Compute lengths of dual edges. Boundary dual edges get length 1. Negative sign = flipped edge."""
    dual_edges = face_positions[hemesh.heface]-face_positions[hemesh.heface[hemesh.twin]]

    edges = vertices[hemesh.orig]-vertices[hemesh.dest]
    edges_normalized = (edges.T / jnp.linalg.norm(edges, axis=-1)).T
    signed_dual_length = jnp.einsum('vi,vi->v', edges_normalized, dual_edges @ trig.get_rot_mat(np.pi/2))
    signed_dual_length = jnp.where(hemesh.is_bdry_edge, 1, signed_dual_length)
    return signed_dual_length

# %% ../nbs/src/05_geometric_quantities.ipynb #96c8a576
def get_corner_angles(vertices: Float[jax.Array, "n_vertices dim"],hemesh: msh.HeMesh
                      ) -> Float[jax.Array, " n_hes"]:
    """Get angles in mesh corners (opposite to half-edges)."""
    b, c = vertices[hemesh.orig], vertices[hemesh.dest]
    a = vertices[hemesh.dest[hemesh.nxt]]
    return jax.vmap(trig.get_angle_between_vectors)(b-a, c-a)


def get_angle_sum(vertices: Float[jax.Array, "n_vertices dim"],hemesh: msh.HeMesh
                  ) -> Float[jax.Array, " n_vertices"]:
    """Angle sum around vertices. 2*pi-angle sum measures Gaussian curvature"""
    angles = get_corner_angles(vertices, hemesh)
    return adj.sum_he_to_vertex_opposite(hemesh, angles)


def get_cotan_weights_per_he(vertices: Float[jax.Array, "n_vertices dim"],
                             hemesh: msh.HeMesh) -> Float[jax.Array, " n_hes"]:
    """Cotangent of angle opposite to half-edge """
    b, c = vertices[hemesh.orig], vertices[hemesh.dest]
    a = vertices[hemesh.dest[hemesh.nxt]]
    return jax.vmap(trig.get_cot_between_vectors)(b-a, c-a)


def get_cotan_weights_per_egde(vertices: Float[jax.Array, "n_vertices dim"],
                               hemesh: msh.HeMesh) -> Float[jax.Array, " n_hes"]:
    """Average of cotangent of angles opposite to edge."""
    per_he = get_cotan_weights_per_he(vertices, hemesh)
    per_he = jnp.where(hemesh.is_bdry_he, 0.0, per_he)
    return (per_he + per_he[hemesh.twin])/2


def get_voronoi_edge_lengths(vertices: Float[jax.Array, "n_vertices dim"],
                             hemesh: msh.HeMesh) -> Float[jax.Array, " n_hes"]:
    """Computed directly from angles. Accurate in any dimension"""
    return get_cotan_weights_per_egde(vertices, hemesh) * get_he_length(vertices, hemesh)


def get_voronoi_edge_areas(vertices: Float[jax.Array, "n_vertices dim"],
                           hemesh: msh.HeMesh) -> Float[jax.Array, " n_hes"]:
    """Voronoi "area" for an edge. Defined as dual edge length * primal edge length ** 2 / 4.
    Summing over all edge areas adjacent to a vertex gives the area of the Voronoi cell around that vertex.
    Computed directly from angles. Accurate in any dimension"""
    return get_cotan_weights_per_egde(vertices, hemesh) * get_he_length(vertices, hemesh)**2 / 4



# %% ../nbs/src/05_geometric_quantities.ipynb #fbebd977-9ea6-4ab9-8188-d833f1bbba60
def get_cell_areas_traversal(geommesh: msh.GeomMesh, hemesh: msh.HeMesh) -> Float[jax.Array, " n_vertices"]:
    """
    Compute areas of cells by mesh traversal (don't use for simulation, inefficient).

    Boundary vertices get area 0.
    """
    areas = np.zeros(hemesh.n_vertices)
    bdry = hemesh.is_bdry
    for v in range(hemesh.n_vertices):
        if bdry[v]:
            areas[v] = 0
        else:
            adjacent_faces = hemesh.heface[hemesh.iterate_around_vertex(v)]
            polygon = geommesh.face_positions[adjacent_faces]
            areas[v] = trig.get_polygon_area(polygon)
    return -jnp.array(areas)


def get_voronoi_areas(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                      ) ->Float[jax.Array, " n_vertices"]:
    """Compute Voronoi area for each vertex."""
    edge_areas = get_voronoi_edge_areas(vertices, hemesh)
    return adj.sum_he_to_vertex_incoming(hemesh, edge_areas)

# %% ../nbs/src/05_geometric_quantities.ipynb #a840388a
def get_mean_curvature_dihedral(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                                ) ->Float[jax.Array, " n_vertices"]:

    """Compute mean curvature of triangulated mesh using Steiner approximation:
        H_i = 1/(4 A_i) * sum_j * theta_ij * l_ij
    where theta_ij is the dihedral angle between faces adjacent to edge ij, l_ij is the length of edge ij,
    and A_i is the barycentric dual cell area around vertex i.
    """
    dihedral_angles = get_dihedral_angles(vertices, hemesh)
    edge_lengths = get_he_length(vertices, hemesh)
    cell_areas = get_barycentric_cell_areas(vertices, hemesh)
    return  1/4 * adj.sum_he_to_vertex_incoming(hemesh, dihedral_angles*edge_lengths) / cell_areas

# %% ../nbs/src/05_geometric_quantities.ipynb #e27886c1
def get_corner_scaled_angles(vertices: Float[jax.Array, "n_vertices dim"],
                             hemesh: msh.HeMesh
                             ) -> Float[jax.Array, " n_hes"]:
    """Corner angles rescaled so they sum to 2π at interior vertices and π at boundary vertices.

    Uses the same indexing convention as `get_corner_angles`: scaled_angles[he] is the
    rescaled angle at vertex dest[nxt[he]] (the vertex opposite halfedge he).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_hes"]
        Rescaled corner angles per halfedge.
    """
    angles = get_corner_angles(vertices, hemesh)
    angle_sums = adj.sum_he_to_vertex_opposite(hemesh, angles)
    # scale factor: 2π/sum at interior, π/sum at boundary
    target = jnp.where(hemesh.is_bdry, jnp.pi, 2 * jnp.pi)
    scale = target / jnp.clip(angle_sums, 1e-10)
    # corner_angles[he] is the angle at vertex dest[nxt[he]]
    vertex_of_corner = hemesh.dest[hemesh.nxt]
    return angles * scale[vertex_of_corner]

# %% ../nbs/src/05_geometric_quantities.ipynb #38cd5b95
def get_face_tangent_basis(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                           ) -> Float[jax.Array, "n_faces 2 dim"]:
    """Orthonormal tangent basis (basisX, basisY) in 3D world coordinates per face.

    Convention: basisX is aligned with the face's incident halfedge projected onto
    the face tangent plane. basisY = cross(face_normal, basisX).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions in 3D.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_faces 2 3"]
        Per-face tangent basis: result[f, 0] = basisX, result[f, 1] = basisY.
    """
    normals = get_triangle_normals(vertices, hemesh)
    # edge vector of face incident halfedge
    edge_vecs = vertices[hemesh.dest[hemesh.face_incident]] - vertices[hemesh.orig[hemesh.face_incident]]
    # project onto tangent plane and normalize
    basis_X = jax.vmap(trig.project_out_vector)(edge_vecs, normals)
    basis_X = basis_X / jnp.clip(jnp.linalg.norm(basis_X, axis=-1, keepdims=True), 1e-10)
    basis_Y = jnp.cross(basis_X, normals)
    return jnp.stack([basis_X, basis_Y], axis=1)

# %% ../nbs/src/05_geometric_quantities.ipynb #0934d60c
def get_vertex_tangent_basis(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                             ) -> Float[jax.Array, "n_vertices 2 dim"]:
    """Orthonormal tangent basis (basisX, basisY) in 3D world coordinates per vertex.

    Convention: basisX is aligned with the vertex' incident halfedge projected onto
    the vertex tangent plane. basisY = cross(vertex_normal, basisX).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 3"]
        Vertex positions in 3D.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_vertices 2 3"]
        Per-vertex tangent basis: result[v, 0] = basisX, result[v, 1] = basisY.
    """
    normals = get_vertex_normals(vertices, hemesh)
    edge_vecs = vertices[hemesh.dest[hemesh.incident]] - vertices[hemesh.orig[hemesh.incident]]
    basis_X = jax.vmap(trig.project_out_vector)(edge_vecs, normals)
    basis_X = basis_X / jnp.clip(jnp.linalg.norm(basis_X, axis=-1, keepdims=True), 1e-10)
    basis_Y = jnp.cross(basis_X, normals)
    return jnp.stack([basis_X, basis_Y], axis=1)

# %% ../nbs/src/05_geometric_quantities.ipynb #3d2e6fa4
def get_transport_across_halfedge(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                                  ) -> Float[jax.Array, " n_hes"]:
    """Rotation angle to transport a tangent vector from one face to the adjacent face across a halfedge.

    Applying this rotation to a vector in the frame of heface[he] gives the same vector
    in the frame of heface[twin[he]]. For boundary half edges, this is set to 0
    (no transport since there's only one face).

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_hes"]
        Transport angle per halfedge (radians). NaN for boundary halfedges.
    """
    # get vector of shared half edge in 3d world coordinates
    edge_vec = vertices[hemesh.orig] - vertices[hemesh.dest]
    # get tangent basis
    face_basis = get_face_tangent_basis(vertices, hemesh)
    # project edge vector onto face and twin bases
    edge_vec_face = jnp.einsum('vix, vx -> vi', face_basis[hemesh.heface], edge_vec)
    edge_vec_face_twin = jnp.einsum('vix, vx -> vi', face_basis[hemesh.heface[hemesh.twin]], edge_vec)
    # get angle between the two
    transport_angle = jax.vmap(trig.get_angle_between_vectors)(edge_vec_face, -edge_vec_face_twin)
    # mask boundary halfedges
    transport_angle = jnp.where(hemesh.is_bdry_edge, 0, transport_angle)
    return transport_angle

# %% ../nbs/src/05_geometric_quantities.ipynb #c3e7ad42
def get_transport_along_halfedge(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                                 ) -> Float[jax.Array, " n_hes"]:
    """Rotation angle to transport a tangent vector from one vertex to the next vertex along a halfedge.

    Applying this rotation to a vector in the frame of a vertex gives the same vector
    in the frame of the next vertex along the halfedge

    Parameters
    ----------
    vertices : Float[Array, "n_vertices dim"]
        Vertex positions.
    hemesh : HeMesh
        Half-edge mesh.

    Returns
    -------
    Float[Array, "n_hes"]
        Transport angle per halfedge (radians). NaN for boundary halfedges.
    """
    # get vector of shared half edge in 3d world coordinates
    edge_vec = vertices[hemesh.orig] - vertices[hemesh.dest]
    # get tangent basis
    vertex_basis = get_vertex_tangent_basis(vertices, hemesh)
    # project edge vector onto vertex bases
    edge_vec_vertex = jnp.einsum('vix, vx -> vi', vertex_basis[hemesh.orig], edge_vec)
    edge_vec_vertex_next = jnp.einsum('vix, vx -> vi', vertex_basis[hemesh.dest], edge_vec)
    # get angle between the two
    transport_angle = jax.vmap(trig.get_angle_between_vectors)(edge_vec_vertex, -edge_vec_vertex_next)
    # mask boundary halfedges
    transport_angle = jnp.where(hemesh.is_bdry_edge, 0, transport_angle)
    return transport_angle
