# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/07_interpolation.ipynb.

# %% auto #0
__all__ = ['get_closest_point_on_segment', 'get_closest_point_on_triangle', 'find_closest_faces', 'interpolate_barycentric']

# %% ../nbs/src/07_interpolation.ipynb #f8d8a985
import jax
import jax.numpy as jnp


# %% ../nbs/src/07_interpolation.ipynb #15d87ae0
from jaxtyping import Bool, Float, Int

# %% ../nbs/src/07_interpolation.ipynb #ebc2fa3b
from . import trigonometry as trig


# %% ../nbs/src/07_interpolation.ipynb #closest-triangle-helpers
def get_closest_point_on_segment(point: Float[jax.Array, " dim"],
                                 a: Float[jax.Array, " dim"],
                                 b: Float[jax.Array, " dim"]) -> Float[jax.Array, " dim"]:
    """Closest point on a line segment.

    Parameters
    ----------
    point : Float[Array, "dim"]
        Query point.
    a, b : Float[Array, "dim"]
        Segment endpoints.

    Returns
    -------
    Float[Array, "dim"]
        Closest point on the segment from a to b.
    """
    ab = b - a
    t = jnp.dot(point - a, ab) / jnp.clip(jnp.dot(ab, ab), 1e-12)
    return a + jnp.clip(t, 0.0, 1.0) * ab


def get_closest_point_on_triangle(point: Float[jax.Array, " dim"],
                                  a: Float[jax.Array, " dim"],
                                  b: Float[jax.Array, " dim"],
                                  c: Float[jax.Array, " dim"]) -> Float[jax.Array, " dim"]:
    """Closest point on triangle abc to a query point.

    For non-degenerate triangles this first projects onto the triangle plane,
    then clamps to the triangle if the projection lies outside. Degenerate
    triangles fall back to the closest point on the three edges.

    Parameters
    ----------
    point : Float[Array, "dim"]
        Query point.
    a, b, c : Float[Array, "dim"]
        Triangle vertex positions.

    Returns
    -------
    Float[Array, "dim"]
        Closest point on the triangle.
    """
    normal = jnp.cross(b - a, c - a)
    if point.shape[-1] > 2:
        projected_point = a + trig.project_out_vector(point - a, normal)
    else:
        projected_point = point
    barycentric = trig.get_barycentric_coordinates(projected_point, a, b, c)
    edge_points = jnp.stack([get_closest_point_on_segment(projected_point, a, b),
                             get_closest_point_on_segment(projected_point, b, c),
                             get_closest_point_on_segment(projected_point, c, a)])
    edge_distances = jnp.sum((edge_points - projected_point) ** 2, axis=-1)
    closest_edge_point = edge_points[jnp.argmin(edge_distances)]
    is_degenerate = trig.get_triangle_area(a, b, c) <= 1e-12
    is_inside = jnp.all(barycentric >= -1e-12)
    return jnp.where(jnp.logical_and(is_inside, jnp.logical_not(is_degenerate)),
                     projected_point,
                     closest_edge_point)

# %% ../nbs/src/07_interpolation.ipynb #3a84d9ba
def _point_triangle_squared_distance(point: Float[jax.Array, " 3"],
                                     corners: Float[jax.Array, "3 3"],
                                     edges: Float[jax.Array, "3 3"],
                                     normal: Float[jax.Array, " 3"],
                                     nondegenerate: Bool[jax.Array, ""]) -> Float[jax.Array, ""]:
    """Squared distance from a point to a triangle with precomputed edges and normal.

    If the projection of the point onto the triangle plane falls inside the
    triangle, this is the squared distance to the plane; otherwise, the squared
    distance to the closest edge. Degenerate triangles fall back to edge
    distances. Cheaper than computing the closest point itself.

    Parameters
    ----------
    point : Float[Array, "3"]
        Query point.
    corners : Float[Array, "3 3"]
        Triangle vertex positions a, b, c.
    edges : Float[Array, "3 3"]
        Precomputed edge vectors b-a, c-b, a-c.
    normal : Float[Array, "3"]
        Precomputed unit normal.
    nondegenerate : Bool[Array, ""]
        Whether the triangle has non-zero area.

    Returns
    -------
    Float[Array, ""]
        Squared distance from the point to the triangle.
    """
    a, b, c = corners
    ab, bc, ca = edges
    # jnp.sum(x * y) instead of jnp.dot: batched dot_general is ~8x slower under nested vmap
    plane_distance = jnp.sum((point - a) * normal) ** 2
    is_inside = ((jnp.sum(jnp.cross(ab, point - a) * normal) >= 0)
                 & (jnp.sum(jnp.cross(bc, point - b) * normal) >= 0)
                 & (jnp.sum(jnp.cross(ca, point - c) * normal) >= 0))

    def segment_distance(origin: Float[jax.Array, " 3"], edge: Float[jax.Array, " 3"]
                         ) -> Float[jax.Array, ""]:
        t = jnp.sum((point - origin) * edge) / jnp.clip(jnp.sum(edge ** 2), 1e-12)
        return jnp.sum((point - origin - jnp.clip(t, 0.0, 1.0) * edge) ** 2)

    edge_distance = jnp.minimum(segment_distance(a, ab),
                                jnp.minimum(segment_distance(b, bc), segment_distance(c, ca)))
    return jnp.where(is_inside & nondegenerate, plane_distance, edge_distance)


def find_closest_faces(points: Float[jax.Array, "n_points dim"],
                       vertices: Float[jax.Array, "n_vertices dim"],
                       faces: Int[jax.Array, "n_faces 3"]
                       ) -> tuple[Int[jax.Array, " n_points"], Float[jax.Array, "n_points dim"]]:
    """Find the closest triangle and closest point on the mesh for each query point.

    Brute-force O(n_points * n_faces) search: cheap point-triangle squared
    distances (using per-mesh precomputed edge vectors and unit normals) select
    the closest face, then the exact closest point is computed on that face
    only. 2D meshes are zero-padded to 3D for the search. Compatible with
    jax.jit and automatic differentiation.

    Parameters
    ----------
    points : Float[Array, "n_points dim"]
        Query points (dim = 2 or 3).
    vertices : Float[Array, "n_vertices dim"]
        Mesh vertices.
    faces : Int[Array, "n_faces 3"]
        Triangle indices into vertices.

    Returns
    -------
    tuple[Int[Array, "n_points"], Float[Array, "n_points dim"]]
        Closest face index and closest point on that face for each query point.
    """
    pad_width = ((0, 0), (0, 3 - points.shape[-1]))
    triangles = jnp.pad(vertices, pad_width)[faces]
    edges = jnp.roll(triangles, shift=-1, axis=1) - triangles
    normals = jnp.cross(edges[:, 0], -edges[:, 2])
    double_areas = jnp.linalg.norm(normals, axis=-1, keepdims=True)
    normals = normals / jnp.clip(double_areas, 1e-12)
    nondegenerate = double_areas[:, 0] > 1e-12

    squared_distances = jax.vmap(_point_triangle_squared_distance,
                                 in_axes=(None, 0, 0, 0, 0))
    face_indices = jax.vmap(lambda point: jnp.argmin(squared_distances(point, triangles, edges,
                                                                       normals, nondegenerate))
                            )(jnp.pad(points, pad_width))
    closest_points = jax.vmap(lambda point, triangle: get_closest_point_on_triangle(point, *triangle)
                              )(points, vertices[faces[face_indices]])
    return face_indices, closest_points

# %% ../nbs/src/07_interpolation.ipynb #barycentric-interpolation
def interpolate_barycentric(points: Float[jax.Array, "n_points dim"],
                            vertices: Float[jax.Array, "n_vertices dim"],
                            faces: Int[jax.Array, "n_faces 3"],
                            values: Float[jax.Array, "n_vertices ..."],
                            distance_threshold: float = jnp.inf
                            ) -> Float[jax.Array, "n_points ..."]:
    """Interpolate vertex data onto query points using barycentric coordinates.

    Each query point is first mapped to its closest triangle on the mesh via
    find_closest_faces, then the barycentric coordinates of the closest point
    are used to linearly blend the values at that triangle's vertices. Query
    points off the mesh (e.g. away from the surface in 3D) are assigned the
    value at the closest mesh point.

    Parameters
    ----------
    points : Float[Array, "n_points dim"]
        Query points.
    vertices : Float[Array, "n_vertices dim"]
        Mesh vertices in 2D or 3D.
    faces : Int[Array, "n_faces 3"]
        Mesh triangles, indexing vertices.
    values : Float[Array, "n_vertices ..."]
        Values defined at mesh vertices. Additional trailing axes are preserved.
    distance_threshold : float, default=jnp.inf
        Squared-distance threshold. Points farther from the mesh than this are
        masked with NaN in the returned array.

    Returns
    -------
    Float[Array, "n_points ..."]
        Interpolated values at the query points.
    """
    face_indices, closest_points = find_closest_faces(points, vertices, faces)
    hit_triangles = vertices[faces[face_indices]]
    barycentric = jax.vmap(trig.get_barycentric_coordinates)(closest_points,
                                                             hit_triangles[:, 0],
                                                             hit_triangles[:, 1],
                                                             hit_triangles[:, 2])
    interpolated = jnp.einsum('pi,pi...->p...', barycentric, values[faces[face_indices]])

    squared_distances = jnp.sum((closest_points - points) ** 2, axis=-1)
    invalid = squared_distances > distance_threshold
    invalid = invalid.reshape(invalid.shape + (1,) * (interpolated.ndim - 1))
    return jnp.where(invalid, jnp.nan, interpolated)
