# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/06_linear_operators.ipynb.

# %% auto #0
__all__ = ['scipy_to_bcoo', 'bcoo_to_scipy', 'diag_jsparse', 'compute_cotan_laplace_intrinsic', 'compute_cotan_laplace',
           'cotan_laplace_sparse_intrinsic', 'cotan_laplace_sparse', 'mass_matrix_sparse_intrinsic',
           'mass_matrix_inv_sparse_intrinsic', 'mass_matrix_sparse', 'mass_matrix_inv_sparse', 'compute_gradient_2d',
           'compute_gradient_3d', 'gradient_sparse_2d', 'gradient_sparse_3d', 'reshape_face_gradient',
           'compute_divergence_2d', 'compute_divergence_3d', 'compute_normal_derivative_intrinsic',
           'normal_derivative_sparse_intrinsic', 'compute_normal_derivative', 'normal_derivative_sparse',
           'linear_op_to_sparse']

# %% ../nbs/src/06_linear_operators.ipynb #d159edd4-4456-41f8-b520-8b1b69219c67
import numpy as np
from scipy import sparse

# %% ../nbs/src/06_linear_operators.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp
import jax.experimental.sparse as jsparse

# %% ../nbs/src/06_linear_operators.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Float 

# %% ../nbs/src/06_linear_operators.ipynb #cef3ff0a
from collections.abc import Callable

from . import trigonometry as trig
from . import mesh as msh
from . import adjacency as adj
from . import geometry as geom

# %% ../nbs/src/06_linear_operators.ipynb #4cc0c0fb
def scipy_to_bcoo(A) -> jsparse.BCOO:
    """
    Convert a SciPy sparse matrix (CSC or CSR) to a JAX BCOO sparse matrix
    without converting to dense.

    Parameters
    ----------
    A : scipy.sparse.spmatrix
        Input sparse matrix (CSR or CSC recommended)

    Returns
    -------
    B : jax.experimental.sparse.BCOO
        Equivalent JAX sparse matrix
    """
    # Convert to COO
    Acoo = A.tocoo()

    # COO format gives us row, col, data arrays directly
    rows = jnp.array(Acoo.row, dtype=jnp.int32)
    cols = jnp.array(Acoo.col, dtype=jnp.int32)
    data = jnp.array(Acoo.data)
    return jsparse.BCOO((data, jnp.stack([rows, cols], axis=1)), shape=Acoo.shape)


def bcoo_to_scipy(A: jsparse.BCOO) -> sparse.csr_matrix:
    """
    Convert a JAX BCOO sparse matrix to a SciPy CSR sparse matrix.

    Parameters
    ----------
    A : jax.experimental.sparse.BCOO
        Input JAX sparse matrix

    Returns
    -------
    B : scipy.sparse.csr_matrix
        Equivalent SciPy sparse matrix
    """
    data, indices = A.data, A.indices
    rows = np.array(indices[:, 0])
    cols = np.array(indices[:, 1])
    data = np.array(data)
    return sparse.csr_matrix((data, (rows, cols)), shape=A.shape)


def diag_jsparse(v : Float[jax.Array, " N"], k: int =0) -> jsparse.BCOO:
    """Construct a diagonal jax.sparse array. Plugin replacement for np.diag"""
    N  = v.shape[0] + abs(k)  # plain abs: jnp.abs would make N a tracer and break jit
    if k >=0:
        row_inds = jnp.arange(k, N, dtype=jnp.int32)
    else:
        row_inds = jnp.arange(0, N+k, dtype=jnp.int32)
    return jsparse.BCOO((v, jnp.stack([row_inds-k, row_inds,], axis=1)), shape=(N, N))

# %% ../nbs/src/06_linear_operators.ipynb #66b2e04f
def compute_cotan_laplace_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh,
                                    vertex_field: Float[jax.Array, "n_vertices ..."],
                                    normalize: bool = False,
                                    ) -> Float[jax.Array, "n_vertices ..."]:
    """Compute the cotangent Laplacian of a per-vertex field from edge lengths (natural boundary conditions).

    Parameters
    ----------
    he_lengths
        Edge length per half-edge, e.g. from `geometry.get_he_length` or, under periodic
        boundary conditions, `periodic.get_periodic_he_lengths`.
    hemesh
        Half-edge mesh connectivity.
    vertex_field
        Per-vertex scalar, vector, or tensor field.
    normalize
        If True, return the area-normalized Laplace-Beltrami operator $M^{-1} L u$,
        dividing by the robust Voronoi cell area at each vertex.

    Returns
    -------
    result
        Cotangent Laplacian applied to the field, same shape as ``vertex_field``.
    """
    w_edge = geom.get_cotan_weights_per_edge_intrinsic(he_lengths, hemesh)
    diff = vertex_field[hemesh.dest] - vertex_field[hemesh.orig]
    result = -adj.sum_he_to_vertex_incoming(hemesh, (w_edge*diff.T).T)
    if normalize:
        areas = geom.get_voronoi_areas_robust_intrinsic(he_lengths, hemesh)
        result = result / jnp.expand_dims(areas, jnp.arange(1, result.ndim)) # for broadcasting
    return result


def compute_cotan_laplace(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                          vertex_field: Float[jax.Array, "n_vertices ..."],
                          normalize: bool = False,
                          ) -> Float[jax.Array, "n_vertices ..."]:
    """Compute cotangent Laplacian of a per-vertex field (natural boundary conditions).

    Position-based form of `compute_cotan_laplace_intrinsic`; see there for the parameters.
    """
    return compute_cotan_laplace_intrinsic(geom.get_he_length(vertices, hemesh), hemesh,
                                           vertex_field, normalize=normalize,)

# %% ../nbs/src/06_linear_operators.ipynb #b9c6f5cc
def cotan_laplace_sparse_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh
                                   ) -> jsparse.BCOO:
    """Assemble the cotangent Laplacian from edge lengths as a sparse matrix (BCOO).

    Same sign convention as `compute_cotan_laplace_intrinsic`, so
    ``cotan_laplace_sparse_intrinsic(l, h) @ u == compute_cotan_laplace_intrinsic(l, h, u)``.
    """
    w_edge = geom.get_cotan_weights_per_edge_intrinsic(he_lengths, hemesh)
    unique = hemesh.is_unique

    i = hemesh.orig[unique]
    j = hemesh.dest[unique]
    w = w_edge[unique]

    rows = jnp.concatenate([i, j, i, j])
    cols = jnp.concatenate([j, i, i, j])
    data = jnp.concatenate([w, w, -w, -w])

    mat = jsparse.BCOO((data, jnp.stack([rows, cols], axis=1)),
                       shape=(hemesh.n_vertices, hemesh.n_vertices))
    return mat.sum_duplicates()


def cotan_laplace_sparse(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                         ) -> jsparse.BCOO:
    """Assemble cotangent Laplacian as a sparse matrix (BCOO)."""
    return cotan_laplace_sparse_intrinsic(geom.get_he_length(vertices, hemesh), hemesh)

# %% ../nbs/src/06_linear_operators.ipynb #c45f21b2
def mass_matrix_sparse_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh,
                                 area_type: str = "voronoi") -> jsparse.BCOO:
    """Assemble the lumped (diagonal) mass matrix from edge lengths as a sparse matrix (BCOO).

    The lumped mass matrix is diagonal with entries equal to the dual
    area of each vertex: $M_{ii} = A_i$.

    Parameters
    ----------
    he_lengths : Float[Array, "n_hes"]
        Edge length per half-edge, e.g. from `geometry.get_he_length` or, under periodic
        boundary conditions, `periodic.get_periodic_he_lengths`.
    hemesh : HeMesh
        Half-edge mesh connectivity.
    area_type : {"voronoi", "voronoi_exact", "barycentric"}, default="voronoi"
        Choice of dual-cell area definition used on the diagonal.
        ``"voronoi"`` is the *mixed* Voronoi area of Meyer et al., which is what
        ``igl.massmatrix(..., MASSMATRIX_TYPE_VORONOI)`` computes and is always
        positive; this is the right choice for the cotangent Laplacian.
        ``"voronoi_exact"`` is the exact (signed) circumcentric area, which can be
        NEGATIVE on obtuse triangles and then destroys positive-definiteness of
        ``M - dt*L``. ``"barycentric"`` is a simpler always-positive approximation.

    Returns
    -------
    M : BCOO, shape (n_vertices, n_vertices)
        Diagonal sparse mass matrix.
    """
    if area_type == "voronoi":
        cell_areas = geom.get_voronoi_areas_robust_intrinsic(he_lengths, hemesh)
    elif area_type == "voronoi_exact":
        cell_areas = geom.get_voronoi_areas_intrinsic(he_lengths, hemesh)
    elif area_type == "barycentric":
        cell_areas = geom.get_barycentric_cell_areas_intrinsic(he_lengths, hemesh)
    else:
        raise ValueError(f"unknown area_type {area_type!r}; "
                         "expected 'voronoi', 'voronoi_exact' or 'barycentric'")
    return diag_jsparse(cell_areas)


def mass_matrix_inv_sparse_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh,
                                     area_type: str = "voronoi") -> jsparse.BCOO:
    """Inverse of `mass_matrix_sparse_intrinsic`. See there for the area conventions.

    Note only ``"voronoi"`` (mixed) areas are guaranteed positive; the other choices can
    produce zero or negative areas, and hence a divergent inverse.
    """
    mass = mass_matrix_sparse_intrinsic(he_lengths, hemesh, area_type=area_type)
    return diag_jsparse(1.0 / mass.data)


def mass_matrix_sparse(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                       area_type: str = "voronoi") -> jsparse.BCOO:
    """Assemble lumped (diagonal) mass matrix as a sparse matrix (BCOO).

    Position-based form of `mass_matrix_sparse_intrinsic`; see there for the parameters
    and the meaning of ``area_type``.
    """
    return mass_matrix_sparse_intrinsic(geom.get_he_length(vertices, hemesh), hemesh,
                                        area_type=area_type)


def mass_matrix_inv_sparse(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                           area_type: str = "voronoi") -> jsparse.BCOO:
    """Assemble the inverse lumped mass matrix as a sparse matrix (BCOO).

    Position-based form of `mass_matrix_inv_sparse_intrinsic`.
    """
    return mass_matrix_inv_sparse_intrinsic(geom.get_he_length(vertices, hemesh), hemesh,
                                            area_type=area_type)

# %% ../nbs/src/06_linear_operators.ipynb #e2587568
def _fe_grad_phi_2d(vertices: Float[jax.Array, "n_vertices 2"], hemesh: msh.HeMesh,
                 ) -> Float[jax.Array, "n_faces 3 2"]:
    """Per-face gradients of the P1 hat functions (2D).

    For each face f=(i,j,k), returns an array grads[f, l, :] = ∇φ_l, with l=0,1,2
    corresponding to vertices (i,j,k). Degenerate faces get zero gradients.
    """
    faces = hemesh.faces
    v0, v1, v2 = (vertices[faces[:, 0]], vertices[faces[:, 1]], vertices[faces[:, 2]])

    area2 = jnp.cross(v1 - v0, v2 - v0)[:, None]
    mask = area2 != 0
    # the denominator must be made safe *before* dividing: jnp.where masks the value
    # but the reverse-mode rule still differentiates the untaken x/0 branch -> NaN.
    safe_area2 = jnp.where(mask, area2, 1.0)
    grad_phi0 = jnp.where(mask, trig.get_perp_2d(v1 - v2)/safe_area2, 0)
    grad_phi1 = jnp.where(mask, trig.get_perp_2d(v2 - v0)/safe_area2, 0)
    grad_phi2 = jnp.where(mask, trig.get_perp_2d(v0 - v1)/safe_area2, 0)

    return jnp.stack([grad_phi0, grad_phi1, grad_phi2], axis=1)


def _fe_grad_phi_3d(vertices: Float[jax.Array, "n_vertices 3"], hemesh: msh.HeMesh,
                 ) -> Float[jax.Array, "n_faces 3 3"]:
    """Per-face gradients of the P1 hat functions (3D).

    For each face f=(i,j,k), returns grads[f, l, :] = ∇φ_l in R^3, l=0,1,2.
    Degenerate faces get zero gradients.
    """
    faces = hemesh.faces
    v0, v1, v2 = (vertices[faces[:, 0]], vertices[faces[:, 1]], vertices[faces[:, 2]])

    n = jnp.cross(v1 - v0, v2 - v0)
    norm_n_sq = jnp.sum(n**2, axis=-1, keepdims=True)  # avoids norm's NaN gradient at 0
    mask = norm_n_sq > 0
    # see _fe_grad_phi_2d: the denominator must be safe before the division
    safe_norm_n_sq = jnp.where(mask, norm_n_sq, 1.0)
    grad_phi0 = jnp.where(mask, jnp.cross(v1 - v2, n)/safe_norm_n_sq, 0)
    grad_phi1 = jnp.where(mask, jnp.cross(v2 - v0, n)/safe_norm_n_sq, 0)
    grad_phi2 = jnp.where(mask, jnp.cross(v0 - v1, n)/safe_norm_n_sq, 0)

    return jnp.stack([grad_phi0, grad_phi1, grad_phi2], axis=1)


def compute_gradient_2d(vertices: Float[jax.Array, "n_vertices 2"], hemesh: msh.HeMesh,
                        vertex_field: Float[jax.Array, "n_vertices ..."]
                        ) -> Float[jax.Array, "n_faces 2 ..."]:
    """Compute the linear finite-element gradient (constant per face)."""
    faces = hemesh.faces
    grads = _fe_grad_phi_2d(vertices, hemesh)
    vals = vertex_field[faces]
    return jnp.einsum("fvd,fv...->fd...", grads, vals)


def compute_gradient_3d(vertices: Float[jax.Array, "n_vertices 3"], hemesh: msh.HeMesh,
                        vertex_field: Float[jax.Array, "n_vertices ..."]
                        ) -> Float[jax.Array, "n_faces 3 ..."]:
    """Compute the linear finite-element gradient (constant per face)."""
    faces = hemesh.faces
    grads = _fe_grad_phi_3d(vertices, hemesh)
    vals = vertex_field[faces]
    return jnp.einsum("fvd,fv...->fd...", grads, vals)

# %% ../nbs/src/06_linear_operators.ipynb #ebdd9818
def gradient_sparse_2d(vertices: Float[jax.Array, "n_vertices 2"], hemesh: msh.HeMesh,
                      ) -> jsparse.BCOO:
    """Assemble FE gradient in 2D as a sparse matrix (BCOO).

    Returns a matrix G with shape (2*n_faces, n_vertices) such that for a scalar
    per-vertex field u (n_vertices,), the per-face gradients are obtained via:
        g_flat = G @ u                    # (2*n_faces,)
        g = g_flat.reshape((2, n_faces)).T  # (n_faces, 2)

    This row layout matches libigl's `grad` operator convention (component blocks).
    """
    faces = hemesh.faces.astype(jnp.int32)
    n_faces = faces.shape[0]
    n_vertices = hemesh.n_vertices

    grads = _fe_grad_phi_2d(vertices, hemesh)  # (n_faces, 3, 2)
    # order contributions as (component c, corner k, face f)
    data = jnp.transpose(grads, (2, 1, 0)).reshape((-1,))  # (2*3*n_faces,)
    cols_kf = faces.T.reshape((-1,))  # (3*n_faces,), order (k,f)
    cols = jnp.tile(cols_kf, (2,))
    rows_f = jnp.arange(n_faces, dtype=jnp.int32)
    rows_kf = jnp.tile(rows_f, (3,))  # (3*n_faces,), order (k,f)
    rows = jnp.tile(rows_kf, (2,)) + jnp.repeat(jnp.arange(2, dtype=jnp.int32) * n_faces, 3 * n_faces)

    indices = jnp.stack([rows, cols], axis=1)
    return jsparse.BCOO((data, indices), shape=(2 * n_faces, n_vertices))


def gradient_sparse_3d(vertices: Float[jax.Array, "n_vertices 3"], hemesh: msh.HeMesh,
                      ) -> jsparse.BCOO:
    """Assemble FE gradient in 3D as a sparse matrix (BCOO).

    Returns a matrix G with shape (3*n_faces, n_vertices) such that for a scalar
    per-vertex field u (n_vertices,), the per-face gradients are obtained via:
        g_flat = G @ u                    # (3*n_faces,)
        g = g_flat.reshape((3, n_faces)).T  # (n_faces, 3)

    This row layout matches libigl's `grad` operator convention (component blocks).
    """
    faces = hemesh.faces.astype(jnp.int32)
    n_faces = faces.shape[0]
    n_vertices = hemesh.n_vertices

    grads = _fe_grad_phi_3d(vertices, hemesh)  # (n_faces, 3, 3)
    data = jnp.transpose(grads, (2, 1, 0)).reshape((-1,))  # (3*3*n_faces,)
    cols_kf = faces.T.reshape((-1,))  # (3*n_faces,)
    cols = jnp.tile(cols_kf, (3,))
    rows_f = jnp.arange(n_faces, dtype=jnp.int32)
    rows_kf = jnp.tile(rows_f, (3,))
    rows = jnp.tile(rows_kf, (3,)) + jnp.repeat(jnp.arange(3, dtype=jnp.int32) * n_faces, 3 * n_faces)

    indices = jnp.stack([rows, cols], axis=1)
    return jsparse.BCOO((data, indices), shape=(3 * n_faces, n_vertices))

# %% ../nbs/src/06_linear_operators.ipynb #86653c6e
def reshape_face_gradient(grad_flat: Float[jax.Array, "dim_n_faces ..."], n_faces: int, dim: int,
                          ) -> Float[jax.Array, "n_faces dim ..."]:
    """Reshape a flattened FE gradient into per-face vectors.

    This is meant to be used with `gradient_sparse_2d/3d` (and any similar operator that
    stacks components in blocks), where applying the sparse matrix yields an array of shape
    `(dim*n_faces, ...)` (for scalar/vector/tensor per-vertex fields).

    Parameters
    ----------
    grad_flat
        Output of `G @ u`, with shape `(dim*n_faces, ...)`.
    n_faces
        Number of mesh faces.
    dim
        Spatial dimension (2 or 3).

    Returns
    -------
    grad
        Reshaped gradient with shape `(n_faces, dim, ...)`, matching the output convention
        of `compute_gradient_2d/3d`.
    """
    if grad_flat.shape[0] != dim * n_faces:
        raise ValueError(f"Expected grad_flat.shape[0] == dim*n_faces = {dim*n_faces}, got {grad_flat.shape[0]}")
    grad = jnp.reshape(grad_flat, (dim, n_faces) + grad_flat.shape[1:])
    return jnp.swapaxes(grad, 0, 1)

# %% ../nbs/src/06_linear_operators.ipynb #f7ff66ae
def compute_divergence_2d(vertices: Float[jax.Array, "n_vertices 2"], hemesh: msh.HeMesh,
                          face_field: Float[jax.Array, "n_faces 2 ..."]
                          ) -> Float[jax.Array, "n_vertices ..."]:
    """Compute the (integrated) FE divergence of a per-face vector field (2D).

    Maps a per-face vector field to a per-vertex scalar field. This is the
    negative adjoint of the FE gradient weighted by face areas.
    Satisfies ``compute_cotan_laplace(v, h, u) ≈ compute_divergence_2d(v, h, compute_gradient_2d(v, h, u))``.

    Parameters
    ----------
    vertices
        Vertex positions, shape (n_vertices, 2).
    hemesh
        Half-edge mesh connectivity.
    face_field
        Per-face vector (or tensor) field, shape (n_faces, 2, ...).

    Returns
    -------
    result
        Per-vertex field, shape (n_vertices, ...).
    """
    faces = hemesh.faces
    grads = _fe_grad_phi_2d(vertices, hemesh)                  # (n_faces, 3, 2)
    areas = geom.get_triangle_areas(vertices, hemesh)          # (n_faces,)

    # contract over spatial dim, weight by area → per-corner contributions
    # areas must broadcast against the trailing axes of a vector/tensor face field
    contrib = -jnp.einsum("fvd,fd...->fv...", grads, face_field)
    contrib = contrib * areas.reshape((-1,) + (1,) * (contrib.ndim - 1))

    # scatter-add per-corner contributions to vertices
    trailing = face_field.shape[2:]
    result = jnp.zeros((hemesh.n_vertices,) + trailing)
    for corner in range(3):
        result = result.at[faces[:, corner]].add(contrib[:, corner])
    return result


def compute_divergence_3d(vertices: Float[jax.Array, "n_vertices 3"], hemesh: msh.HeMesh,
                          face_field: Float[jax.Array, "n_faces 3 ..."]
                          ) -> Float[jax.Array, "n_vertices ..."]:
    """Compute the (integrated) FE divergence of a per-face vector field (3D).

    Same as :func:`compute_divergence_2d` but for surfaces embedded in 3D.
    """
    faces = hemesh.faces
    grads = _fe_grad_phi_3d(vertices, hemesh)                  # (n_faces, 3, 3)
    areas = geom.get_triangle_areas(vertices, hemesh)          # (n_faces,)

    contrib = -jnp.einsum("fvd,fd...->fv...", grads, face_field)
    contrib = contrib * areas.reshape((-1,) + (1,) * (contrib.ndim - 1))

    trailing = face_field.shape[2:]
    result = jnp.zeros((hemesh.n_vertices,) + trailing)
    for corner in range(3):
        result = result.at[faces[:, corner]].add(contrib[:, corner])
    return result

# %% ../nbs/src/06_linear_operators.ipynb #normalderiv
def compute_normal_derivative_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh,
                                        vertex_field: Float[jax.Array, "n_vertices ..."],
                                        ) -> Float[jax.Array, "n_hes ..."]:
    """Integrated normal derivative (flux) of a vertex field across each half-edge, from edge lengths.

    For half-edge ``he`` inside a face, this is the flux of the piecewise-linear gradient
    through the dual edge segment of that face:
    ``D[he] = cot(theta_opposite(he)) / 2 * (u[dest[he]] - u[orig[he]])``,
    where ``theta_opposite`` is the corner angle opposite ``he``. It is 0 on boundary
    half-edges, which have no face.

    This is the per-half-edge quantity the cotangent Laplacian is assembled from. The twin
    half-edge measures the same edge from the adjacent face and with the opposite sign of
    ``u[dest] - u[orig]``, so the total flux across an edge is ``D - D[twin]`` and

        ``compute_cotan_laplace_intrinsic(l, h, u) == -sum_he_to_vertex_incoming(h, D - D[twin])``

    holds to machine precision. Note the *raw* sum of ``D`` over all half-edges is not zero:
    the two half-edges of an edge carry different opposite angles, and it is the combination
    ``D - D[twin]`` that cancels pairwise. Summing that over a set of vertices gives the net
    flux across the set's boundary (the discrete divergence theorem); over a closed mesh it
    is zero.

    Parameters
    ----------
    he_lengths : Float[Array, "n_hes"]
        Edge length per half-edge, e.g. from `geometry.get_he_length` or, under periodic
        boundary conditions, `periodic.get_periodic_he_lengths`.
    hemesh : HeMesh
        Half-edge mesh.
    vertex_field : Float[Array, "n_vertices ..."]
        Per-vertex scalar, vector, or tensor field.

    Returns
    -------
    Float[Array, "n_hes ..."]
        Integrated normal derivative per half-edge, 0 on boundary half-edges.
    """
    w_he = geom.get_cotan_weights_per_he_intrinsic(he_lengths, hemesh) / 2
    diff = vertex_field[hemesh.dest] - vertex_field[hemesh.orig]
    return (w_he * diff.T).T


def normal_derivative_sparse_intrinsic(he_lengths: Float[jax.Array, " n_hes"], hemesh: msh.HeMesh
                                       ) -> jsparse.BCOO:
    """Sparse matrix form of `compute_normal_derivative_intrinsic`, of shape ``(n_hes, n_vertices)``."""
    w_he = geom.get_cotan_weights_per_he_intrinsic(he_lengths, hemesh) / 2
    rows = jnp.arange(hemesh.n_hes, dtype=jnp.int32)
    data = jnp.concatenate([w_he, -w_he])
    indices = jnp.concatenate([jnp.stack([rows, hemesh.dest.astype(jnp.int32)], axis=1),
                               jnp.stack([rows, hemesh.orig.astype(jnp.int32)], axis=1)], axis=0)
    return jsparse.BCOO((data, indices), shape=(hemesh.n_hes, hemesh.n_vertices))


def compute_normal_derivative(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh,
                              vertex_field: Float[jax.Array, "n_vertices ..."],
                              ) -> Float[jax.Array, "n_hes ..."]:
    """Integrated normal derivative (flux) of a vertex field across each half-edge.

    Position-based form of `compute_normal_derivative_intrinsic`; see there for details.
    """
    return compute_normal_derivative_intrinsic(geom.get_he_length(vertices, hemesh), hemesh, vertex_field)


def normal_derivative_sparse(vertices: Float[jax.Array, "n_vertices dim"], hemesh: msh.HeMesh
                             ) -> jsparse.BCOO:
    """Sparse matrix form of `compute_normal_derivative`, of shape ``(n_hes, n_vertices)``.

    ``normal_derivative_sparse(v, h) @ u == compute_normal_derivative(v, h, u)``.
    """
    return normal_derivative_sparse_intrinsic(geom.get_he_length(vertices, hemesh), hemesh)

# %% ../nbs/src/06_linear_operators.ipynb #3d9366df
def linear_op_to_sparse(op: Callable,
                        in_shape: tuple[int, ...],
                        out_shape: tuple[int, ...],
                        dtype: jnp.dtype | None = None,
                        chunk_size: int = 256,
                        tol: float = 0.0,
                        ) -> jsparse.BCOO:
    """Build a sparse matrix for a linear map using batched one-hot probes.

    Parameters
    ----------
    op : Callable
        Linear map taking and returning 1d arrays.
    in_shape, out_shape : tuple[int, ...]
        Input and output shapes of ``op``. Must be 1d. ``out_shape`` is checked
        against what ``op`` actually returns.
    dtype : jnp.dtype | None
        Output dtype. Inferred from ``op`` if None.
    chunk_size : int
        Number of one-hot probes evaluated per batch.
    tol : float
        Entries with ``|value| <= tol`` are dropped.

    Returns
    -------
    jsparse.BCOO
        Sparse matrix of shape ``(n_out, n_in)``.

    Note: this needs one probe per input dimension, so it costs O(n_in) applications of
    ``op`` with an O(chunk_size * n_out) dense intermediate. On a 36k-vertex mesh this is
    ~20x slower than assembling the cotan Laplacian directly; prefer a dedicated
    assembler when one exists.
    """
    if len(in_shape) != 1 or len(out_shape) != 1:
        raise ValueError("Only 1D input/output supported for now.")
    n_in = in_shape[0]
    n_out = out_shape[0]
    if dtype is None:
        dtype = jnp.result_type(op(jnp.zeros((n_in,))))

    data_list: list[np.ndarray] = []
    row_list: list[np.ndarray] = []
    col_list: list[np.ndarray] = []

    for start in range(0, n_in, chunk_size):
        end = min(start + chunk_size, n_in)
        idx = jnp.arange(start, end, dtype=jnp.int32)
        basis = jax.nn.one_hot(jnp.array(idx), n_in, dtype=dtype)
        cols = jax.vmap(op)(basis)  # (chunk, n_out)
        # a wrong out_shape would put probe rows out of bounds, and BCOO silently
        # DROPS out-of-bounds entries -- returning a quietly incorrect matrix.
        if cols.shape[1:] != (n_out,):
            raise ValueError(f"op returned output shape {cols.shape[1:]} per probe, "
                             f"but out_shape says {(n_out,)}")
        mask = jnp.abs(cols) > tol
        col_in_batch, row_out = jnp.nonzero(mask)
        if col_in_batch.size == 0:
            continue

        data_list.append(cols[col_in_batch, row_out])
        row_list.append(row_out)
        col_list.append(idx[col_in_batch])

    if len(data_list) == 0:
        return jsparse.empty((n_out, n_in), dtype=dtype)
    data = jnp.concatenate(data_list)
    rows = jnp.concatenate(row_list)
    cols = jnp.concatenate(col_list)
    indices = jnp.stack([jnp.array(rows, dtype=jnp.int32),
                            jnp.array(cols, dtype=jnp.int32)], axis=1)
    return jsparse.BCOO((data, indices), shape=(n_out, n_in))
