# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/02_halfedge_datastructure.ipynb.

# %% auto #0
__all__ = ['label_plot', 'get_half_edge_arrays_vectorized', 'HeMesh', 'test_mesh_validity', 'connect_boundary_to_infinity',
           'get_real_faces', 'get_n_vertices_edges_faces', 'is_closed', 'get_n_boundary_loops',
           'get_euler_characteristic', 'get_n_connected_components', 'get_genus', 'GeomMesh', 'Mesh', 'cellplot',
           'tree_stack', 'tree_unstack']

# %% ../nbs/src/02_halfedge_datastructure.ipynb #d159edd4-4456-41f8-b520-8b1b69219c67
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

import igl

# %% ../nbs/src/02_halfedge_datastructure.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp

# %% ../nbs/src/02_halfedge_datastructure.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Float, Int, Bool, PyTree 
from typing import Any, Iterable, NamedTuple
from pathlib import Path
from enum import IntEnum

import dataclasses

# %% ../nbs/src/02_halfedge_datastructure.ipynb #45616576-ecbd-46f3-998b-ff82c6aa7bef
def label_plot(vertices: Float[jax.Array, "n_vertices 2"],
               faces: Int[jax.Array, "n_faces 3"],
               hemesh: None | PyTree=None,
               vertex_labels: bool = True, face_labels: bool=True,
               ax: None | mpl.axes.Axes=None,
               fontsize: int|None = None) -> None:
    """For debugging purposes. Plot triangular mesh with face/vertex labels in black/blue.
    If hemesh is not None, the connectivity info from it is used to plot the half-edge labels."""
    ax = plt.gca() if ax is None else ax
    if vertex_labels:
        for iv, v in enumerate(vertices):
            ax.text(*(v+np.array([0,.025])), str(iv),
                    color="tab:blue", ha="center", fontsize=fontsize)
    if face_labels:
        for ifc, fc in enumerate(faces):
            centroid = np.mean([vertices[iv] for iv in fc], axis=0)
            ax.text(*centroid, str(ifc), color="k", fontsize=fontsize, ha="center",)
    if hemesh is not None:
        edge_center = (vertices[hemesh.dest] + vertices[hemesh.orig])/2
        for ie in np.where(hemesh.is_unique)[0]:
            ax.text(*edge_center[ie], f"{ie}/{hemesh.twin[ie]}",
            color="tab:orange", ha="center", fontsize=fontsize)
            
    return None

# %% ../nbs/src/02_halfedge_datastructure.ipynb #0e885259
def get_half_edge_arrays_vectorized(n_vertices: int, faces: Int[jax.Array, "n_faces 3"]) -> list[Int[jax.Array, " n"]]:
    """
    Get half-edge data structure arrays from faces (vectorized). Returned arrays are dtype int32.
    For internal use to construct HeMesh objects.

    Returns: incident, orig, dest, twin, nxt, prv, heface, face_incident
    """
    # form all unique edges, ordered lexicographically
    faces_np = np.asarray(faces).astype(np.int64)
    edges = np.array(sorted([sorted(x) for x in igl.edges(faces_np)]))
    half_edges = np.vstack([edges, edges[:, ::-1]])

    # initialize the connectivity arrays. origin, destination, and twin are easy
    orig = half_edges[:, 0]
    dest = half_edges[:, 1]
    n_edges = edges.shape[0]
    twin = np.hstack([np.arange(n_edges) + n_edges, np.arange(n_edges)])

    n_hes = half_edges.shape[0]
    nxt = np.ones(n_hes, dtype=orig.dtype)
    prv = np.ones(n_hes, dtype=orig.dtype)
    heface = -1 * np.ones(n_hes, dtype=orig.dtype)

    # build mapping from (orig, dest) -> half-edge index via sorting
    order = np.lexsort((dest, orig))
    half_edges_sorted = half_edges[order]
    dtype = np.dtype([("o", half_edges_sorted.dtype), ("d", half_edges_sorted.dtype)])
    he_view = half_edges_sorted.view(dtype).ravel()

    def lookup(pairs: np.ndarray) -> np.ndarray:
        pairs_view = pairs.view(dtype).ravel()
        pos = np.searchsorted(he_view, pairs_view)
        # searchsorted silently returns a neighbouring slot for an absent pair, which
        # would build a corrupt mesh with no error at all. Validate instead.
        clipped = np.minimum(pos, he_view.size - 1)
        if np.any(pos >= he_view.size) or np.any(he_view[clipped] != pairs_view):
            raise ValueError(
                "faces reference an edge that is not in the half-edge table. The input "
                "must be a consistently oriented, edge-manifold triangle mesh without "
                "degenerate (repeated-vertex) faces.")
        return order[pos]

    # per-face half-edges (v0->v1, v1->v2, v2->v0)
    v0, v1, v2 = faces_np[:, 0], faces_np[:, 1], faces_np[:, 2]
    pairs0 = np.stack([v0, v1], axis=1)
    pairs1 = np.stack([v1, v2], axis=1)
    pairs2 = np.stack([v2, v0], axis=1)
    h0 = lookup(pairs0)
    h1 = lookup(pairs1)
    h2 = lookup(pairs2)

    ifc = np.arange(faces_np.shape[0])
    heface[h0] = ifc
    heface[h1] = ifc
    heface[h2] = ifc

    nxt[h0] = h1
    nxt[h1] = h2
    nxt[h2] = h0

    prv[h0] = h2
    prv[h1] = h0
    prv[h2] = h1

    # boundary loops (match reference orientation)
    for loop in igl.boundary_loop_all(faces_np):
        loop = np.asarray(loop)
        v_nxt = np.roll(loop, 1)
        v = loop
        v_prv = np.roll(loop, -1)
        hb0 = lookup(np.stack([v_prv, v], axis=1))
        hb1 = lookup(np.stack([v, v_nxt], axis=1))
        nxt[hb0] = hb1
        prv[hb1] = hb0

    # incident half-edge per vertex (minimum index in original ordering)
    order_orig = np.argsort(orig)
    orig_sorted = orig[order_orig]
    first = np.concatenate([[0], np.where(orig_sorted[1:] != orig_sorted[:-1])[0] + 1])
    incident = np.full(n_vertices, -1, dtype=orig.dtype)
    min_idx = np.minimum.reduceat(order_orig, first)
    incident[orig_sorted[first]] = min_idx

    # first half-edge per face (minimum index among the three)
    face_incident = np.minimum(np.minimum(h0, h1), h2)

    return [jnp.array(arr, dtype=jnp.int32) for arr in [incident, orig, dest, twin, nxt, prv, heface, face_incident]]

# %% ../nbs/src/02_halfedge_datastructure.ipynb #965577eb-7900-4c5d-8f0a-8cc2fd40caba
@jax.tree_util.register_dataclass
@dataclasses.dataclass(repr=False, eq=False, frozen=True)
class HeMesh:
    """
    Half-edge mesh data structure for triangular meshes.

    A half-edge mesh is described by a set of half-edges and several
    arrays that specify their connectivity (see full explanation in `mesh` module docs).
    This class serves as a container for multiple arrays.
    For compatibility with JAX, after initialization, do not
    modify these arrays in-place; always return a new HeMesh object.
    The mesh vertices may live in whatever dimension (or in periodic BC)
    - this does not affect the connectivity bookkeeping.

    Half-edge meshes are initialized from a list of triangles and a 
    number of vertices, and can return the original triangles (e.g., to save as a .obj).

    All information and methods are purely "combinatorial". The
    HeMesh class does _not_ contain the vertex or face positions.
    These are saved in the GeomHeMesh class that combines
    a HeMesh (combinatorics) with a couple of other arrays (geometry).

    Comparing two HeMeshes checks for equality of all arrays they contain,
    not for graph isomorphism (equivalence up to vertex renaming).

    ---Conventions---
    
    For vertices, the `incident` half-edge points _away_ from the vertex.

    To describe the mesh boundary, there are two options:
        1. Initialize from a triangulation with a boundary. Half-edges without
        a face (boundary) are assigned heface=-1.
        2. Initialize from a triangulation without boundary, where certain vertices
         are "at infinity". They should have coordinates [np.inf, np.inf].
         Each infinity vertex corresponds to one boundary. For a single
         boundary, the vertex at infinity is, by convention, the final one.
    Mixing the two conventions will lead to errors.

    Starting from a set of triangles, the half-edges are initialized as follows:
    The 1st N_edges half-edges are (origin_vertex, destination_vertex), in lexicographic order, with 
    origin_vertex < destination_vertex. The 2nd N_edges are their twins, in the same order.

    **Attributes**
    
    incident : Int[jax.Array, "n_vertices"]

    orig : Int[jax.Array, "n_hes"]

    dest : Int[jax.Array, "n_hes"]

    nxt : Int[jax.Array, "n_hes"]

    prv : Int[jax.Array, "n_hes"]

    twin : Int[jax.Array, "n_hes"]

    heface : Int[jax.Array, "n_hes"]

    face_incident : Int[jax.Array, "n_faces"]

    inf_vertices : tuple[Int]

    **Property methods (use like attributes)**

    n_vertices : int

    n_hes : int

    n_faces : int

    n_items : tuple[int, int, int]

    faces : Int[jax.Array, "n_faces 3"]

    has_inf_vertex : bool

    is_inf_face : Bool[jax.Array, "n_faces"]

    is_unique : Bool[jax.Array, "n_hes"]

    is_inf_he : Bool[jax.Array, "n_hes"]

    is_bdry_he : Bool[jax.Array, "n_hes"]

    is_bdry_edge : Bool[jax.Array, "n_hes"]

    is_bdry : Bool[jax.Array, "n_vertices"]

    **Static methods**

    from_triangles : tuple[int, Int[jax.Array, "n_faces 3"], Int[jax.Array, "n_boundaries"] -> HeMesh

    The arguments are the number of vertices, the n_faces * 3 array of faces, and, optionally,
    a list of "infinity" vertices.   

    **Class methods**

    iterate_around_vertex : int -> Int[jax.Array, "n_neighbors"]

    save : str -> None:

    **Static methods**
    
    load : str -> HeMesh

    """
    
    incident : Int[jax.Array, "*batch n_vertices"]
    orig : Int[jax.Array, "*batch n_hes"]
    dest : Int[jax.Array, "*batch n_hes"] 
    twin : Int[jax.Array, "*batch n_hes"] 
    nxt : Int[jax.Array, "*batch n_hes"] 
    prv : Int[jax.Array, "*batch n_hes"]
    heface : Int[jax.Array, "*batch n_hes"]
    face_incident : Int[jax.Array, "*batch n_faces"]
    inf_vertices : tuple[()] | tuple[int] = dataclasses.field(default=(), metadata=dict(static=True))

    # convert from and to a list of triangles

    @staticmethod
    def from_triangles(n_vertices: int, faces: Int[jax.Array, "n_faces 3"],
                       inf_vertices: tuple[()] | tuple[int] =()):
        # get HE data arrays
        incident, orig, dest, twin, nxt, prv, heface, face_incident = get_half_edge_arrays_vectorized(n_vertices, faces)
        return HeMesh(incident, orig, dest, twin, nxt, prv, heface, face_incident, inf_vertices)

    @property
    def faces(self) -> Int[jax.Array, "n_faces 3"]:
        """Get faces (list of vertices per face)."""
        return jnp.stack([self.orig[self.face_incident],
                          self.dest[self.face_incident],
                          self.dest[self.nxt[self.face_incident]]], axis=1)
    
    # mesh size info

    @property
    def n_vertices(self) -> int:
        return self.incident.shape[-1]
    
    @property
    def n_hes(self) -> int:
        return self.orig.shape[-1]

    @property
    def n_faces(self) -> int:
        return self.face_incident.shape[-1]
    @property
    def n_items(self) -> tuple[int, int, int]:
        return (self.n_vertices, self.n_hes, self.n_faces)
    
    @property
    def is_unique(self) -> Bool[jax.Array, "n_hes"]:
        """Get an (arbitrary) set of unique half-edges (every edge is represented once)."""
        return self.orig < self.dest

    def __repr__(self) -> str:
        return "HeMesh(N_V={}, N_HE={}, N_F={})".format(*self.n_items)
    
    # boundary info - implemented as class methods to hide "implementation detail" of infinity vertices
    
    @property
    def has_inf_vertex(self) -> bool:
        return len(self.inf_vertices)>0

    @property
    def _inf_vertex_array(self) -> Int[jax.Array, " n_inf"]:
        """inf_vertices as an array of the same integer dtype as the connectivity.

        jnp.array(()) would be a float array, which breaks jnp.isin against int32
        indices under strict dtype promotion.
        """
        return jnp.array(self.inf_vertices, dtype=self.orig.dtype)

    @property
    def is_inf_face(self) -> Bool[jax.Array, "n_faces"]:
        """True if face is fictitious/connected to an infinity vertex."""
        return jnp.isin(self.faces, self._inf_vertex_array).any(axis=1)

    @property
    def is_inf_he(self) -> Bool[jax.Array, "n_hes"]:
        """True if half-edge is fictitious/connected to an infinity vertex."""
        return jnp.isin(self.orig, self._inf_vertex_array) | jnp.isin(self.dest, self._inf_vertex_array)

    @property
    def is_bdry_he(self) -> Bool[jax.Array, "n_hes"]:
        """True if the half-edge lies on the mesh boundary (either convention)."""
        # has_inf_vertex is a static Python bool, so this is a plain `if`:
        # jax.lax.select would trace and materialise both branches on every call.
        if self.has_inf_vertex:
            return jnp.isin(self.dest[self.nxt], self._inf_vertex_array)
        return self.heface == -1

    @property
    def is_bdry_edge(self) -> Bool[jax.Array, "n_hes"]:
        return self.is_bdry_he | self.is_bdry_he[self.twin]
    
    @property
    def is_bdry(self) -> Bool[jax.Array, "n_vertices"]:
        """True if the vertex lies on the mesh boundary (either convention)."""
        # scatter in bool rather than mixing int into a float accumulator, which fails
        # under jax_numpy_dtype_promotion='strict'
        return jnp.zeros(self.n_vertices, dtype=bool).at[self.dest].max(self.is_bdry_he)

    # mesh traversal
    
    def iterate_around_vertex(self, v: int) -> Int[jax.Array, " n_neighbors"]:
        """Get list of half-edges going out of a vertex.

        Not jittable (the output length is data-dependent). Raises if the vertex has
        no outgoing half-edge, or if the one-ring fails to close.
        """
        if int(self.incident[v]) < 0:
            raise ValueError(f"vertex {v} has no outgoing half-edge "
                             "(it is not referenced by any face)")
        polygon_edges = [self.incident[v]]
        while True: # this while loop is hard to rewrite using jax.lax since the output shape is not known!
            next_edge = self.twin[self.prv[polygon_edges[-1]]]
            if next_edge == polygon_edges[0]:
                break
            polygon_edges.append(next_edge)
            if len(polygon_edges) > self.n_hes:  # corrupt connectivity: never closes
                raise RuntimeError(f"one-ring around vertex {v} does not close; "
                                   "the mesh connectivity is invalid")
        return jnp.array(polygon_edges)

    @property
    def bdry_loops(self) -> list[Int[jax.Array, " loop_length"]]:
        """Boundary loops, as arrays of vertex indices.

        Loops are oriented consistently with the face orientation under both
        boundary conventions (heface == -1 and vertices at infinity).
        """
        if not self.has_inf_vertex:
            return [jnp.asarray(loop) for loop in igl.boundary_loop_all(np.asarray(self.faces, dtype=np.int64))]
        # iterate_around_vertex traverses the infinity vertex the other way round,
        # so reverse to match the orientation of the heface == -1 convention.
        return [self.dest[self.iterate_around_vertex(v)][::-1] for v in self.inf_vertices]
        
    # copying, saving, and loading

    def __copy__(self):
        return HeMesh(**dataclasses.asdict(self)) # no need to copy since all entries are immutable
    
    def save(self, file: str | Path) -> None:
        """Save HeMesh to .npz archive of np.arrays"""
        dict_to_save = dataclasses.asdict(self)
        dict_to_save["inf_vertices"] = jnp.array(self.inf_vertices)
        np.savez(file, **dict_to_save, allow_pickle=False)
        return None

    @staticmethod
    def load(file: str | Path) -> "HeMesh":
        """Load a HeMesh from an .npz archive written by `save`."""
        dict_to_load = dict(np.load(file))
        inf_vertices = tuple(int(x) for x in dict_to_load.pop("inf_vertices"))
        # jnp.asarray: np.load returns numpy arrays, which do not support .at[] updates
        arrays = {k: jnp.asarray(v, dtype=jnp.int32) for k, v in dict_to_load.items()}
        return HeMesh(**arrays, inf_vertices=inf_vertices)

    # equality comparisons. Two meshes are equal if all the arrays they contain are.
    # isomorphic meshes _can_ compare to false if, e.g., the orderings are different.
    
    # connectivity is static across a simulation, so allow use as a static jit argument.
    # Identity hash: consistent with the pytree registration, and __eq__ is value-based.
    __hash__ = object.__hash__

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, HeMesh):
            return False          
        if not self.inf_vertices == other.inf_vertices:
            return False
        return jax.tree_util.tree_all(jax.tree.map(jnp.array_equal, dataclasses.asdict(self), dataclasses.asdict(other))) # exact comparison: these are integer index arrays

# %% ../nbs/src/02_halfedge_datastructure.ipynb #f9d0be63
def test_mesh_validity(h: HeMesh, verbose: bool=False) -> bool:
    """Test if a mesh is valid. Returns True if valid, optionally, returns message.

    Checks both for consistency of the HeMesh datastructure AND whether the mesh is edge- and vertex 
    manifold (defines a 2D surface).

    Parameters
    ----------
    h : HeMesh
        Half-edge mesh to validate.
    verbose : bool
        Return diagnostic message.
        
    Returns
    -------
    bool OR (bool, str)
        True if the mesh is valid. Also returns a string with a message if verbose = True
    """
    ar = jnp.arange(h.n_hes)
    message = ""
    valid = True
    if not h.orig.shape == h.dest.shape == h.nxt.shape == h.prv.shape == h.twin.shape == h.heface.shape:
        valid = False
        message += "shapes failed. "
    if not jnp.array_equal(h.twin[h.twin], ar):
       valid = False
       message += "twin.twin failed. "
    if not jnp.array_equal((h.prv[h.prv[h.prv]])[~h.is_bdry_edge], ar[~h.is_bdry_edge]):
        valid = False
        message +=  "prv.prv.prv failed."
    if not jnp.array_equal((h.nxt[h.nxt[h.nxt]])[~h.is_bdry_edge], ar[~h.is_bdry_edge]):
        valid = False
        message += "nxt.nxt.nxt failed. "
    # nxt/prv must be mutually inverse everywhere, including along boundary loops,
    # which the masked cubing checks above do not constrain at all.
    if not jnp.array_equal(h.nxt[h.prv], ar):
        valid = False
        message += "nxt.prv failed. "
    if not jnp.array_equal(h.prv[h.nxt], ar):
        valid = False
        message += "prv.nxt failed. "
    if not jnp.array_equal(h.dest, h.orig[h.nxt]):
        valid = False
        message += "dest vs orig.nxt failed. "
    if not jnp.array_equal(h.heface[h.nxt], h.heface):
        valid = False
        message += "face.nxt failed. "
    if not jnp.array_equal(h.heface[h.nxt], h.heface[h.prv]):
        valid = False
        message += "face.nxt vs face.prv failed. "
    if not jnp.array_equal(h.orig[h.incident], jnp.arange(h.n_vertices)):
        valid = False
        message += "orig.incident failed. "
    if not jnp.array_equal(h.heface[h.face_incident], jnp.arange(h.n_faces)):
        valid = False
        message += "face.face_incident failed. "
    if not jnp.array_equal(h.orig, h.dest[h.twin]):
        valid = False
        message += "orig vs dest.twin failed. "
    faces_np = np.asarray(h.faces, dtype=np.int64)  # igl requires int64
    if not igl.is_edge_manifold(faces_np)[0] and igl.is_vertex_manifold(faces_np)[0]:
        valid = False
        message += "manifold check failed. "
    if verbose:
        return valid, message
    return valid

def _canonical_faces_np(F: np.ndarray) -> np.ndarray:
    """Helper function to canonicalize faces for testing."""
    F = np.asarray(F, dtype=np.int64)  # int32 overflows the base-(max+1) key above ~1300 vertices
    F = np.sort(F, axis=1)
    keys = F[:, 0] * (F[:, 2].max() + 1) ** 2 + F[:, 1] * (F[:, 2].max() + 1) + F[:, 2]
    return F[np.argsort(keys)]


# %% ../nbs/src/02_halfedge_datastructure.ipynb #4378ad6f
def connect_boundary_to_infinity(vertices: Float[jax.Array, "n_vertices 2"], faces: Int[jax.Array, "n_faces 3"]
                                ) -> tuple[Float[jax.Array, "n_vertices_new 2"],
                                           Int[jax.Array, "n_faces_new 3"],
                                           tuple[int]]:
    """
    Connect boundary loop(s) to infinity.
    
    New vertices are appended to the end of vertex array and have coordinates [np.inf, np.inf].

    Parameters 
    ----------
    vertices : Float[jax.Array, "n_vertices 2"]
        Vertex positions.
    faces : Int[jax.Array, "n_faces 3"]
        Faces (triangles) as list of vertex indices.

    Returns
    -------
    new_vertices : Float[jax.Array, "n_vertices_new 2"]
        Vertex positions with infinity vertices appended.
        One infinity vertex per boundary loop.
    new_faces : Int[jax.Array, "n_faces_new 3"]
        Faces (triangles) as list of vertex indices, with new faces added to connect
        boundary loops to infinity vertices.
    inf_vertices : tuple[Int]
        Indices of infinity vertices in new_vertices.
        Will be (n_vertices, n_vertices+1, ..., n_vertices+n_boundaries-1).
    """
    boundary_loops = igl.boundary_loop_all(np.asarray(faces, dtype=np.int64))  # igl requires int64
    new_vertices = jnp.copy(vertices)
    new_faces = jnp.copy(faces)

    for loop in boundary_loops:
        inf_index = new_vertices.shape[0]
        inf_faces = np.stack([[inf_index, v2, v1] for v1, v2 in zip(loop, np.roll(loop, -1))])
        new_vertices = jnp.vstack([new_vertices, jnp.inf*jnp.ones_like(new_vertices[:1])])
        new_faces = jnp.vstack([new_faces, inf_faces])
    
    return new_vertices, new_faces, tuple(range(vertices.shape[0], new_vertices.shape[0]))

# %% ../nbs/src/02_halfedge_datastructure.ipynb #topohelpers
def get_real_faces(hemesh: HeMesh) -> Int[np.ndarray, "n_real_faces 3"]:
    """Faces as an int64 numpy array, with fictitious (infinity) faces removed.

    Useful to hand a mesh to `igl`, which requires int64 and has no notion of the
    "vertex at infinity" boundary convention.
    """
    faces = np.asarray(hemesh.faces, dtype=np.int64)
    if hemesh.has_inf_vertex:
        faces = faces[~np.asarray(hemesh.is_inf_face)]
    return faces


def get_n_vertices_edges_faces(hemesh: HeMesh) -> tuple[int, int, int]:
    """Counts of real (non-fictitious) vertices, edges, and faces."""
    faces = get_real_faces(hemesh)
    n_vertices = hemesh.n_vertices - len(hemesh.inf_vertices)
    return n_vertices, int(igl.edges(faces).shape[0]), int(faces.shape[0])


def is_closed(hemesh: HeMesh) -> bool:
    """True if the mesh has no boundary."""
    return not bool(hemesh.is_bdry_he.any())


def get_n_boundary_loops(hemesh: HeMesh) -> int:
    """Number of boundary loops (0 for a closed mesh, 1 for a disk, 2 for a cylinder)."""
    return len(hemesh.bdry_loops)


def get_euler_characteristic(hemesh: HeMesh) -> int:
    """Euler characteristic chi = V - E + F.

    2 for a sphere, 1 for a disk, 0 for a torus.
    """
    n_vertices, n_edges, n_faces = get_n_vertices_edges_faces(hemesh)
    return n_vertices - n_edges + n_faces


def get_n_connected_components(hemesh: HeMesh) -> int:
    """Number of edge-connected components of the mesh."""
    return int(igl.facet_components(get_real_faces(hemesh))[0])


def get_genus(hemesh: HeMesh) -> int:
    """Genus of the surface, from chi = 2*n_components - 2*genus - n_boundary_loops.

    0 for a sphere or disk, 1 for a torus. Assumes an orientable mesh (which the
    half-edge construction guarantees). Raises if the result is not an integer, which
    indicates an invalid mesh.
    """
    chi = get_euler_characteristic(hemesh)
    numerator = 2 * get_n_connected_components(hemesh) - chi - get_n_boundary_loops(hemesh)
    if numerator % 2 != 0:
        raise ValueError(f"non-integer genus from chi={chi}; the mesh is not a valid "
                         "orientable surface")
    return numerator // 2


# %% ../nbs/src/02_halfedge_datastructure.ipynb #c7c0e33c-a06d-4a93-9d88-6aa0716bdf5b
@jax.tree_util.register_dataclass
@dataclasses.dataclass(repr=False, eq=False, frozen=False,)
class GeomMesh:
    """
    Data class for holding mesh geometry and mesh-associated variables.
    To be combined with a HeMesh to specify the connectivity.

    One array (for vertex positions) must always be present. A second,
    optional, standard entry is a set of positions for each face.
    The mesh coordinates can live in any dimension

    Optionally, vertices, half-edges, and faces can have attributes (stored as dictionaries).
    The keys of the dictionary should be taken from a suitable 'enum'. The values are
    ndarrays, whose 0th axis is (vertices/edges/faces). These attribute dicts are
    initialized empty and can be set afterwards.

    Unlike `HeMesh`, this class is intentionally *not* frozen. Vertex positions and
    per-mesh attributes may be updated directly (e.g. during a simulation step),
    whereas mesh connectivity (`HeMesh`) should never be edited by hand.

    This class stores no element counts of its own: the number of vertices,
    half-edges, and faces belongs to the `HeMesh`. Use `check_compatibility(hemesh)`
    to confirm a geometry and a connectivity match.

    
    **Attributes**

    vertices : Float[jax.Array, "n_vertices dim"]

    face_positions : Float[jax.Array, "n_faces dim"]

    vertex_attribs : dict[IntEnum, Float[jax.Array, "n_vertices ..."]]

    he_attribs : dict[IntEnum, Float[jax.Array, "n_hes ..."]]

    face_attribs : dict[IntEnum, Float[jax.Array, "n_faces ..."]]

    **Property methods (use like attributes)**

    dim : int

    **Class methods**

    validate_dimensions : None

    check_compatibility : HeMesh -> bool

    **Static methods**

    load : str -> GeomMesh

    """

    vertices : Float[jax.Array, "*batch n_vertices dim"]
    face_positions : Float[jax.Array, "*batch n_faces dim"] = dataclasses.field(default_factory=lambda : jnp.array([]))
    vertex_attribs : dict[IntEnum, Float[jax.Array, "n_vertices ..."]] = dataclasses.field(default_factory=dict)
    he_attribs : dict[IntEnum, Float[jax.Array, "n_hes ..."]] = dataclasses.field(default_factory=dict)
    face_attribs : dict[IntEnum, Float[jax.Array, "n_faces ..."]] = dataclasses.field(default_factory=dict)

    @property
    def dim(self) -> int:
        return self.vertices.shape[-1]

    def _derived_counts(self) -> tuple[int, int | None, int | None]:
        """(n_vertices, n_hes, n_faces), with None where nothing determines the count."""
        n_vertices = self.vertices.shape[0]
        n_hes = next((val.shape[0] for val in self.he_attribs.values()), None)
        n_faces = self.face_positions.shape[0] if self.face_positions.shape[0] > 0 else None
        if n_faces is None:
            n_faces = next((val.shape[0] for val in self.face_attribs.values()), None)
        return n_vertices, n_hes, n_faces

    def __repr__(self) -> str:
        n_vertices, n_hes, n_faces = self._derived_counts()
        return "GeomMesh(D={}, N_V={}, N_HE={}, N_F={})".format(
            self.dim, n_vertices,
            "N/A" if n_hes is None else n_hes,
            "N/A" if n_faces is None else n_faces)

    def validate_dimensions(self) -> None:
        """Check that this object is internally consistent.

        All vertex attributes must have as many entries as there are vertices, all
        half-edge attributes must agree with each other, and all face attributes must
        agree with each other and with `face_positions`. Nothing here can check against
        the connectivity -- use `check_compatibility` for that.

        Raises
        ------
        ValueError
            If any attribute has an inconsistent number of entries.
        """
        n_vertices, n_hes, n_faces = self._derived_counts()
        if any(val.shape[0] != n_vertices for val in self.vertex_attribs.values()):
            raise ValueError("Vertex attribute dimension inconsistent with vertices")
        if n_hes is not None and any(val.shape[0] != n_hes for val in self.he_attribs.values()):
            raise ValueError("Half-edge attribute dimensions inconsistent with each other")
        if n_faces is not None and any(val.shape[0] != n_faces for val in self.face_attribs.values()):
            raise ValueError("Face attribute dimensions inconsistent with each other/face_positions")
        return None

    def check_compatibility(self, hemesh: HeMesh) -> bool:
        """True if this geometry matches the given connectivity.

        Checks the vertex count, and the number of entries of `face_positions` and of every
        attribute dict against the corresponding count in `hemesh`. Absent optional data
        (empty `face_positions`, empty attribute dicts) is not an incompatibility.
        """
        if self.vertices.shape[0] != hemesh.n_vertices:
            return False
        if self.face_positions.shape[0] not in (0, hemesh.n_faces):
            return False
        for attribs, n in [(self.vertex_attribs, hemesh.n_vertices),
                           (self.he_attribs, hemesh.n_hes),
                           (self.face_attribs, hemesh.n_faces)]:
            if any(val.shape[0] != n for val in attribs.values()):
                return False
        return True

    ## copying, loading, and saving

    def __copy__(self):
        return GeomMesh(vertices=self.vertices, face_positions=self.face_positions,
                   vertex_attribs={key: jnp.copy(val) for key, val in self.vertex_attribs.items()},
                   he_attribs={key: jnp.copy(val) for key, val in self.he_attribs.items()},
                   face_attribs={key: jnp.copy(val) for key, val in self.face_attribs.items()})

    def save(self, file: str | Path) -> None:
        """Save GeomMesh to .npz archive of np.arrays."""
        np.savez(file,
             vertices=self.vertices, face_positions=self.face_positions,
             **{f"VertexAttribs.{key.name}": val for key, val in self.vertex_attribs.items()},
             **{f"HeAttribs.{key.name}": val for key, val in self.he_attribs.items()},
             **{f"FaceAttribs.{key.name}": val for key, val in self.face_attribs.items()},
             allow_pickle=False)
        return None

    @staticmethod
    def load(file: str | Path,
             vertex_attribs_enum: type[IntEnum] | None = None,
             he_attribs_enum: type[IntEnum] | None = None,
             face_attribs_enum: type[IntEnum] | None = None) -> "GeomMesh":
        """
        Load GeomMesh from .npz archive.

        Parameters
        ----------
        file : str | Path
            Path to the .npz file.
        vertex_attribs_enum : type[IntEnum] | None
            If provided, convert vertex attribute string keys back to this IntEnum.
        he_attribs_enum : type[IntEnum] | None
            If provided, convert half-edge attribute string keys back to this IntEnum.
        face_attribs_enum : type[IntEnum] | None
            If provided, convert face attribute string keys back to this IntEnum.
        """
        npzfile = np.load(file)
        def _parse_attribs(prefix: str, enum_cls: type[IntEnum] | None) -> dict:
            attribs = {key.split(".")[1]: jnp.asarray(val)
                       for key, val in npzfile.items() if key.split(".")[0] == prefix}
            if enum_cls is not None:
                attribs = {enum_cls[k]: v for k, v in attribs.items()}
            return attribs

        return GeomMesh(vertices=jnp.asarray(npzfile['vertices']),
                        face_positions=jnp.asarray(npzfile['face_positions']),
                        vertex_attribs=_parse_attribs("VertexAttribs", vertex_attribs_enum),
                        he_attribs=_parse_attribs("HeAttribs", he_attribs_enum),
                        face_attribs=_parse_attribs("FaceAttribs", face_attribs_enum))

    # equality comparisons. Two meshes are equal if all of the arrays they contain are equal.

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, GeomMesh):
            return False
        leaves_self, tree_self = jax.tree_util.tree_flatten(self)
        leaves_other, tree_other = jax.tree_util.tree_flatten(other)
        if tree_self != tree_other:   # different attribute keys / optional data present
            return False
        # shapes must match before comparing values:
        if any(a.shape != b.shape for a, b in zip(leaves_self, leaves_other)):
            return False
        return jax.tree_util.tree_all(jax.tree.map(jnp.array_equal, leaves_self, leaves_other))


# %% ../nbs/src/02_halfedge_datastructure.ipynb #504fefa9-e469-4056-a6b9-a5496b3f6ff3
class Mesh(NamedTuple):
    """Combine geometric and connectivity info into a single object."""
    geommesh: GeomMesh
    hemesh: HeMesh

# %% ../nbs/src/02_halfedge_datastructure.ipynb #b4ccf185-8b5b-46f9-8d3f-9c7f7d77f516
def cellplot(hemesh: HeMesh, face_positions: Float[jax.Array, "n_faces 2"],
             cell_colors: None | str | Float[np.ndarray, "4"] | Float[np.ndarray, "n_vertices 4"] =None,
             mpl_polygon_kwargs: None | dict[str, Any] = None) -> mpl.collections.PatchCollection:
    """
    Plot a cell tesselation.
    
    cell_colors can be either a single color (for all cells) or a vector of rgba values.
    Only interior cells are plotted.
    """
    if mpl_polygon_kwargs is None:
        mpl_polygon_kwargs = {"lw": 1, "ec": "k"}
    # formatting for the cell colors - make into a list
    if cell_colors is None:
        cell_colors = np.zeros((hemesh.n_vertices, 4))
    if isinstance(cell_colors, str):
        cell_colors = [cell_colors for v in range(hemesh.n_vertices)]
    if isinstance(cell_colors, Iterable):
        assert len(cell_colors) in [4, hemesh.n_vertices], "Cell color must be 1 or n_vertices rgba values"
        if len(cell_colors) == 4:
            cell_colors = [cell_colors for v in range(hemesh.n_vertices)]
    # iterate over non-boundary vertices.
    polygons = []
    bdry = hemesh.is_bdry
    for v in range(hemesh.n_vertices):
        if not bdry[v]:
            polygon_edges = hemesh.iterate_around_vertex(v)
            polygon_vertices = face_positions[hemesh.heface[np.array(polygon_edges)]]
            polygons.append(mpl.patches.Polygon(polygon_vertices, color=cell_colors[v], **mpl_polygon_kwargs))
    return mpl.collections.PatchCollection(polygons, match_original=True)

# %% ../nbs/src/02_halfedge_datastructure.ipynb #d8e2ff2f
def tree_stack(xs : list[PyTree], axis=0) -> PyTree:
    """Stack a sequence of identical-structure pytrees along a new axis."""
    return jax.tree.map(lambda *leaves: jnp.stack(leaves, axis=axis), *xs)

def tree_unstack(xb: PyTree, axis=0) -> list[PyTree]:
    """Unstack a batched pytree along axis into a list of pytrees."""
    leaves, treedef = jax.tree.flatten(xb)
    B = leaves[0].shape[axis]
    # split every leaf along batch dimension
    per = [jax.tree.unflatten(treedef, [leaf.take(indices=i, axis=axis)  for leaf in leaves])
           for i in range(B)]
    return per
