# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb.

# %% auto #0
__all__ = ['displacement_periodic', 'displacement_periodic_twisted', 'get_periodic_he_lengths', 'get_periodic_triangle_areas',
           'get_periodic_area', 'get_periodic_barycentric_cell_areas', 'get_periodic_face_centroids',
           'get_periodic_face_corner_angles', 'get_periodic_corner_angles', 'get_periodic_face_corner_cotangents',
           'get_periodic_cotan_weights_per_he', 'get_periodic_cotan_weights_per_edge', 'get_periodic_voronoi_areas',
           'get_periodic_voronoi_face_positions', 'get_periodic_dual_he_length', 'get_periodic_voronoi_perimeters',
           'get_periodic_oriented_triangle_areas', 'get_periodic_triangle_orientations',
           'get_periodic_voronoi_areas_robust']

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #48f4c00d
import jax
import jax.numpy as jnp

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #b486f71a
from jaxtyping import Float 
from collections.abc import Callable

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #c2783a57
from . import trigonometry as trig
from .mesh import HeMesh
from . import adjacency as adj

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #02987b23
def displacement_periodic(r_1: Float[jax.Array, "2"], r_2: Float[jax.Array, "2"], L: Float[jax.Array, "2"]
                         ) -> Float[jax.Array, "2"]:
    """Return the minimum-image displacement on a rectangular torus.

    IMPORTANT: the minimum-image convention always returns the *shortest* periodic
    image, so it only reproduces the intended mesh edge when every edge is shorter
    than ``min(L)/2``. For a longer edge it silently returns the displacement to a
    different periodic image, giving wrong lengths, areas and angles with no error
    raised. Check with ``get_periodic_he_lengths(...).max() < L.min()/2``. This
    matters for coarse periodic meshes and for a shrinking or strongly sheared box.

    Parameters
    ----------
    r_1, r_2
        Positions in a periodic box.
    L
        Box lengths [L_x, L_y].

    Returns
    -------
    Float[Array, "2"]
        Displacement ``r_2 - r_1`` under the minimum-image convention.
    """
    d = r_2 - r_1
    return d - L * jnp.round(d / L)


def displacement_periodic_twisted(r_1: Float[jax.Array, "2"], r_2: Float[jax.Array, "2"],
                                  L: Float[jax.Array, "2"], s: float
                                  ) -> Float[jax.Array, "2"]:
    """Return the minimum-image displacement on a sheared periodic torus (Lees-Edwards BCs).

    Parameters
    ----------
    r_1, r_2
        Positions in a periodic box.
    L
        Box lengths [L_x, L_y].
    s
        Shear factor: wrapping in y shifts x by ``s * L_x``. This corresponds to vertex
        positions carrying the shear as ``x -> x - s * y``; the opposite sign stretches
        the edges instead of shearing them.

    Notes
    -----
    Inherits the ``max edge < min(L)/2`` precondition of `displacement_periodic`, applied
    *after* the twist. Note ``s`` near 0.5 (or 1.5, ...) violates it for a mesh that has
    not been sheared correspondingly -- a value every Lees-Edwards sweep passes through.
    """
    d = r_2 - r_1
    twist = s * L[0] * jnp.round(d[1] / L[1])
    d = d.at[0].set(d[0] + twist)
    return d - L * jnp.round(d / L)

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #3381813f
def _get_periodic_face_edge_lengths(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                    displacement_fn: Callable,
                                    ) -> tuple[Float[jax.Array, " n_faces"],
                                               Float[jax.Array, " n_faces"],
                                               Float[jax.Array, " n_faces"]]:
    """Return face-local edge lengths ``(la, lb, lc)`` from a periodic displacement function."""
    edge_vectors = jax.vmap(displacement_fn)(vertices[hemesh.orig], vertices[hemesh.dest])
    edge_lengths = jnp.linalg.norm(edge_vectors, axis=-1)
    return (edge_lengths[hemesh.prv[hemesh.face_incident]],
            edge_lengths[hemesh.face_incident],
            edge_lengths[hemesh.nxt[hemesh.face_incident]],)


def get_periodic_he_lengths(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                            displacement_fn: Callable,
                            ) -> Float[jax.Array, " n_hes"]:
    """Get lengths of half-edges using a periodic displacement function."""
    edge_vectors = jax.vmap(displacement_fn)(vertices[hemesh.orig], vertices[hemesh.dest])
    return jnp.linalg.norm(edge_vectors, axis=-1)


def get_periodic_triangle_areas(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                displacement_fn: Callable,
                                ) -> Float[jax.Array, " n_faces"]:
    """Compute triangle areas using a periodic displacement function."""
    la, lb, lc = _get_periodic_face_edge_lengths(vertices, hemesh, displacement_fn)
    return jax.vmap(trig.get_triangle_area_from_lengths)(la, lb, lc)


def get_periodic_area(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                      displacement_fn: Callable,
                      ) -> Float[jax.Array, ""]:
    """Total mesh area using a periodic displacement function."""
    return get_periodic_triangle_areas(vertices, hemesh, displacement_fn).sum()


def get_periodic_barycentric_cell_areas(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                        displacement_fn: Callable,
                                        ) -> Float[jax.Array, " n_vertices"]:
    """Get area of barycentric dual cell around each vertex, using a periodic displacement function.

    Defined as 1/3 * sum of adjacent triangle areas.
    """
    triangle_areas = get_periodic_triangle_areas(vertices, hemesh, displacement_fn)
    return adj.sum_face_to_vertex(hemesh, triangle_areas) / 3.0


def get_periodic_face_centroids(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                displacement_fn: Callable,
                                ) -> Float[jax.Array, "n_faces 2"]:
    """Compute face centroids (barycenters) using a periodic displacement function.

    Returns positions relative to vertex ``a`` of each face, not wrapped to the periodic box.
    """
    face_hes = hemesh.face_incident
    a = vertices[hemesh.orig[face_hes]]
    ab = jax.vmap(displacement_fn)(vertices[hemesh.orig[face_hes]],
                                   vertices[hemesh.dest[face_hes]])
    bc = jax.vmap(displacement_fn)(vertices[hemesh.orig[hemesh.nxt[face_hes]]],
                                   vertices[hemesh.dest[hemesh.nxt[face_hes]]])
    b = a + ab
    c = b + bc
    return (a + b + c) / 3


def get_periodic_face_corner_angles(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                    displacement_fn: Callable,
                                    ) -> Float[jax.Array, "n_faces 3"]:
    """Compute corner angles for each face using a periodic displacement function.

    Returns an ``(n_faces, 3)`` array where columns correspond to the three
    corners of each face in half-edge order ``(prv, face_incident, nxt)``.
    See also :func:`get_periodic_corner_angles` for per-half-edge indexing.
    """
    la, lb, lc = _get_periodic_face_edge_lengths(vertices, hemesh, displacement_fn)
    return jax.vmap(trig.get_angles_from_lengths)(la, lb, lc)


def get_periodic_corner_angles(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                               displacement_fn: Callable,
                               ) -> Float[jax.Array, " n_hes"]:
    """Compute the angle opposite to each half-edge, using a periodic displacement function.

    Returns a per-half-edge array (same convention as :func:`geometry.get_corner_angles`).
    """
    face_angles = get_periodic_face_corner_angles(vertices, hemesh, displacement_fn)
    per_he = jnp.zeros(hemesh.n_hes, dtype=vertices.dtype)
    per_he = per_he.at[hemesh.prv[hemesh.face_incident]].set(face_angles[:, 0])
    per_he = per_he.at[hemesh.face_incident].set(face_angles[:, 1])
    per_he = per_he.at[hemesh.nxt[hemesh.face_incident]].set(face_angles[:, 2])
    return per_he


def get_periodic_face_corner_cotangents(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                        displacement_fn: Callable,
                                        ) -> Float[jax.Array, "n_faces 3"]:
    """Compute corner cotangents for each face using a periodic displacement function.

    Returns an ``(n_faces, 3)`` array (same layout as :func:`get_periodic_face_corner_angles`).
    See also :func:`get_periodic_cotan_weights_per_he` for per-half-edge indexing.
    """
    la, lb, lc = _get_periodic_face_edge_lengths(vertices, hemesh, displacement_fn)
    return jax.vmap(trig.get_cotangents_from_lengths)(la, lb, lc)


def get_periodic_cotan_weights_per_he(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                      displacement_fn: Callable,
                                      ) -> Float[jax.Array, " n_hes"]:
    """Cotangent of the angle opposite to each half-edge, using a periodic displacement function.

    Returns a per-half-edge array (same convention as :func:`geometry.get_cotan_weights_per_he`).
    """
    face_cotangents = get_periodic_face_corner_cotangents(vertices, hemesh, displacement_fn)
    per_he = jnp.zeros(hemesh.n_hes, dtype=vertices.dtype)
    per_he = per_he.at[hemesh.prv[hemesh.face_incident]].set(face_cotangents[:, 0])
    per_he = per_he.at[hemesh.face_incident].set(face_cotangents[:, 1])
    per_he = per_he.at[hemesh.nxt[hemesh.face_incident]].set(face_cotangents[:, 2])
    return per_he


def get_periodic_cotan_weights_per_edge(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                        displacement_fn: Callable,
                                        ) -> Float[jax.Array, " n_hes"]:
    """Average cotangent weight per edge, using a periodic displacement function.

    Returns ``(cot_he + cot_twin) / 2`` (same convention as :func:`geometry.get_cotan_weights_per_edge`).
    """
    per_he = get_periodic_cotan_weights_per_he(vertices, hemesh, displacement_fn)
    return (per_he + per_he[hemesh.twin]) / 2

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #a40f1f15
def get_periodic_voronoi_areas(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_vertices"]:
    """Compute Voronoi cell areas from periodic edge lengths and cotangent weights."""
    edge_lengths = get_periodic_he_lengths(vertices, hemesh, displacement_fn)
    edge_areas = get_periodic_cotan_weights_per_edge(vertices, hemesh, displacement_fn) * edge_lengths**2 / 4
    return adj.sum_he_to_vertex_incoming(hemesh, edge_areas)


def get_periodic_voronoi_face_positions(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, "n_faces 2"]:
    """Compute periodic Voronoi dual positions (circumcenters) from intrinsic barycentric coordinates.

    Like `get_periodic_face_centroids`, the returned positions are NOT wrapped back into
    the periodic box: each is expressed in the image of its own face. Do not feed them to
    `geometry.get_dual_he_length` or `mesh.cellplot`, which assume unwrapped Euclidean
    coordinates -- use `get_periodic_dual_he_length` instead.
    """
    face_hes = hemesh.face_incident
    edge_lengths = get_periodic_he_lengths(vertices, hemesh, displacement_fn)
    la = edge_lengths[hemesh.nxt[face_hes]]
    lb = edge_lengths[hemesh.prv[face_hes]]
    lc = edge_lengths[face_hes]
    barycentric = jax.vmap(trig.get_circumcenter_from_lengths)(la, lb, lc)

    a = vertices[hemesh.orig[face_hes]]
    ab = jax.vmap(displacement_fn)(vertices[hemesh.orig[face_hes]], vertices[hemesh.dest[face_hes]])
    bc = jax.vmap(displacement_fn)(vertices[hemesh.orig[hemesh.nxt[face_hes]]],
                                   vertices[hemesh.dest[hemesh.nxt[face_hes]]])
    b = a + ab
    c = b + bc
    return (barycentric[:, :1] * a
            + barycentric[:, 1:2] * b
            + barycentric[:, 2:3] * c)


def get_periodic_dual_he_length(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_hes"]:
    """Voronoi dual edge lengths computed from cotangent weights.

    Equivalent to ``cotan_weights_per_edge * he_length``. Note this is the periodic
    counterpart of `geometry.get_voronoi_edge_lengths`, not of the similarly named
    `geometry.get_dual_he_length` (which takes explicit face positions and measures a
    Euclidean distance).
    """
    return (get_periodic_cotan_weights_per_edge(vertices, hemesh, displacement_fn)
            * get_periodic_he_lengths(vertices, hemesh, displacement_fn))


def get_periodic_voronoi_perimeters(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_vertices"]:
    """Compute Voronoi cell perimeters by summing dual edge lengths per vertex."""
    dual_lengths = get_periodic_dual_he_length(vertices, hemesh, displacement_fn)
    return adj.sum_he_to_vertex_incoming(hemesh, dual_lengths)

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #perareas
def get_periodic_oriented_triangle_areas(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_faces"]:
    """Signed triangle areas under periodic boundary conditions.

    Positive for counter-clockwise (positively oriented) triangles, negative for inverted
    ones. Unlike `get_periodic_triangle_areas`, which goes through Heron's formula on
    minimum-image edge lengths and is therefore unconditionally non-negative, this
    detects triangle inversion -- the event a vertex-model simulation has to watch for.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 2"]
        Vertex positions in the periodic box.
    hemesh : HeMesh
        Half-edge mesh.
    displacement_fn : Callable
        Periodic displacement function ``(r1, r2) -> r2 - r1 (mod L)``.

    Returns
    -------
    Float[Array, "n_faces"]
        Signed area per face.
    """
    face_hes = hemesh.face_incident
    ab = jax.vmap(displacement_fn)(vertices[hemesh.orig[face_hes]], vertices[hemesh.dest[face_hes]])
    bc = jax.vmap(displacement_fn)(vertices[hemesh.orig[hemesh.nxt[face_hes]]],
                                   vertices[hemesh.dest[hemesh.nxt[face_hes]]])
    # signed area = cross(ab, ac) / 2 with ac = ab + bc
    return jnp.cross(ab, ab + bc) / 2


def get_periodic_triangle_orientations(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_faces"]:
    """Per-face orientation (+1, -1 or 0) under periodic boundary conditions.

    Periodic counterpart of `geometry.get_triangle_orientations`.
    """
    return jnp.sign(get_periodic_oriented_triangle_areas(vertices, hemesh, displacement_fn))


def get_periodic_voronoi_areas_robust(
    vertices: Float[jax.Array, "n_vertices 2"],
    hemesh: HeMesh,
    displacement_fn: Callable[[Float[jax.Array, "2"], Float[jax.Array, "2"]], Float[jax.Array, "2"]],
) -> Float[jax.Array, " n_vertices"]:
    """Mixed (Meyer et al.) Voronoi cell areas under periodic boundary conditions.

    Periodic counterpart of `geometry.get_voronoi_areas_robust`. Unlike
    `get_periodic_voronoi_areas`, which computes the exact circumcentric area, this is
    always positive even on obtuse triangles -- required for a well-posed mass matrix.
    """
    edge_lengths = get_periodic_he_lengths(vertices, hemesh, displacement_fn)
    cot_per_he = get_periodic_cotan_weights_per_he(vertices, hemesh, displacement_fn)
    voronoi_per_tri = (edge_lengths**2 * cot_per_he
                       + edge_lengths[hemesh.nxt]**2 * cot_per_he[hemesh.nxt]) / 8
    tri_areas = get_periodic_triangle_areas(vertices, hemesh, displacement_fn)[hemesh.heface]

    corner_angles = get_periodic_corner_angles(vertices, hemesh, displacement_fn)
    is_obtuse_at_x = corner_angles[hemesh.prv] > jnp.pi/2
    is_obtuse_elsewhere = (corner_angles > jnp.pi/2) | (corner_angles[hemesh.nxt] > jnp.pi/2)

    amixed = jnp.select([is_obtuse_at_x, is_obtuse_elsewhere],
                        [tri_areas / 2, tri_areas / 4], default=voronoi_per_tri)
    amixed = jnp.where(hemesh.is_bdry_he, 0.0, amixed)
    return adj.sum_he_to_vertex_incoming(hemesh, amixed)

