# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb.

# %% auto #0
__all__ = ['displacement_periodic', 'displacement_periodic_twisted', 'get_periodic_edge_vectors', 'get_periodic_he_lengths',
           'get_periodic_face_corners', 'get_periodic_face_centroids', 'get_periodic_voronoi_face_positions',
           'get_periodic_oriented_triangle_areas', 'get_periodic_triangle_orientations']

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #48f4c00d
import jax
import jax.numpy as jnp

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #b486f71a
from jaxtyping import Float 
from collections.abc import Callable

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #c2783a57
from . import trigonometry as trig
from .mesh import HeMesh

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #02987b23
def displacement_periodic(r_1: Float[jax.Array, "2"], r_2: Float[jax.Array, "2"], L: Float[jax.Array, "2"]
                         ) -> Float[jax.Array, "2"]:
    """Return the minimum-image displacement on a rectangular torus.

    IMPORTANT: the minimum-image convention always returns the *shortest* periodic
    image, so it only reproduces the intended mesh edge when every edge is shorter
    than ``min(L)/2``. For a longer edge it silently returns the displacement to a
    different periodic image, giving wrong lengths, areas and angles with no error
    raised. Check with ``get_periodic_he_lengths(...).max() < L.min()/2``. This
    matters for coarse periodic meshes and for a shrinking or strongly sheared box.

    Parameters
    ----------
    r_1, r_2
        Positions in a periodic box.
    L
        Box lengths [L_x, L_y].

    Returns
    -------
    Float[Array, "2"]
        Displacement ``r_2 - r_1`` under the minimum-image convention.
    """
    d = r_2 - r_1
    return d - L * jnp.round(d / L)


def displacement_periodic_twisted(r_1: Float[jax.Array, "2"], r_2: Float[jax.Array, "2"],
                                  L: Float[jax.Array, "2"], s: float
                                  ) -> Float[jax.Array, "2"]:
    """Return the minimum-image displacement on a sheared periodic torus (Lees-Edwards BCs).

    Parameters
    ----------
    r_1, r_2
        Positions in a periodic box.
    L
        Box lengths [L_x, L_y].
    s
        Shear factor: wrapping in y shifts x by ``s * L_x``. This corresponds to vertex
        positions carrying the shear as ``x -> x - s * y``; the opposite sign stretches
        the edges instead of shearing them.

    Notes
    -----
    Inherits the ``max edge < min(L)/2`` precondition of `displacement_periodic`, applied
    *after* the twist. Note ``s`` near 0.5 (or 1.5, ...) violates it for a mesh that has
    not been sheared correspondingly -- a value every Lees-Edwards sweep passes through.
    """
    d = r_2 - r_1
    twist = s * L[0] * jnp.round(d[1] / L[1])
    d = d.at[0].set(d[0] + twist)
    return d - L * jnp.round(d / L)

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #3381813f
def get_periodic_edge_vectors(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                              displacement_fn: Callable,
                              ) -> Float[jax.Array, "n_hes 2"]:
    """Edge vectors ``r_dest - r_orig`` per half-edge, using a periodic displacement function.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 2"]
        Vertex positions in the periodic box.
    hemesh : HeMesh
        Half-edge mesh.
    displacement_fn : Callable
        Periodic displacement function ``(r_1, r_2) -> r_2 - r_1 (mod L)``, e.g.
        `displacement_periodic`.

    Returns
    -------
    Float[Array, "n_hes 2"]
        Displacement vector per half-edge.
    """
    return jax.vmap(displacement_fn)(vertices[hemesh.orig], vertices[hemesh.dest])


def get_periodic_he_lengths(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                            displacement_fn: Callable,
                            ) -> Float[jax.Array, " n_hes"]:
    """Get lengths of half-edges using a periodic displacement function.

    This is the periodic counterpart of `geometry.get_he_length`, and the entry point to
    all intrinsic geometry under periodic boundary conditions: pass the result to any
    ``*_intrinsic`` function of the `geometry` or `linops` modules.
    """
    return trig.safe_norm(get_periodic_edge_vectors(vertices, hemesh, displacement_fn))

# %% ../nbs/src/05b_geometric_quantities_periodic_bcs.ipynb #periodic-pos
def get_periodic_face_corners(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                              displacement_fn: Callable,
                              ) -> Float[jax.Array, "n_faces 3 2"]:
    """Vertex positions of each face, unwrapped into a single periodic image.

    The first corner is the origin vertex of the face's incident half-edge and keeps its
    position in the box; the other two are placed relative to it by following displacement
    vectors, so that the triangle is contiguous even if it wraps around the periodic
    boundary. The positions are therefore NOT wrapped back into the box.

    Corners are ordered as in `mesh.HeMesh.faces`, so the result can be used like
    ``vertices[hemesh.faces]`` in the non-periodic case.

    Parameters
    ----------
    vertices : Float[Array, "n_vertices 2"]
        Vertex positions in the periodic box.
    hemesh : HeMesh
        Half-edge mesh.
    displacement_fn : Callable
        Periodic displacement function ``(r_1, r_2) -> r_2 - r_1 (mod L)``.

    Returns
    -------
    Float[Array, "n_faces 3 2"]
        Unwrapped positions of the three corners of each face.
    """
    face_hes = hemesh.face_incident
    edge_vectors = get_periodic_edge_vectors(vertices, hemesh, displacement_fn)
    a = vertices[hemesh.orig[face_hes]]
    b = a + edge_vectors[face_hes]
    c = b + edge_vectors[hemesh.nxt[face_hes]]
    return jnp.stack([a, b, c], axis=1)


def get_periodic_face_centroids(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                displacement_fn: Callable,
                                ) -> Float[jax.Array, "n_faces 2"]:
    """Face centroids (barycenters) using a periodic displacement function.

    Returned in the periodic image of their own face, not wrapped back into the box
    (see `get_periodic_face_corners`).
    """
    return get_periodic_face_corners(vertices, hemesh, displacement_fn).mean(axis=1)


def get_periodic_voronoi_face_positions(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                        displacement_fn: Callable,
                                        ) -> Float[jax.Array, "n_faces 2"]:
    """Voronoi dual positions (circumcenters) using a periodic displacement function.

    The circumcenter is computed in intrinsic barycentric coordinates
    (`trigonometry.get_circumcenter_from_lengths`) from the periodic edge lengths, then
    mapped back onto the unwrapped face corners.

    Like `get_periodic_face_centroids`, the returned positions are in the periodic image
    of their own face and are not wrapped back into the box. Do not feed them to
    `geometry.get_dual_he_length` or `mesh.cellplot`, which assume unwrapped Euclidean
    coordinates -- for dual edge lengths use `geometry.get_voronoi_edge_lengths_intrinsic`.
    """
    face_hes = hemesh.face_incident
    he_lengths = get_periodic_he_lengths(vertices, hemesh, displacement_fn)
    # sides opposite the corners (a, b, c) are the half-edges (nxt, prv, face_incident)
    barycentric = jax.vmap(trig.get_circumcenter_from_lengths)(he_lengths[hemesh.nxt[face_hes]],
                                                               he_lengths[hemesh.prv[face_hes]],
                                                               he_lengths[face_hes],)
    corners = get_periodic_face_corners(vertices, hemesh, displacement_fn)
    return jnp.einsum('fi,fij->fj', barycentric, corners)


def get_periodic_oriented_triangle_areas(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                         displacement_fn: Callable,
                                         ) -> Float[jax.Array, " n_faces"]:
    """Signed triangle areas under periodic boundary conditions.

    Positive for counter-clockwise (positively oriented) triangles, negative for inverted
    ones. Unlike the intrinsic `geometry.get_triangle_areas_intrinsic`, which goes through
    Heron's formula and is therefore unconditionally non-negative, this detects triangle
    inversion -- the event a vertex-model simulation has to watch for.
    """
    corners = get_periodic_face_corners(vertices, hemesh, displacement_fn)
    return jax.vmap(trig.get_oriented_triangle_area)(*corners.transpose((1, 0, 2)))


def get_periodic_triangle_orientations(vertices: Float[jax.Array, "n_vertices 2"], hemesh: HeMesh,
                                       displacement_fn: Callable,
                                       ) -> Float[jax.Array, " n_faces"]:
    """Per-face orientation (+1, -1 or 0) under periodic boundary conditions.

    Periodic counterpart of `geometry.get_triangle_orientations`.
    """
    return jnp.sign(get_periodic_oriented_triangle_areas(vertices, hemesh, displacement_fn))
