# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/08_simulation.ipynb.

# %% auto #0
__all__ = ['State', 'Log', 'simulate', 'chunked_simulate']

# %% ../nbs/src/08_simulation.ipynb #9bf6bfbe
import jax
import jax.numpy as jnp

# %% ../nbs/src/08_simulation.ipynb #3c98cf5f
from collections.abc import Callable
from typing import TypeVar

from jaxtyping import Float

# %% ../nbs/src/08_simulation.ipynb #b22edcce
State = TypeVar("State")
Log = TypeVar("Log")

# %% ../nbs/src/08_simulation.ipynb #f5720a3b
def simulate(step_fn: Callable[[State, Float[jax.Array, ""]], State],
             measure_fn: Callable[[State], Log],
             init: State,
             timepoints: Float[jax.Array, " n_steps"],
             ) -> tuple[State, Log]:
    """Run a simulation by scanning `step_fn` over `timepoints`, logging via `measure_fn`.

    Wraps `jax.lax.scan`. Fully JIT- and vmap-compatible.

    Parameters
    ----------
    step_fn : (State, jax.Array) -> State
        Advances the simulation state from the current time to the next time.
        Signature: ``step_fn(state, next_time) -> new_state``.
    measure_fn : (State) -> Log
        Extracts measurements from the current state.
        Signature: ``measure_fn(state) -> log``.
        The returned pytree is stacked along axis 0 across all time steps.
    init : State
        Initial simulation state (any JAX pytree).
    timepoints : jax.Array, shape (n_steps,)
        Time points to step through. `step_fn` receives consecutive pairs.

    Returns
    -------
    final_state : State
        The simulation state after the last time step.
    logs : Log
        Pytree of measurements, with each leaf having an extra leading axis of
        size ``n_steps``.
    """
    def _scan_fn(state: State, t_next: jax.Array) -> tuple[State, Log]:
        new_state = step_fn(state, t_next)
        log = measure_fn(new_state)
        return new_state, log

    return jax.lax.scan(_scan_fn, init, timepoints)

# %% ../nbs/src/08_simulation.ipynb #fa9f0374
def chunked_simulate(step_fn: Callable[[State, Float[jax.Array, ""]], State],
                     measure_fn: Callable[[State], Log],
                     init: State,
                     timepoints: Float[jax.Array, " n_steps"],
                     chunk_size: int,
                     on_chunk: Callable[[State, Log, int], None] | None = None,
                     ) -> tuple[State, Log]:
    """Run a simulation in chunks, with an optional callback between chunks.

    Each chunk is executed as a single `jax.lax.scan`. Between chunks, the
    ``on_chunk`` callback is called in Python, enabling checkpointing, progress
    reporting, or early stopping.

    Parameters
    ----------
    step_fn : (State, jax.Array) -> State
        Advances the simulation state. Same as :func:`simulate`.
    measure_fn : (State) -> Log
        Extracts measurements. Same as :func:`simulate`.
    init : State
        Initial simulation state.
    timepoints : jax.Array, shape (n_steps,)
        Time points to step through.
    chunk_size : int
        Number of time steps per chunk.
    on_chunk : (State, Log, int) -> None, optional
        Callback invoked after each chunk with ``(state, chunk_logs, chunk_index)``.
        Runs in Python (not JIT'd), so it can do I/O.

    Returns
    -------
    final_state : State
        The simulation state after the last time step.
    logs : Log
        Concatenated measurements from all chunks. Each leaf has a leading axis
        of size ``n_steps``.
    """
    n_steps = timepoints.shape[0]
    all_logs = []
    state = init

    # Split timepoints into chunks. The last chunk may be shorter.
    n_full_chunks = n_steps // chunk_size
    remainder = n_steps % chunk_size

    for i in range(n_full_chunks):
        chunk_tp = timepoints[i * chunk_size : (i + 1) * chunk_size]
        state, chunk_logs = simulate(step_fn, measure_fn, state, chunk_tp)
        all_logs.append(chunk_logs)
        if on_chunk is not None:
            on_chunk(state, chunk_logs, i)

    if remainder > 0:
        chunk_tp = timepoints[n_full_chunks * chunk_size:]
        state, chunk_logs = simulate(step_fn, measure_fn, state, chunk_tp)
        all_logs.append(chunk_logs)
        if on_chunk is not None:
            on_chunk(state, chunk_logs, n_full_chunks)

    # Concatenate logs along the time axis
    logs = jax.tree.map(lambda *arrs: jnp.concatenate(arrs, axis=0), *all_logs)
    return state, logs
