# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/03_topological_modifications.ipynb.

# %% auto #0
__all__ = ['flip_edge', 'can_flip_edge', 'flip_by_id', 'flip_all', 'flip_n_shortest', 'remap_inds_removal_forward',
           'remap_inds_removal_reverse', 'MeshReindexMap', 'can_collapse_edge', 'collapse_edge', 'can_split_vertex',
           'split_vertex']

# %% ../nbs/src/03_topological_modifications.ipynb #03827561
import numpy as np
import igl

# %% ../nbs/src/03_topological_modifications.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp

# %% ../nbs/src/03_topological_modifications.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Int, Bool 
from typing import Any

import dataclasses

import functools

# %% ../nbs/src/03_topological_modifications.ipynb #cef3ff0a
from . import trigonometry as trig
from .triangular import TriMesh
from .mesh import HeMesh, GeomMesh
import triangulax.mesh as msh
from . import geometry as geom

# %% ../nbs/src/03_topological_modifications.ipynb #2a1c1f7c-4c6e-4312-9820-cf497590c452
@functools.partial(jax.jit, static_argnames=['check_boundary'])
def flip_edge(hemesh: HeMesh, e: Int[jax.Array, ""], check_boundary: bool = False) -> HeMesh:
    """
    Flip half-edge e in a half-edge mesh.
    
    See https://jerryyin.info/geometry-processing-algorithms/half-edge/. The algorithm
    is slightly modified since we keep track of the origin and destination of a half-edge,
    and use arrays instead of pointers. Returns a new HeMesh, does not modify in-place.

    Does not check whether the flip produces a valid mesh. Use `can_flip_edge` to check first.
    """
    if check_boundary:
        assert (hemesh.heface[e] !=-1 and hemesh.heface[hemesh.twin[e]] != -1), "Cannot flip boundary edge"

    # identify relevant elements
    e5 = hemesh.prv[e]
    e4 = hemesh.nxt[e]
    twin = hemesh.twin[e]
    e1 = hemesh.prv[twin] 
    e0 = hemesh.nxt[twin] 

    # make sure there's no vertex or face references to e or twin
    incident = hemesh.incident.at[jnp.array([hemesh.orig[e], hemesh.orig[twin]])].set(
        jnp.array([hemesh.twin[e5], hemesh.twin[e1]]))
    face_incident = hemesh.face_incident.at[jnp.array([hemesh.heface[e], hemesh.heface[twin]])].set(
        jnp.array([e5, e1])) # e1, e5 don't change face

    # update the data structure to do the T1
    nxt = hemesh.nxt.at[jnp.array([e, twin])].set(jnp.array([e5, e1]))
    prv = hemesh.prv.at[jnp.array([e, twin])].set(jnp.array([e0, e4]))
    orig = hemesh.orig.at[jnp.array([e, twin])].set(jnp.array([hemesh.orig[e1], hemesh.orig[e5]]) )
    dest = hemesh.dest.at[jnp.array([e, twin])].set(jnp.array([hemesh.dest[e4], hemesh.dest[e0]]))

    nxt = nxt.at[jnp.array([e0, e1, e4, e5])].set(jnp.array([e, e4, twin, e0]) )
    prv = prv.at[jnp.array([e0, e1, e4, e5])].set(jnp.array([e5, twin, e1, e]) )
    heface = hemesh.heface.at[jnp.array([e0, e4])].set(jnp.array([hemesh.heface[e5], hemesh.heface[e1]]))

    return HeMesh(incident, orig, dest, hemesh.twin, nxt, prv, heface, face_incident, hemesh.inf_vertices)

# %% ../nbs/src/03_topological_modifications.ipynb #c519ff06
@jax.jit
def can_flip_edge(hemesh: HeMesh, e: Int[jax.Array, ""]) -> Bool[jax.Array, ""]:
    """
    Check whether flipping half-edge e would produce a valid mesh.
    
    An edge can be flipped if it is interior (not boundary) and the two opposite vertices
    are not already connected (which would create a duplicate edge).
    """
    twin = hemesh.twin[e]
    is_interior = (hemesh.heface[e] != -1) & (hemesh.heface[twin] != -1)
    # opposite vertices after flip
    v_opp_1 = hemesh.dest[hemesh.nxt[e]]     # = orig of prv[e]
    v_opp_2 = hemesh.dest[hemesh.nxt[twin]]   # = orig of prv[twin]
    # check that v_opp_1 and v_opp_2 are not already connected
    already_connected = jnp.any((hemesh.orig == v_opp_1) & (hemesh.dest == v_opp_2))
    return is_interior & ~already_connected

# %% ../nbs/src/03_topological_modifications.ipynb #242d6ee1-d553-45fc-852f-a80fbb4a589a
@jax.jit
def flip_by_id(hemesh: HeMesh, ids: Int[jax.Array, " flips"], to_flip: Bool[jax.Array, " flips"]) -> HeMesh:
    """Flip half-edges from ids array where to_flip is True. Wraps flip_edge."""
    def scan_fun(h, x):
        return jax.lax.cond(x[1], lambda hh: flip_edge(hh, x[0]), lambda hh: hh, h), None
    xs = jnp.stack([ids, to_flip], axis=1)  
    flipped_hemesh, _ = jax.lax.scan(scan_fun, init=hemesh, xs=xs)
    return flipped_hemesh

@jax.jit
def flip_all(hemesh: HeMesh, to_flip: Bool[jax.Array, " n_hes"]) -> HeMesh:
    """
    Flip all (unique) half-edges where to_flip is True in a half-edge mesh. Wraps flip_edge.
    
    Note: scans over *all* half-edges, which can be slow for large meshes. See `flip_n_shortest`
    for a more efficient alternative that only scans over a fixed number of candidate edges.
    """
    def scan_fun(h, e):
        return jax.lax.cond(to_flip[e] & hemesh.is_unique[e],
                            lambda hh: flip_edge(hh, e), lambda hh: hh, h), None
    flipped_hemesh, _ = jax.lax.scan(scan_fun, init=hemesh, xs=jnp.arange(hemesh.n_hes) )
    return flipped_hemesh

# %% ../nbs/src/03_topological_modifications.ipynb #6f857122
@functools.partial(jax.jit, static_argnames=['max_flips'])
def flip_n_shortest(hemesh: HeMesh, edge_lengths: Int[jax.Array, " n_hes"],
                    threshold: float, max_flips: int = 10) -> tuple[HeMesh, Bool[jax.Array, " n_hes"]]:
    """
    Flip up to `max_flips` shortest edges below `threshold`.

    Sorts edges by length, selects the `max_flips` shortest unique, non-boundary candidates,
    and flips those below `threshold`. Much faster than `flip_all` for large meshes.

    Parameters
    ----------
    hemesh : HeMesh
        The half-edge mesh.
    edge_lengths : Float[Array, " n_hes"]
        Per-half-edge edge lengths (e.g., dual/Voronoi edge lengths).
    threshold : float
        Edges shorter than this are flipped.
    max_flips : int
        Maximum number of edges to consider. Static argument (changing it triggers recompilation).

    Returns
    -------
    hemesh : HeMesh
        The mesh after flipping.
    did_flip : Bool[Array, " n_hes"]
        Boolean mask of half-edges that were flipped.
    """
    lengths = jnp.where(hemesh.is_unique & ~hemesh.is_bdry_edge, edge_lengths, jnp.inf)
    ids = jnp.argsort(lengths)[:max_flips]
    hemesh_new = flip_by_id(hemesh, ids, lengths[ids] < threshold)
    did_flip = (lengths < threshold) & (lengths <= lengths[ids[max_flips - 1]])
    return hemesh_new, did_flip

# %% ../nbs/src/03_topological_modifications.ipynb #d2df40a4
def remap_inds_removal_forward(N: int, removed: Int[jax.Array, " n_removed"]) -> Int[jax.Array, " N"]:
    """Remap indices after removal. Returns array arr[i] = i - (removed < i).sum()."""
    remap = jnp.arange(N)
    return remap - jnp.searchsorted(jnp.sort(removed), remap, side='left')  # left


def remap_inds_removal_reverse(N: int, removed: Int[jax.Array, " n_removed"]) -> Int[jax.Array, " N-n_removed"]:
    """Remap indices after removal. Reverse of remap_inds_removal_forward."""
    remap = jnp.arange(N)
    return jnp.delete(remap, removed, assume_unique_indices=True)


# %% ../nbs/src/03_topological_modifications.ipynb #05455739
@jax.tree_util.register_dataclass
@dataclasses.dataclass(frozen=True)
class MeshReindexMap:
    """Old↔new index maps produced by topology-changing operations."""
    v_forward: Int[jax.Array, " n_vertices_old"]
    v_reverse: Int[jax.Array, " n_vertices_new"]
    f_forward: Int[jax.Array, " n_faces_old"]
    f_reverse: Int[jax.Array, " n_faces_new"]
    he_forward: Int[jax.Array, " n_hes_old"]
    he_reverse: Int[jax.Array, " n_hes_new"]
    info: dict[str, Any] = dataclasses.field(default_factory=dict, metadata=dict(static=True))


# %% ../nbs/src/03_topological_modifications.ipynb #43101a21
@jax.jit
def can_collapse_edge(hemesh: HeMesh, e: Int[jax.Array, ""]) -> Bool[jax.Array, ""]:
    """
    Check whether collapsing half-edge e would produce a valid mesh (link condition).
    
    An edge can be collapsed if it is interior and the two endpoint vertices share exactly
    two common neighbors (the opposite vertices of the two adjacent faces). This is the
    discrete "link condition" that ensures the collapse preserves manifoldness.
    """
    t = hemesh.twin[e]
    is_interior = (hemesh.heface[e] != -1) & (hemesh.heface[t] != -1)
    # compute neighbor sets via orig/dest
    v0, v1 = hemesh.orig[e], hemesh.dest[e]
    nbrs_v0 = jnp.where(hemesh.orig == v0, hemesh.dest, -1)
    nbrs_v1 = jnp.where(hemesh.orig == v1, hemesh.dest, -1)
    # count common neighbors (a neighbor n is common if it appears in both nbr sets)
    is_common = jnp.any(nbrs_v0[:, None] == nbrs_v1[None, :], axis=1) & (nbrs_v0 != -1)
    n_common = jnp.sum(is_common)
    return is_interior & (n_common == 2)

# %% ../nbs/src/03_topological_modifications.ipynb #67afc0b1
@functools.partial(jax.jit, static_argnames=['check_boundary']) 
def collapse_edge(hemesh: HeMesh, e: int, check_boundary=False
                  ) -> tuple[HeMesh, MeshReindexMap]:
    """
    Collapse half-edge e in a half-edge mesh. Keeps the origin vertex of e.
        
    Returns a new HeMesh (does not modify in-place), and a MeshReindexMap for remapping
    vertex, half-edge, and face indices from the original mesh to the new mesh.

    Does not check whether the collapse produces a valid mesh. Use `can_collapse_edge` to check first.

    JIT-compatible, but calling with different numbers of vertices/edges/faces will cause recompilation.
    """

    if check_boundary:
        assert not hemesh.is_bdry_edge[e] and not hemesh.is_inf_he[e], "Interior edges only"

    # identify relevant elements
    t = hemesh.twin[e]

    # make sure there's no vertex references to e or twin
    incident = hemesh.incident.at[jnp.array([hemesh.orig[e], # v1 
                                             hemesh.orig[hemesh.prv[e]], # v2
                                             hemesh.orig[hemesh.prv[t]]])].set( # v4
                                  jnp.array([hemesh.twin[hemesh.prv[e]],
                                             hemesh.twin[hemesh.nxt[e]],
                                             hemesh.twin[hemesh.nxt[t]]]))
    # re-twin the half-edges
    twin = hemesh.twin.at[jnp.array([hemesh.twin[hemesh.prv[e]],
                                     hemesh.twin[hemesh.nxt[e]], 
                                     hemesh.twin[hemesh.prv[t]],
                                     hemesh.twin[hemesh.nxt[t]]])].set( 
                          jnp.array([hemesh.twin[hemesh.nxt[e]],
                                     hemesh.twin[hemesh.prv[e]],
                                     hemesh.twin[hemesh.nxt[t]],
                                     hemesh.twin[hemesh.prv[t]]]))
    # edit orign and dest for all hes in/out of v3
    orig = jnp.where(hemesh.orig==hemesh.dest[e], hemesh.orig[e], hemesh.orig)
    dest = jnp.where(hemesh.dest==hemesh.dest[e], hemesh.orig[e], hemesh.dest)

    # delete the elements
    v_delete = jnp.array([hemesh.dest[e]])
    hes_delete = jnp.array([e, hemesh.nxt[e], hemesh.prv[e],
                            t, hemesh.nxt[t], hemesh.prv[t]])
    fs_delete =  jnp.array([hemesh.heface[e], hemesh.heface[t]])
    incident = jnp.delete(incident, v_delete, assume_unique_indices=True)
    face_incident = jnp.delete(hemesh.face_incident, fs_delete, assume_unique_indices=True)
    
    def delete_he(arr): return jnp.delete(arr, hes_delete, assume_unique_indices=True)
    orig, dest = (delete_he(orig), delete_he(dest))
    twin = delete_he(twin)
    nxt, prv = (delete_he(hemesh.nxt), delete_he(hemesh.prv))
    heface = delete_he(hemesh.heface)

    # index remapping: identity for v < hemesh.dest[e], v-> v-1 for
    remap_v = remap_inds_removal_forward(hemesh.n_vertices, v_delete)
    remap_he = remap_inds_removal_forward(hemesh.n_hes, hes_delete)  
    remap_f = remap_inds_removal_forward(hemesh.n_faces, fs_delete)

    index_map = MeshReindexMap(v_forward=remap_v,
                               v_reverse=remap_inds_removal_reverse(hemesh.n_vertices, v_delete),
                               f_forward=remap_f,
                               f_reverse=remap_inds_removal_reverse(hemesh.n_faces, fs_delete),
                               he_forward=remap_he,
                               he_reverse=remap_inds_removal_reverse(hemesh.n_hes, hes_delete),
                               info={"operation": "collapse_edge", "collapsed_edge": e})
    
    inf_vertices = tuple(int(remap_v[v]) for v in hemesh.inf_vertices)

    # special case: boundary hes need "-1" face
    is_bdry_he = jnp.delete(hemesh.heface == -1, hes_delete, assume_unique_indices=True)
    heface = jnp.where(is_bdry_he, -1, remap_f[heface])

    new_hemesh = HeMesh(incident=remap_he[incident], orig=remap_v[orig], dest=remap_v[dest],
                        twin=remap_he[twin], nxt=remap_he[nxt], prv=remap_he[prv],
                        heface=heface, face_incident=remap_he[face_incident], inf_vertices=inf_vertices)

    return new_hemesh, index_map

# %% ../nbs/src/03_topological_modifications.ipynb #3a3a3f64
def can_split_vertex(hemesh: HeMesh, e1: int, e2: int) -> bool:
    """
    Check whether splitting a vertex along half-edges e1 and e2 is valid.
    
    Both half-edges must originate from the same vertex, and both must be on interior faces.
    """
    return (hemesh.orig[e1] == hemesh.orig[e2] and
            hemesh.heface[e1] != -1 and hemesh.heface[e2] != -1 and e1 != e2)

# %% ../nbs/src/03_topological_modifications.ipynb #8a3a4335
def split_vertex(hemesh: HeMesh, e1: int, e2: int, check_args: bool=False) -> tuple[HeMesh, MeshReindexMap]:
    """
    Split a vertex into two along a "splitting axis" given by two half-edges originating at that vertex.
    
    New vertex inserted at origin of e2. The new vertex will be the final one in the array.

    This function is not JIT-compatible, since it depends on iterating around the vertex to update origins/destinations.
    """
    if check_args:
        assert hemesh.orig[e1]==hemesh.orig[e2] and not hemesh.heface[e1]==-1 and not hemesh.heface[e2]==-1, "invalid half edges"

    # create 1 new vertex, 6 new half-edges, and 2 new faces. By convention, at the end of the arrays
    incident = jnp.pad(hemesh.incident, (0, 1))
    face_incident = jnp.pad(hemesh.face_incident, (0, 2))
    orig, dest, twin, nxt, prv, heface = [jnp.pad(arr, (0, 6))
                                         for arr in [hemesh.orig, hemesh.dest, hemesh.twin, hemesh.nxt, hemesh.prv, hemesh.heface]]

    # the new elements are appended at the end
    vnew = hemesh.n_vertices
    fnew_1, fnew_2 = hemesh.n_faces, hemesh.n_faces+1 # faces of triangle of twin[e1] and triangle of twin[e2]
    enew_1, enew_2, enew_3 = hemesh.n_hes, hemesh.n_hes+1, hemesh.n_hes+2 # fnew_1, enew_1 is twin[e1]
    enew_4, enew_5, enew_6 = hemesh.n_hes+3, hemesh.n_hes+4, hemesh.n_hes+5 # fnew_2, enew_4 is twin[e2]

    # set incidents for new mesh elements
    incident = incident.at[vnew].set(e2)
    incident = incident.at[hemesh.orig[e1]].set(e1)  # ensure original vertex still points to a valid outgoing he
    heface = heface.at[jnp.array([enew_1, enew_2, enew_3])].set(fnew_1)
    heface = heface.at[jnp.array([enew_4, enew_5, enew_6])].set(fnew_2)
    face_incident = face_incident.at[jnp.array([fnew_1, fnew_2])].set(jnp.array([enew_1, enew_4]))

    # origin and destination of new half-edges
    orig = orig.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([hemesh.dest[e1], hemesh.orig[e1], vnew]))
    orig = orig.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([hemesh.dest[e2], vnew, hemesh.orig[e1]]))
    dest = dest.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([hemesh.orig[e1], vnew, hemesh.dest[e1]]))
    dest = dest.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([vnew, hemesh.orig[e1], hemesh.dest[e2]]))
    
    # nxt, prv, twin of new half-edges
    nxt = nxt.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([enew_2, enew_3, enew_1]))
    nxt = nxt.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([enew_5, enew_6, enew_4]))
    prv = prv.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([enew_3, enew_1, enew_2]))
    prv = prv.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([enew_6, enew_4, enew_5]))
    
    twin = twin.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([e1, enew_5, hemesh.twin[e1]]))
    twin = twin.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([e2, enew_2, hemesh.twin[e2]]))
    twin = twin.at[jnp.array([e1, e2])].set(jnp.array([enew_1, enew_4]))
    twin = twin.at[jnp.array([hemesh.twin[e1], hemesh.twin[e2]])].set(jnp.array([enew_3, enew_6]))

    # finally, need to update the origin and destination of half-edges into the "split" vertex.
    # iterate around the vertex from e2 to e1 to get the ones we need to update
    outgoing = [e2]
    while True:
        next_edge = hemesh.twin[hemesh.prv[outgoing[-1]]]
        if next_edge == e1:
            break
        outgoing.append(next_edge)
    outgoing = jnp.array(outgoing)
    orig = orig.at[outgoing].set(vnew)
    dest = dest.at[hemesh.prv[outgoing]].set(vnew)

    # no need to update the indices, since we appended the mesh elements at the very end
    new_hemesh = HeMesh(incident=incident, orig=orig, dest=dest, twin=twin, nxt=nxt, prv=prv,
                        heface=heface, face_incident=face_incident, inf_vertices=hemesh.inf_vertices)
    
    # need to find the "parents" of the new mesh elements
    v_reverse = jnp.arange(hemesh.n_vertices+1).at[vnew].set(hemesh.orig[e1])
    f_reverse = jnp.arange(hemesh.n_faces+2).at[jnp.array([fnew_1, fnew_2])].set(
                                                jnp.array([hemesh.heface[e1], hemesh.heface[e2]]))
    he_reverse = jnp.arange(hemesh.n_hes+6)
    he_reverse = he_reverse.at[jnp.array([enew_1, enew_2, enew_3])].set(
                              jnp.array([e1, e1, hemesh.twin[e1]]))
    he_reverse = he_reverse.at[jnp.array([enew_4, enew_5, enew_6])].set(
                              jnp.array([e2, e2, hemesh.twin[e2]]))
    index_map = MeshReindexMap(v_forward=jnp.arange(hemesh.n_vertices),
                               v_reverse=v_reverse,
                               f_forward=jnp.arange(hemesh.n_faces),
                               f_reverse=f_reverse,
                               he_forward=jnp.arange(hemesh.n_hes),
                               he_reverse=he_reverse,
                               info={"operation": "split_vertex", "split_edges": (e1, e2), "new_vertex": vnew})

    return new_hemesh, index_map
