# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/03_topological_modifications.ipynb.

# %% auto #0
__all__ = ['flip_edge', 'can_flip_edge', 'flip_by_id', 'flip_all', 'flip_n_shortest', 'remap_inds_removal_forward',
           'remap_inds_removal_reverse', 'MeshReindexMap', 'can_collapse_edge', 'collapse_edge', 'can_split_vertex',
           'split_vertex']

# %% ../nbs/src/03_topological_modifications.ipynb #03827561
#| export


# %% ../nbs/src/03_topological_modifications.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp

# %% ../nbs/src/03_topological_modifications.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Int, Bool 
from typing import Any

import dataclasses


# %% ../nbs/src/03_topological_modifications.ipynb #cef3ff0a
from .mesh import HeMesh


# %% ../nbs/src/03_topological_modifications.ipynb #2a1c1f7c-4c6e-4312-9820-cf497590c452
def flip_edge(hemesh: HeMesh, e: Int[jax.Array, ""] | int) -> HeMesh:
    """
    Flip half-edge e in a half-edge mesh.

    See https://jerryyin.info/geometry-processing-algorithms/half-edge/. The algorithm
    is slightly modified since we keep track of the origin and destination of a half-edge,
    and use arrays instead of pointers. Returns a new HeMesh, does not modify in-place.

    Warning: does NOT check whether the flip produces a valid mesh. Flipping a boundary
    edge silently corrupts the connectivity, because heface == -1 wraps around and
    overwrites the last face. Always screen with `can_flip_edge` first; the batch
    helpers `flip_all` / `flip_by_id` / `flip_n_shortest` do this for you.

    Not jitted: wrap in `jax.jit` yourself if desired (`e` may be a traced value).
    """
    # all index arrays are built at the mesh's own integer dtype: `e` may be int64
    # (e.g. from jnp.arange under jax_enable_x64) while the mesh arrays are int32,
    # and scattering int64 values into an int32 array is a JAX error-in-waiting.
    idx = lambda *xs: jnp.array(xs, dtype=hemesh.orig.dtype)

    # identify relevant elements
    e5 = hemesh.prv[e]
    e4 = hemesh.nxt[e]
    twin = hemesh.twin[e]
    e1 = hemesh.prv[twin]
    e0 = hemesh.nxt[twin]

    # make sure there's no vertex or face references to e or twin
    incident = hemesh.incident.at[idx(hemesh.orig[e], hemesh.orig[twin])].set(
        idx(hemesh.twin[e5], hemesh.twin[e1]))
    face_incident = hemesh.face_incident.at[idx(hemesh.heface[e], hemesh.heface[twin])].set(
        idx(e5, e1)) # e1, e5 don't change face

    # update the data structure to do the T1
    nxt = hemesh.nxt.at[idx(e, twin)].set(idx(e5, e1))
    prv = hemesh.prv.at[idx(e, twin)].set(idx(e0, e4))
    orig = hemesh.orig.at[idx(e, twin)].set(idx(hemesh.orig[e1], hemesh.orig[e5]))
    dest = hemesh.dest.at[idx(e, twin)].set(idx(hemesh.dest[e4], hemesh.dest[e0]))

    nxt = nxt.at[idx(e0, e1, e4, e5)].set(idx(e, e4, twin, e0))
    prv = prv.at[idx(e0, e1, e4, e5)].set(idx(e5, twin, e1, e))
    heface = hemesh.heface.at[idx(e0, e4)].set(idx(hemesh.heface[e5], hemesh.heface[e1]))

    return HeMesh(incident, orig, dest, hemesh.twin, nxt, prv, heface, face_incident, hemesh.inf_vertices)

# %% ../nbs/src/03_topological_modifications.ipynb #c519ff06
def can_flip_edge(hemesh: HeMesh, e: Int[jax.Array, ""] | int) -> Bool[jax.Array, ""]:
    """
    Check whether flipping half-edge e would produce a valid mesh.

    An edge can be flipped if it is interior (not boundary) and the two opposite vertices
    are not already connected (which would create a duplicate edge).

    Uses `hemesh.is_bdry_edge`, so boundaries are detected under both conventions
    (heface == -1 and vertices at infinity).
    """
    twin = hemesh.twin[e]
    is_interior = ~hemesh.is_bdry_edge[e]
    # opposite vertices after flip
    v_opp_1 = hemesh.dest[hemesh.nxt[e]]     # = orig of prv[e]
    v_opp_2 = hemesh.dest[hemesh.nxt[twin]]   # = orig of prv[twin]
    # check that v_opp_1 and v_opp_2 are not already connected
    already_connected = jnp.any((hemesh.orig == v_opp_1) & (hemesh.dest == v_opp_2))
    return is_interior & ~already_connected


# %% ../nbs/src/03_topological_modifications.ipynb #242d6ee1-d553-45fc-852f-a80fbb4a589a
def flip_by_id(hemesh: HeMesh, ids: Int[jax.Array, " flips"], to_flip: Bool[jax.Array, " flips"]) -> HeMesh:
    """Flip half-edges from ids array where to_flip is True. Wraps flip_edge.

    Flips are applied *sequentially*, and each one is re-checked against the current
    (partially flipped) mesh with `can_flip_edge`, since an earlier flip can invalidate
    a later one. Edges that fail the check are skipped.
    """
    def scan_fun(h, x):
        e = x[0]
        do = (x[1] != 0) & can_flip_edge(h, e)
        return jax.lax.cond(do, lambda hh: flip_edge(hh, e), lambda hh: hh, h), None
    xs = jnp.stack([ids, to_flip], axis=1)
    flipped_hemesh, _ = jax.lax.scan(scan_fun, init=hemesh, xs=xs)
    return flipped_hemesh


def flip_all(hemesh: HeMesh, to_flip: Bool[jax.Array, " n_hes"],
             max_flips: int | None = None) -> HeMesh:
    """
    Flip all (unique) half-edges where to_flip is True in a half-edge mesh. Wraps flip_edge.

    Flips are applied *sequentially*, and each one is re-checked against the current
    (partially flipped) mesh with `can_flip_edge`: `to_flip` is evaluated against the
    original mesh, but an earlier flip can make a later one invalid (the two opposite
    vertices may have become adjacent). Without the re-check this silently produces
    non-manifold meshes.

    Parameters
    ----------
    hemesh : HeMesh
        The half-edge mesh.
    to_flip : Bool[Array, " n_hes"]
        Mask of half-edges to flip. Only unique half-edges (`hemesh.is_unique`) are
        considered, so marking the twin instead has no effect.
    max_flips : int | None
        If None (default), scan over *all* half-edges. Cost is then O(n_hes^2) and this
        dominates for large meshes. If given, scan only the `max_flips` lowest-indexed
        candidates, which is much faster. `max_flips` determines the scan length and
        hence array shapes, so under `jax.jit` it must be a static argument
        (`jax.jit(flip_all, static_argnames=['max_flips'])`).

    Returns
    -------
    HeMesh
        The mesh after flipping.
    """
    candidates = to_flip & hemesh.is_unique
    if max_flips is None:
        ids = jnp.arange(hemesh.n_hes)
    else:
        # candidate indices first, padded with the out-of-range sentinel n_hes
        ids = jnp.sort(jnp.where(candidates, jnp.arange(hemesh.n_hes), hemesh.n_hes))[:max_flips]

    def scan_fun(h, e):
        e_safe = jnp.minimum(e, hemesh.n_hes - 1)
        do = (e < hemesh.n_hes) & candidates[e_safe] & can_flip_edge(h, e_safe)
        return jax.lax.cond(do, lambda hh: flip_edge(hh, e_safe), lambda hh: hh, h), None
    flipped_hemesh, _ = jax.lax.scan(scan_fun, init=hemesh, xs=ids)
    return flipped_hemesh


# %% ../nbs/src/03_topological_modifications.ipynb #6f857122
def flip_n_shortest(hemesh: HeMesh, edge_lengths: Int[jax.Array, " n_hes"],
                    threshold: float, max_flips: int = 10) -> tuple[HeMesh, Bool[jax.Array, " n_hes"]]:
    """
    Flip up to `max_flips` shortest edges below `threshold`.

    Sorts edges by length, selects the `max_flips` shortest unique, non-boundary candidates,
    and flips those below `threshold`. Much faster than `flip_all` for large meshes.

    Parameters
    ----------
    hemesh : HeMesh
        The half-edge mesh.
    edge_lengths : Float[Array, " n_hes"]
        Per-half-edge edge lengths (e.g., dual/Voronoi edge lengths).
    threshold : float
        Edges shorter than this are flipped.
    max_flips : int
        Maximum number of edges to consider. Determines the scan length and hence array
        shapes, so under `jax.jit` it must be a static argument
        (`jax.jit(flip_n_shortest, static_argnames=['max_flips'])`).

    Returns
    -------
    hemesh : HeMesh
        The mesh after flipping.
    did_flip : Bool[Array, " n_hes"]
        Boolean mask of half-edges that were actually flipped (both the half-edge and
        its twin are marked).
    """
    lengths = jnp.where(hemesh.is_unique & ~hemesh.is_bdry_edge, edge_lengths, jnp.inf)
    ids = jnp.argsort(lengths)[:max_flips]
    hemesh_new = flip_by_id(hemesh, ids, lengths[ids] < threshold)
    # flip_edge rewrites orig/dest only for the flipped half-edge and its twin, so this
    # is the exact set of applied flips (candidates rejected by can_flip_edge are excluded).
    did_flip = (hemesh_new.orig != hemesh.orig) | (hemesh_new.dest != hemesh.dest)
    return hemesh_new, did_flip

# %% ../nbs/src/03_topological_modifications.ipynb #d2df40a4
def remap_inds_removal_forward(N: int, removed: Int[jax.Array, " n_removed"]) -> Int[jax.Array, " N"]:
    """Remap indices after removal. Returns array arr[i] = i - (removed < i).sum()."""
    remap = jnp.arange(N)
    return remap - jnp.searchsorted(jnp.sort(removed), remap, side='left')  # left


def remap_inds_removal_reverse(N: int, removed: Int[jax.Array, " n_removed"]) -> Int[jax.Array, " N-n_removed"]:
    """Remap indices after removal. Reverse of remap_inds_removal_forward."""
    remap = jnp.arange(N)
    return jnp.delete(remap, removed, assume_unique_indices=True)


# %% ../nbs/src/03_topological_modifications.ipynb #05455739
@jax.tree_util.register_dataclass
@dataclasses.dataclass(frozen=True)
class MeshReindexMap:
    """Old↔new index maps produced by topology-changing operations."""
    v_forward: Int[jax.Array, " n_vertices_old"]
    v_reverse: Int[jax.Array, " n_vertices_new"]
    f_forward: Int[jax.Array, " n_faces_old"]
    f_reverse: Int[jax.Array, " n_faces_new"]
    he_forward: Int[jax.Array, " n_hes_old"]
    he_reverse: Int[jax.Array, " n_hes_new"]
    info: dict[str, Any] = dataclasses.field(default_factory=dict, metadata=dict(static=True))


# %% ../nbs/src/03_topological_modifications.ipynb #43101a21
def can_collapse_edge(hemesh: HeMesh, e: Int[jax.Array, ""] | int) -> Bool[jax.Array, ""]:
    """
    Check whether collapsing half-edge e would produce a valid mesh (link condition).

    An edge can be collapsed if it is interior and the two endpoint vertices share exactly
    two common neighbors (the opposite vertices of the two adjacent faces). This is the
    discrete "link condition" that ensures the collapse preserves manifoldness.

    Uses `hemesh.is_bdry_edge`, so boundaries are detected under both conventions
    (heface == -1 and vertices at infinity).
    """
    is_interior = ~hemesh.is_bdry_edge[e]
    # neighbour sets as per-vertex boolean masks: O(n_hes) rather than O(n_hes^2)
    v0, v1 = hemesh.orig[e], hemesh.dest[e]
    empty = jnp.zeros(hemesh.n_vertices, dtype=bool)
    nbrs_v0 = empty.at[hemesh.dest].max(hemesh.orig == v0)
    nbrs_v1 = empty.at[hemesh.dest].max(hemesh.orig == v1)
    n_common = jnp.sum(nbrs_v0 & nbrs_v1)
    return is_interior & (n_common == 2)


# %% ../nbs/src/03_topological_modifications.ipynb #67afc0b1
def collapse_edge(hemesh: HeMesh, e: Int[jax.Array, ""] | int
                  ) -> tuple[HeMesh, MeshReindexMap]:
    """
    Collapse half-edge e in a half-edge mesh. Keeps the origin vertex of e.
        
    Returns a new HeMesh (does not modify in-place), and a MeshReindexMap for remapping
    vertex, half-edge, and face indices from the original mesh to the new mesh.

    Warning: does NOT check whether the collapse produces a valid mesh. Use
    `can_collapse_edge` to check first.

    Not jitted, and inherently awkward to jit: the output arrays are smaller than the
    input, so every call with a different mesh size triggers a recompilation. On a mesh
    with vertices at infinity it cannot be jitted at all, since `inf_vertices` is a
    static field whose remapping requires concrete indices.
    """
    # identify relevant elements
    t = hemesh.twin[e]

    # make sure there's no vertex references to e or twin
    incident = hemesh.incident.at[jnp.array([hemesh.orig[e], # v1 
                                             hemesh.orig[hemesh.prv[e]], # v2
                                             hemesh.orig[hemesh.prv[t]]])].set( # v4
                                  jnp.array([hemesh.twin[hemesh.prv[e]],
                                             hemesh.twin[hemesh.nxt[e]],
                                             hemesh.twin[hemesh.nxt[t]]]))
    # re-twin the half-edges
    twin = hemesh.twin.at[jnp.array([hemesh.twin[hemesh.prv[e]],
                                     hemesh.twin[hemesh.nxt[e]], 
                                     hemesh.twin[hemesh.prv[t]],
                                     hemesh.twin[hemesh.nxt[t]]])].set( 
                          jnp.array([hemesh.twin[hemesh.nxt[e]],
                                     hemesh.twin[hemesh.prv[e]],
                                     hemesh.twin[hemesh.nxt[t]],
                                     hemesh.twin[hemesh.prv[t]]]))
    # edit orign and dest for all hes in/out of v3
    orig = jnp.where(hemesh.orig==hemesh.dest[e], hemesh.orig[e], hemesh.orig)
    dest = jnp.where(hemesh.dest==hemesh.dest[e], hemesh.orig[e], hemesh.dest)

    # delete the elements
    v_delete = jnp.array([hemesh.dest[e]])
    hes_delete = jnp.array([e, hemesh.nxt[e], hemesh.prv[e],
                            t, hemesh.nxt[t], hemesh.prv[t]])
    fs_delete =  jnp.array([hemesh.heface[e], hemesh.heface[t]])
    incident = jnp.delete(incident, v_delete, assume_unique_indices=True)
    face_incident = jnp.delete(hemesh.face_incident, fs_delete, assume_unique_indices=True)
    
    def delete_he(arr): return jnp.delete(arr, hes_delete, assume_unique_indices=True)
    orig, dest = (delete_he(orig), delete_he(dest))
    twin = delete_he(twin)
    nxt, prv = (delete_he(hemesh.nxt), delete_he(hemesh.prv))
    heface = delete_he(hemesh.heface)

    # index remapping: identity for v < hemesh.dest[e], v-> v-1 for
    remap_v = remap_inds_removal_forward(hemesh.n_vertices, v_delete)
    remap_he = remap_inds_removal_forward(hemesh.n_hes, hes_delete)  
    remap_f = remap_inds_removal_forward(hemesh.n_faces, fs_delete)

    index_map = MeshReindexMap(v_forward=remap_v,
                               v_reverse=remap_inds_removal_reverse(hemesh.n_vertices, v_delete),
                               f_forward=remap_f,
                               f_reverse=remap_inds_removal_reverse(hemesh.n_faces, fs_delete),
                               he_forward=remap_he,
                               he_reverse=remap_inds_removal_reverse(hemesh.n_hes, hes_delete),
                               info={"operation": "collapse_edge"})
    
    inf_vertices = tuple(int(remap_v[v]) for v in hemesh.inf_vertices)

    # special case: boundary hes need "-1" face
    is_bdry_he = jnp.delete(hemesh.heface == -1, hes_delete, assume_unique_indices=True)
    heface = jnp.where(is_bdry_he, -1, remap_f[heface])

    new_hemesh = HeMesh(incident=remap_he[incident], orig=remap_v[orig], dest=remap_v[dest],
                        twin=remap_he[twin], nxt=remap_he[nxt], prv=remap_he[prv],
                        heface=heface, face_incident=remap_he[face_incident], inf_vertices=inf_vertices)

    return new_hemesh, index_map

# %% ../nbs/src/03_topological_modifications.ipynb #3a3a3f64
def can_split_vertex(hemesh: HeMesh, e1: int, e2: int) -> bool:
    """
    Check whether splitting a vertex along half-edges e1 and e2 is valid.
    
    Both half-edges must originate from the same vertex, and both must be on interior faces.
    """
    return (hemesh.orig[e1] == hemesh.orig[e2] and
            hemesh.heface[e1] != -1 and hemesh.heface[e2] != -1 and e1 != e2)

# %% ../nbs/src/03_topological_modifications.ipynb #8a3a4335
def split_vertex(hemesh: HeMesh, e1: int, e2: int, check_args: bool=False) -> tuple[HeMesh, MeshReindexMap]:
    """
    Split a vertex into two along a "splitting axis" given by two half-edges originating at that vertex.
    
    New vertex inserted at origin of e2. The new vertex will be the final one in the array.

    This function is not JIT-compatible, since it depends on iterating around the vertex to update origins/destinations.
    """
    if check_args:
        assert hemesh.orig[e1]==hemesh.orig[e2] and not hemesh.heface[e1]==-1 and not hemesh.heface[e2]==-1, "invalid half edges"

    # create 1 new vertex, 6 new half-edges, and 2 new faces. By convention, at the end of the arrays
    incident = jnp.pad(hemesh.incident, (0, 1))
    face_incident = jnp.pad(hemesh.face_incident, (0, 2))
    orig, dest, twin, nxt, prv, heface = [jnp.pad(arr, (0, 6))
                                         for arr in [hemesh.orig, hemesh.dest, hemesh.twin, hemesh.nxt, hemesh.prv, hemesh.heface]]

    # the new elements are appended at the end
    vnew = hemesh.n_vertices
    fnew_1, fnew_2 = hemesh.n_faces, hemesh.n_faces+1 # faces of triangle of twin[e1] and triangle of twin[e2]
    enew_1, enew_2, enew_3 = hemesh.n_hes, hemesh.n_hes+1, hemesh.n_hes+2 # fnew_1, enew_1 is twin[e1]
    enew_4, enew_5, enew_6 = hemesh.n_hes+3, hemesh.n_hes+4, hemesh.n_hes+5 # fnew_2, enew_4 is twin[e2]

    # set incidents for new mesh elements
    incident = incident.at[vnew].set(e2)
    incident = incident.at[hemesh.orig[e1]].set(e1)  # ensure original vertex still points to a valid outgoing he
    heface = heface.at[jnp.array([enew_1, enew_2, enew_3])].set(fnew_1)
    heface = heface.at[jnp.array([enew_4, enew_5, enew_6])].set(fnew_2)
    face_incident = face_incident.at[jnp.array([fnew_1, fnew_2])].set(jnp.array([enew_1, enew_4]))

    # origin and destination of new half-edges
    orig = orig.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([hemesh.dest[e1], hemesh.orig[e1], vnew]))
    orig = orig.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([hemesh.dest[e2], vnew, hemesh.orig[e1]]))
    dest = dest.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([hemesh.orig[e1], vnew, hemesh.dest[e1]]))
    dest = dest.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([vnew, hemesh.orig[e1], hemesh.dest[e2]]))
    
    # nxt, prv, twin of new half-edges
    nxt = nxt.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([enew_2, enew_3, enew_1]))
    nxt = nxt.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([enew_5, enew_6, enew_4]))
    prv = prv.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([enew_3, enew_1, enew_2]))
    prv = prv.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([enew_6, enew_4, enew_5]))
    
    twin = twin.at[jnp.array([enew_1, enew_2, enew_3])].set(jnp.array([e1, enew_5, hemesh.twin[e1]]))
    twin = twin.at[jnp.array([enew_4, enew_5, enew_6])].set(jnp.array([e2, enew_2, hemesh.twin[e2]]))
    twin = twin.at[jnp.array([e1, e2])].set(jnp.array([enew_1, enew_4]))
    twin = twin.at[jnp.array([hemesh.twin[e1], hemesh.twin[e2]])].set(jnp.array([enew_3, enew_6]))

    # finally, need to update the origin and destination of half-edges into the "split" vertex.
    # iterate around the vertex from e2 to e1 to get the ones we need to update
    outgoing = [e2]
    while True:
        next_edge = hemesh.twin[hemesh.prv[outgoing[-1]]]
        if next_edge == e1:
            break
        outgoing.append(next_edge)
    outgoing = jnp.array(outgoing)
    orig = orig.at[outgoing].set(vnew)
    dest = dest.at[hemesh.prv[outgoing]].set(vnew)

    # no need to update the indices, since we appended the mesh elements at the very end
    new_hemesh = HeMesh(incident=incident, orig=orig, dest=dest, twin=twin, nxt=nxt, prv=prv,
                        heface=heface, face_incident=face_incident, inf_vertices=hemesh.inf_vertices)
    
    # need to find the "parents" of the new mesh elements
    v_reverse = jnp.arange(hemesh.n_vertices+1).at[vnew].set(hemesh.orig[e1])
    f_reverse = jnp.arange(hemesh.n_faces+2).at[jnp.array([fnew_1, fnew_2])].set(
                                                jnp.array([hemesh.heface[e1], hemesh.heface[e2]]))
    he_reverse = jnp.arange(hemesh.n_hes+6)
    he_reverse = he_reverse.at[jnp.array([enew_1, enew_2, enew_3])].set(
                              jnp.array([e1, e1, hemesh.twin[e1]]))
    he_reverse = he_reverse.at[jnp.array([enew_4, enew_5, enew_6])].set(
                              jnp.array([e2, e2, hemesh.twin[e2]]))
    index_map = MeshReindexMap(v_forward=jnp.arange(hemesh.n_vertices),
                               v_reverse=v_reverse,
                               f_forward=jnp.arange(hemesh.n_faces),
                               f_reverse=f_reverse,
                               he_forward=jnp.arange(hemesh.n_hes),
                               he_reverse=he_reverse,
                               info={"operation": "split_vertex", "split_edges": (e1, e2), "new_vertex": vnew})

    return new_hemesh, index_map
