# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/src/00_trigonometry.ipynb.

# %% auto #0
__all__ = ['get_circumcenter', 'get_oriented_triangle_area', 'get_triangle_area', 'get_polygon_area', 'project_on_vector',
           'project_out_vector', 'get_projector', 'get_signed_angle_between_vectors', 'get_angle_between_vectors',
           'get_cot_between_vectors', 'get_tetrahedron_volume', 'get_triangle_area_from_lengths',
           'get_angles_from_lengths', 'get_cotangents_from_lengths', 'get_circumcenter_from_lengths', 'get_rot_mat',
           'get_perp_2d', 'get_triangle_normal', 'quaternion_to_rot_max', 'get_barycentric_coordinates',
           'rotate_around_axis']

# %% ../nbs/src/00_trigonometry.ipynb #9f1cb15c-86cd-4e64-8f21-d4726216cd2f
import jax
import jax.numpy as jnp

import functools

# %% ../nbs/src/00_trigonometry.ipynb #723a50d1-f5c2-435c-9026-39b6067f426d
from jaxtyping import Float

# %% ../nbs/src/00_trigonometry.ipynb #7f22d2ad-1ddb-4cf3-b782-ef29639cb724
## trig functions - we can use vmap to vectorize them

@functools.partial(jax.jit, static_argnames=['zero_clip'])
def get_circumcenter(a: Float[jax.Array, " dim"],
                     b: Float[jax.Array, " dim"],
                     c: Float[jax.Array, " dim"], zero_clip: float = 1e-10) -> Float[jax.Array, " dim"]:
    """Return circumcenter coordinates of triangle with vertices a, b, c"""    
    # compute using barycentric coordinates. Start by computing the edge lengths:
    la, lb, lc = (jnp.linalg.norm(b-c), jnp.linalg.norm(c-a), jnp.linalg.norm(a-b,))
    ba, bb, bc = (la**2*(lb**2+lc**2-la**2), lb**2*(lc**2+la**2-lb**2), lc**2*(la**2+lb**2-lc**2))
    u = (ba*a+bb*b+bc*c)/jnp.clip(ba+bb+bc, zero_clip)  # avoid div by zero for degenerate triangles
    return u

def get_oriented_triangle_area(a: Float[jax.Array, " dim"],
                               b: Float[jax.Array, " dim"],
                               c: Float[jax.Array, " dim"]) -> Float[jax.Array, "*"]:
    """Signed area of triangle with vertices a, b, c. If d=2, returns a scalar, if d=3, a vector."""
    return 0.5 * jnp.cross(b - a, c - a)

def get_triangle_area(a: Float[jax.Array, " dim"],
                      b: Float[jax.Array, " dim"],
                      c: Float[jax.Array, " dim"]) -> Float[jax.Array, ""]:
    """Unoriented area of triangle with vertices a, b, c. Works in dim 2 or 3."""
    return 0.5 * jnp.linalg.norm(jnp.cross(b - a, c - a))

def get_polygon_area(pts: Float[jax.Array, "n_vertices 2"]) -> Float[jax.Array, ""]:
    """Area of 2D polygon assuming no self-intersection."""
    return jnp.sum(pts[:,0]*jnp.roll(pts[:,1], 1) - jnp.roll(pts[:,0], 1)*pts[:,1])/2

# %% ../nbs/src/00_trigonometry.ipynb #48180c1b
def project_on_vector(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                       ) -> Float[jax.Array, " dim"]:
    """Project vector a onto vector b"""
    norm = jnp.clip(jnp.dot(b, b), 1e-12)
    return jnp.dot(a, b) / norm * b


def project_out_vector(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                       ) -> Float[jax.Array, " dim"]:
    """Project vector a onto the plane orthogonal to vector b"""
    norm = jnp.clip(jnp.dot(b, b), 1e-12)
    return a - jnp.dot(a, b) / norm * b


def get_projector(normal: Float[jax.Array, " dim"]) -> Float[jax.Array, "dim dim"]:
    """Projector matrix P = I - n⊗n for a (not necessarily normalized) normal vector n.

    Parameters
    ----------
    normal : Float[Array, "dim"]
        Normal vector.

    Returns
    -------
    Float[Array, "dim dim"]
        Projection matrix onto the tangent plane.
    """
    normal = normal / jnp.clip(jnp.linalg.norm(normal), 1e-12)  # normalize to avoid scaling issues
    return jnp.eye(normal.shape[0]) - jnp.outer(normal, normal)


def get_signed_angle_between_vectors(a: Float[jax.Array, "2"], b: Float[jax.Array, "2"]
                                     ) -> Float[jax.Array, ""]:
    """Signed angle between two 2d vectors"""
    return jnp.atan2(jnp.cross(a, b), jnp.dot(a, b))


def get_angle_between_vectors(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                              ) -> Float[jax.Array, ""]:
    """Angle between two vectors"""
    return jnp.atan2(jnp.linalg.norm(jnp.cross(a, b)), jnp.dot(a, b))


def get_cot_between_vectors(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"]
                            ) -> Float[jax.Array, ""]:
    """Cotangent of angle between two vectors"""
    divisor = jnp.clip(jnp.linalg.norm(jnp.cross(a, b)), 1e-12)
    return jnp.dot(a, b) / divisor

# %% ../nbs/src/00_trigonometry.ipynb #e04b3dfe
def get_tetrahedron_volume(a: Float[jax.Array, " dim"], b: Float[jax.Array, " dim"], c: Float[jax.Array, " dim"]
                           ) -> Float[jax.Array, ""]:
    """Volume of tetrahedron defined by side vectors a, b, c"""
    return jnp.linalg.vecdot(a, jnp.cross(b,c)) / 6

# %% ../nbs/src/00_trigonometry.ipynb #07ef8c20
def get_triangle_area_from_lengths(la: Float[jax.Array, ""],
                                   lb: Float[jax.Array, ""],
                                   lc: Float[jax.Array, ""]) -> Float[jax.Array, ""]:
    """Triangle area from side lengths using Heron's formula.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, ""]
        Area of the triangle.
    """
    s = (la + lb + lc) / 2
    return jnp.sqrt(jnp.clip(s * (s - la) * (s - lb) * (s - lc), 0.0))


def get_angles_from_lengths(la: Float[jax.Array, ""],
                            lb: Float[jax.Array, ""],
                            lc: Float[jax.Array, ""]) -> Float[jax.Array, "3"]:
    """Interior angles from side lengths using the law of cosines.

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, "3"]
        Angles [alpha, beta, gamma] at vertices a, b, c respectively.
    """
    l2 = jnp.stack([la**2, lb**2, lc**2])               # [a², b², c²]
    l2_opp = jnp.roll(l2, -1) + jnp.roll(l2, -2) - l2   # [b²+c²-a², c²+a²-b², a²+b²-c²]
    denom = 2 * jnp.roll(jnp.stack([la, lb, lc]), -1) * jnp.roll(jnp.stack([la, lb, lc]), -2)
    cos_angles = jnp.clip(l2_opp / jnp.clip(denom, 1e-12), -1.0, 1.0)
    return jnp.arccos(cos_angles)


def get_cotangents_from_lengths(la: Float[jax.Array, ""],
                                lb: Float[jax.Array, ""],
                                lc: Float[jax.Array, ""]) -> Float[jax.Array, "3"]:
    """Cotangents of interior angles from side lengths.

    Uses cot(A) = (b²+c²-a²) / (4·area).

    Parameters
    ----------
    la : Float[Array, ""]
        Length of side opposite vertex a (i.e. edge bc).
    lb : Float[Array, ""]
        Length of side opposite vertex b (i.e. edge ca).
    lc : Float[Array, ""]
        Length of side opposite vertex c (i.e. edge ab).

    Returns
    -------
    Float[Array, "3"]
        Cotangents [cot_alpha, cot_beta, cot_gamma] at vertices a, b, c.
    """
    l2 = jnp.stack([la**2, lb**2, lc**2])
    l2_opp = jnp.roll(l2, -1) + jnp.roll(l2, -2) - l2
    area4 = jnp.clip(4 * get_triangle_area_from_lengths(la, lb, lc), 1e-12)
    return l2_opp / area4


@functools.partial(jax.jit, static_argnames=['zero_clip'])
def get_circumcenter_from_lengths(la: Float[jax.Array, ""],
                                  lb: Float[jax.Array, ""],
                                  lc: Float[jax.Array, ""], zero_clip: float = 1e-10) -> Float[jax.Array, "3"]:
    """
    Return circumcenter barycentric coordinates of triangle with edge lengths la, lb, lc.
    
    To compute the circumcenter u from the barycentric coordinates ba, bb, bc:
    u = ba * a + bb * b + bc * c
    where a, b, c are the triangle vertices.

    """    
    # compute using barycentric coordinates. Start by computing the edge lengths:
    ba, bb, bc = (la**2*(lb**2+lc**2-la**2), lb**2*(lc**2+la**2-lb**2), lc**2*(la**2+lb**2-lc**2))
    return jnp.array([ba, bb, bc])/jnp.clip(ba+bb+bc, zero_clip)  # avoid div by zero for degenerate triangles

# %% ../nbs/src/00_trigonometry.ipynb #f5fabd40
def get_rot_mat(theta: float) -> Float[jax.Array, "2 2"]:
    """Get 2D rotation matrix from angle in radians."""
    return jnp.array([[jnp.cos(theta), jnp.sin(theta)],[-jnp.sin(theta), jnp.cos(theta)]])

def get_perp_2d(x: Float[jax.Array, "... 2"]) -> Float[jax.Array, "... 2"]:
    """Get perpendicular vector."""
    return jnp.stack([x[..., 1], -x[..., 0]], axis=-1)

def get_triangle_normal(a: Float[jax.Array, "3"],
                        b: Float[jax.Array, "3"],
                        c: Float[jax.Array, "3"]) -> Float[jax.Array, "3"]:
    """Compute unit normal vector of triangle abc."""
    n = jnp.cross(b - a, c - a)
    return n / jnp.linalg.norm(n)

def quaternion_to_rot_max(q: Float[jax.Array, "4"]) -> Float[jax.Array, "3 3"]:
    """
    Convert unit quaternion into a 3d rotation matrix.
    
    See https://fr.wikipedia.org/wiki/Quaternions_et_rotation_dans_l%27espace
    """
    a, b, c, d = q / jnp.linalg.norm(q)
    return jnp.array([[a**2+b**2-c**2-d**2, 2*b*c-2*a*d, 2*a*c+2*b*d],
                      [2*a*d+2*b*c, a**2-b**2+c**2-d**2, 2*c*d-2*a*b],
                      [2*b*d-2*a*c, 2*a*b+2*c*d, a**2-b**2-c**2+d**2]])

# %% ../nbs/src/00_trigonometry.ipynb #8f94dd08
@functools.partial(jax.jit, static_argnames=['zero_clip', 'normalize'])
def get_barycentric_coordinates(point: Float[jax.Array, " dim"],
                                a: Float[jax.Array, " dim"],
                                b: Float[jax.Array, " dim"],
                                c: Float[jax.Array, " dim"],
                                zero_clip: float = 1e-10, normalize: bool = True) -> Float[jax.Array, "3"]:
    """Compute barycentric coordinates of point with respect to triangle abc."""
    bary, _, _, _ = jnp.linalg.lstsq(jnp.stack([a,b,c], axis=1), point)
    if normalize:
        bary = bary / jnp.clip(bary.sum(), zero_clip)
    return bary

# %% ../nbs/src/00_trigonometry.ipynb #649715eb
def rotate_around_axis(v: Float[jax.Array, "3"],
                       axis: Float[jax.Array, "3"],
                       angle: Float[jax.Array, ""]
                       ) -> Float[jax.Array, "3"]:
    """Rotate 3D vector v by angle (radians) around unit axis using Rodrigues' formula.

    Parameters
    ----------
    v : Float[Array, "3"]
        Vector to rotate.
    axis : Float[Array, "3"]
        Unit rotation axis.
    angle : Float[Array, ""]
        Rotation angle in radians.

    Returns
    -------
    Float[Array, "3"]
        Rotated vector.
    """
    return (v * jnp.cos(angle)
            + jnp.cross(axis, v) * jnp.sin(angle)
            + axis * jnp.dot(axis, v) * (1 - jnp.cos(angle)))
